### ISSUE TITLE
Lang/culture consistency

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#101]
Sometimes we have "culture" in the source code or in the DB cols names. Sometimes "lang".
I feel a bit uncomfortable with this inconsistency. That's a bit confusing.

Shouldn't we grep/replace "culture" by "lang" or "language" everywhere in the API and the UI?

**Comment by gberaudo** [comment]
+1 with a preference to `lang`.

**Comment by tsauerwein** [comment]
+1 for "lang" as well.

**Comment by asaunier** [comment]
OK, I suggest to wait after the steering committee before doing so :P

**Comment by tsauerwein** [comment]
At the same time we can also change the `l=...` parameter to `lang=...`.
