### ISSUE TITLE
Add public transport information in waypoints (accesses) listing

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_api#1067]
See #https://github.com/c2corg/c2c_ui/issues/846

Field `public_transportation_rating` should be included. I assume we do not need the `public_transportation_types` field.

**Comment by AntoineMarnat** [comment]
Any progress on this ?

**Comment by cbeauchesne** [comment]
nope ...

**Comment by florentcadot** [comment]
Hey!
My understanding is that we should add a `public_transportation_rating` in the `Route` table. It would make sense to also add a field in the `Route` create/update form front-end side, do you confirm ?

**Comment by eddy-geek** [comment]
mmm I'm discovering this, but I don't think new columns are needed, instead the existing `public_transportation_rating` data of the waypoints can be reused?

![image](https://github.com/c2corg/v6_api/assets/2772505/88e0480d-bfcf-4bfc-9aaf-aabec96236f7)

I'm guessing a *route* is accessible by public transport if at least one of its linked *waypoints* is accessible?

**Comment by florentcadot** [comment]
> mmm I'm discovering this, but I don't think new columns are needed, instead the existing `public_transportation_rating` data of the waypoints can be reused?
> 
> ![image](https://private-user-images.githubusercontent.com/2772505/309490267-88e0480d-bfcf-4bfc-9aaf-aabec96236f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDc3MzcsIm5iZiI6MTcwOTYwNzQzNywicGF0aCI6Ii8yNzcyNTA1LzMwOTQ5MDI2Ny04OGUwNDgwZC1iZmNmLTRiZmMtOWFhZi1hYWJlYzk2MjM2ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDI1NzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVkZWQzMGZlM2M5ZjYwMDEwODEyMjJjOTkxM2RiOWVmY2ZmMjJiOGRiZDg5OTVmNzk1NWY5MTFiNWY2NWViNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vdod-nxgdy70cv_W-33Rk6XSp_lVQUd7_HGtgjKlndo)
> 
> I'm guessing a _route_ is accessible by public transport if at least one of its linked _waypoints_ is accessible?

Isola 2000 :heart_eyes: (a bit of chauvinism, sorry) 


Understood, so does it mean `GET /routes` should return something like:

````json
{
    "documents": [
        {
            "document_id": 1055792,
            "version": 1,
            "locales": [ ... ],
            "geometry": {...},
            .....
            "areas": [],
            "waypoints": [
            {
                        "document_id": 14274,
                        "version": 11,
                        "locales": [...],
                         "public_transportation_rating": "good service" 
                    },
                        {
                        "document_id": 14275,
                        "version": 11,
                        "locales": [...],
                         "public_transportation_rating": "no service" 
                    },
            ]

`````
 
 ?

**Comment by brunobesson** [comment]
Sorry, I missed this disussion befor answering to he PR made for the frontend.

I made a mistake with the title of the issue. Indeed the idea is to have the `public_transportaion_rating` info on access points, not routes. This is what is missing for https://github.com/c2corg/c2c_ui/issues/846.

Having this information for routes could be interesting too, but it's another subject.

**Comment by Nayor** [comment]
There is no other issue open about having this information into routes, I think that's a very nice featureto have 🙂

**Comment by eddy-geek** [comment]
@brunobesson the mistake has been made, now the whole discussion here is about routes, so can we reopen and keep original title?

I like @florentcadot's idea for the API extension, having basic waypoint information on routes (just location+rating, and only for access points) seems to add quite some flexibility, for example to enable better display of the results.
