### ISSUE TITLE
Add ABO and ABO+ rating for global_rating

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/v6_api#1103]
See for example: 
https://www.camptocamp.org/routes/1316775
graded ABO+
https://www.outside.fr/le-recit-de-marek-holecek-la-face-ouest-du-baruntse-cest-lascension-la-plus-dure-que-jai-jamais-faite/

**Comment by brunobesson** [comment]
I do think it was a determined choice to use ED7 rather than ABO grading. @fbunoz ?

**Comment by fbunoz** [comment]
The ABO grades was used on beginning of c2c, but it has been replaced by EDx in 2009 : https://www.camptocamp.org/articles/188413/fr/aide-topoguide-cotation-alpine-globale#ed-et-edx-extremement-difficile-etendu
