### ISSUE TITLE
Test are brokken

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_api#1162]
https://github.com/c2corg/v6_api/runs/3536260758?check_suite_focus=true#step:13:594

**Comment by lbesson** [comment]
Salut j'ai pas trop compris à quel moment ça avait cassé ?

Egalement si je regarde les PRs de dependabot pour setuptools, pyproj ou encore zope-sqlalchemy, clairement c'est pas la maj de ces libs qui "casse" les tests?

**Comment by cbeauchesne** [comment]
Looking in our CI on master : https://github.com/c2corg/v6_api/actions/workflows/ci.yml?query=branch%3Amaster

The error started here : https://github.com/c2corg/v6_api/actions/runs/1161601070https://github.com/c2corg/v6_api/actions/runs/1161601070

The PR is https://github.com/c2corg/v6_api/pull/1143 but the PR CI was ok.

I'm not sure, but it can happen with thos workflowf : 

1. PR 1 => CI is ok 
2. PR 2 (PR 1 is not merged) => CI is ok
3. merge PR 1 => CI still ok, but CI on PR 2 does not re-run
4. merge PR 2 => not ok, but we usually do not check CI on master after a merge :( 

Here, `Bump pep8-naming from 0.12.0 to 0.12.1` may be the PR 2. Though, I do not have the time to look for PR 1 and confirm  my hypothesis :(

**Comment by lbesson** [comment]
Ok I shall have a look when I find time too. I doubt pep-naming PR is the
issue, it would only break lint, wouldn't it?

**Comment by cbeauchesne** [comment]
Yes, it would be very surprising. But not impossible though, libraries dependancies trees can lead to unexpected surprises sometimes :)
