### ISSUE TITLE
Bug: outings cannot be filtered by article

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_api#1175]
See e.g. https://www.camptocamp.org/articles/812624/fr/portail-chronique-ouverture (although the outings box is broken currently).
In recent outings box, the "show more" link directs to https://www.camptocamp.org/outings?c=382117
It returns all results, not filtering those linked to the specified article.

**Comment by cbeauchesne** [comment]
Duplicate of #745 ?

**Comment by brunobesson** [comment]
Indeed.
