### ISSUE TITLE
Test c2c in Chinese: route does not show in the list of associated route

### ISSUE THREAD

**Issue by hemind** [c2corg/v6_api#1186]
I have added four routes for a waypoint (https://c2corg.github.io/c2c_ui/chineese-in-api/#/waypoints/951883/zh/-), but only three of them are shown in the list of associated route (The Filter results will show all four routes.).

The missing route is https://c2corg.github.io/c2c_ui/chineese-in-api/#/routes/951885/zh/-

**Comment by AntoineMarnat** [comment]
Is this issue still relevant ?

**Comment by hemind** [comment]
@AntoineMarnat I can not repeat this issue now. it seems it's fine.
