### ISSUE TITLE
Geo-associations

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#128]
I paste here info sent by email to @tsauerwein a few days ago.

Geoassociations are associations between usual documents (WP, routes, outings, images, etc.) with region documents (http://www.camptocamp.org/areas => countries, CH cantons / F departements and ranges/massifs) and in some cases "paper maps" (http://www.camptocamp.org/maps)

* It's not worth spending too much time about maps. In v5 it's a kind of document but it's not that important. I don't think they are often used. The goal was to automatically list the maps without having to type the map names in a text field, at least in France and Switzerland where we had the geometries.
Not sure we even need to have a "map" document type in v6: if we can provide the list of maps (even without linking toward a detail page for the map) intersecting the current page geometry I guess it's enough.
Please note that we don't show linked maps in a document lists => the associations could be computed on the fly when showing a document if it has at least a default geometry.

* regions are more important since they can be used to filter documents (eg. "show me outings in Mont-Blanc range"). Regions associations may be needed in many pages (detail page, list page) for almost all doc types.
In v5 even books may be linked to regions (based upon linked routes)! For instance: http://www.camptocamp.org/books/704165/fr/scialpinismo-in-svizzera
To be honest, I wonder if it is really needed. Of course it's useful to get the list of guidebooks for a given region. But you don't do that kind of search very often.

It is worth figuring out if we stick to table-based geo associations (as in v5) or if we can use geographical operations by having a associated-docs-based default geometry when the document has no own geometry. The latter solution would be more flexible I think and would allow to make proximity searching or box/polygon filtering for all documents. It would also be needed (required?) for map-extent based filtering in search pages (see wireframes about "topoguide"/"page de recherche").

I wonder if we would not need a "point" default geometry for all documents, including the routes and outings. It would be useful for instance to:
* make map filtering (advanced search)
* show outings on the map: even if we have line geometries, it is probably more usable/performant to show markers rather than a bunch of lines? especially if all features have no own geometry. That probaby can be challenged since in some cases (routes in a WP page for instance) it's interesting to show the actual lines.
* make region filtering (not only a map extent filtering) => I guess it's more performant to get a list of points rather than lines when intersectiong with a polygons or even bboxes. Do you think we could replace the current v5 geo-associations filtering by point-geom-based intersections? Would it be too performances-hurting?

**Comment by asaunier** [comment]
Having a default geometry for all documents would also help to show other documents in the neighbourhood. For instance in an outing (or route or WP) page to get links towards other outings in the area. Or when trying to associate documents together, close documents could be suggested (as it's done in v5 for WP by the way). Etc.
Doing so we could replace associated-regions based links (not that relevent since the area could be too big). Regions association would then only be used for direct linking between regions and other documents.

**Comment by asaunier** [comment]
Related to #94

**Comment by tsauerwein** [comment]
I create a new issue for the part about the default geometry: https://github.com/c2corg/v6_api/issues/144
