### ISSUE TITLE
Python 3 changes break apache mode

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#130]
I have just tried to update the main instance (using apache) with the last version of master (switch to python 3). I have also tested reinstalling the instance from scratch (git clone). Apache has been restarted.

But the application fails when importing modules:

> (...)
[Tue Jan 12 19:19:48.739180 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/__init__.py", line 7, in <module>
[Tue Jan 12 19:19:48.739364 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]     from c2corg_api.models import (
[Tue Jan 12 19:19:48.739576 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/models/__init__.py", line 23, in <module>
[Tue Jan 12 19:19:48.739938 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]     from c2corg_api.models import document  # noqa
[Tue Jan 12 19:19:48.740090 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/models/document.py", line 22, in <module>
[Tue Jan 12 19:19:48.740497 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]     from c2corg_api.ext import colander_ext
[Tue Jan 12 19:19:48.740646 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/ext/colander_ext.py", line 11, in <module>
[Tue Jan 12 19:19:48.740911 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]     import pyproj
[Tue Jan 12 19:19:48.741078 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyproj/__init__.py", line 50, in <module>
[Tue Jan 12 19:19:48.741625 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512]     from pyproj import _proj
[Tue Jan 12 19:19:48.741915 2016] [wsgi:error] [pid 26185] [remote 10.27.71.4:512] ImportError: cannot import name _proj

**Comment by tsauerwein** [comment]
In [wsgi.conf](https://github.com/c2corg/v6_api/blob/master/apache/wsgi.conf.in) I think we have to specify which Python executable should be used by setting `WSGIPythonHome`. See http://stackoverflow.com/a/6450764/119937 I will try to get my instance working.

**Comment by tsauerwein** [comment]
It seems to be more complicated. mod_wsgi is always compiled against one Python version, in our case 2.7. We would have to re-compile mod_wsgi against 3.4 or install mod_wsgi for 3.4.

@mfournier Do you think we could already use Gunicorn or should we try to get mod_wsgi working with Python 3?

**Comment by gberaudo** [comment]
An alternative would be to install libapache2-mod-wsgi-py3.

**Comment by mfournier** [comment]
Fixed as suggested by @gberaudo.

NB: I renamed the legacy python2-based projects directories as follows:
```
/var/www/vhosts/c2cassoc_c2corgv6/private/:
total 12K
lrwxrwxrwx  1 root     sigdev    8 Jan 13 11:26 v6_ui -> v6_ui_p3
drwxrwsr-x 12 gberaudo sigdev 4.0K Dec 16 15:32 v6_ui_g
drwxrwsr-x 12 alex     sigdev 4.0K Jan 12 19:14 v6_ui_p2
drwxrwsr-x 12 alex     sigdev 4.0K Jan 12 19:09 v6_ui_p3

/var/www/vhosts/c2corgv6-api/private/:
total 8.0K
lrwxrwxrwx 1 root     sigdev    9 Jan 13 11:28 v6_api -> v6_api_p3
drwxrwsr-x 9 gberaudo sigdev 4.0K Jan  8 18:28 v6_api_p2
drwxrwsr-x 9 alex     sigdev 4.0K Jan 12 19:19 v6_api_p3
```

**Comment by tsauerwein** [comment]
Great, thanks Marc!
