### ISSUE TITLE
Return summit hierarchy when getting a summit

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#132]
For example: http://www.camptocamp.org/summits/38641/fr/aiguille-du-peigne

![c2corg-links](https://cloud.githubusercontent.com/assets/266474/12389673/6e82c8e4-bdda-11e5-9b03-4b585adecc16.png)

**Comment by stef74** [comment]
to be close ?

**Comment by tsauerwein** [comment]
It's up to the association to decide. :) I still think the summit hierarchy is useful and could be added later on.

**Comment by stef74** [comment]
I close for the moment, reopen if the topic need extra work.
