### ISSUE TITLE
Unittests vs Discourse settings

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#137]
Currently when running the tests on the API main instance one get the following error:

> ERROR: test_login_discourse_success (c2corg_api.tests.views.test_user.TestUserRest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/tests/views/test_user.py", line 81, in test_login_discourse_success
    redirect1 = discourse_redirect(moderator, sso, sig, self.settings)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_sso_provider.py", line 98, in discourse_redirect
    nonce = get_nonce_from_sso(sso, signature, key)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_sso_provider.py", line 88, in get_nonce_from_sso
    check_signature(payload, sig, key)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/security/discourse_sso_provider.py", line 37, in check_signature
    raise HTTPBadRequest('discourse login failed')
nose.proxy.HTTPBadRequest: discourse login failed
-------------------- >> begin captured logging << --------------------
sqlalchemy.engine.base.Engine: INFO: select version()
sqlalchemy.engine.base.Engine: INFO: {}
sqlalchemy.engine.base.Engine: INFO: select current_schema()
sqlalchemy.engine.base.Engine: INFO: {}
sqlalchemy.engine.base.Engine: INFO: SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
sqlalchemy.engine.base.Engine: INFO: {}
sqlalchemy.engine.base.Engine: INFO: SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
sqlalchemy.engine.base.Engine: INFO: {}
sqlalchemy.engine.base.Engine: INFO: show standard_conforming_strings
sqlalchemy.engine.base.Engine: INFO: {}
sqlalchemy.engine.base.Engine: INFO: BEGIN (implicit)
sqlalchemy.engine.base.Engine: INFO: SELECT users."user".password AS users_user_password, users."user".id AS users_user_id, users."user".username AS users_user_username, users."user".email AS users_user_email, users."user".email_validated AS users_user_email_validated, users."user".moderator AS users_user_moderator, users."user".temp_password AS users_user_temp_password 
FROM users."user" 
WHERE users."user".username = %(username_1)s
sqlalchemy.engine.base.Engine: INFO: {'username_1': 'moderator'}
c2corg_api.security.discourse_sso_provider: ERROR: Signature mismatch

@gberaudo told me that's because the actual secret key in our Discourse instance is not the same than in the test settings (publicly available on github). We would need to provide the secret key when running the tests so that the default (public) value is overridden.
We might also have issues with discourse-related tests since we don't really have a sandbox database where we could write stuff while testing...

**Comment by gberaudo** [comment]
The problem comes from the use of `-f config/something` when testing.
This gets the `sso_secret` from `config/default`, which is not the one expected for the tests.
See https://github.com/c2corg/v6_api/pull/140.

**Comment by tsauerwein** [comment]
But this still expects that a Discourse instance is running for the unit tests?

**Comment by gberaudo** [comment]
The issue was not due to a failing request to Discourse. It was due to the signatures of the sso stored in the test not matching the expected one.

**Comment by tsauerwein** [comment]
Ok. Still I would prefer that we test the integration with the forum using a mock client. I will give it a try.
