### ISSUE TITLE
Validate usernames

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#1383]
It is quite frequent to have users complaining they cannot sign in with their username until one figures out the username has a trailing " " in the database
=> additional username validation should be performed when creating a user account:

- at least strip the leading and trailing whitespaces
- most likely also get rid of the case (case insensitive). Note: there are username duplicates in the database if case is not considered => should we then automatically change those existing duplicates?

TODO :

- [ ] strip leading and trailing whitespaces in usernames (and passwords etc.) when creating an account
- [ ] strip leading and trailing whitespaces in usernames and passwords when authenticating
- [ ] make usernames case-insensitive
- [ ] add migration steps to prevent duplicates in existing usernames

**Comment by lbesson** [comment]
Imho we should also allow users to use email address to login in parallel to login.
And maybe trim spaces when they type the password

But then we need checks (for example if no current email is used as login by some other users, etc...)

**Comment by lbesson** [comment]
What about users who are actually using a space currently in their password :)

(but yes in that case, they won't be able to login, and maybe reach us, or use the forgotten password workflow)

**Comment by brunobesson** [comment]
![image](https://user-images.githubusercontent.com/2234024/190124660-2461daea-cfec-407f-a048-b11772d9dd2f.png)

**Comment by brunobesson** [comment]
> Imho we should also allow users to use email address to login in parallel to login.

👍

**Comment by brunobesson** [comment]
![image](https://user-images.githubusercontent.com/2234024/190125083-4e337764-aba8-457b-88be-2f7ff7da860a.png)

**Comment by brunobesson** [comment]
> Anyway I don't think I will address this topic in the current issue/PR.

Seems fair to me, let's do it step by step.
