### ISSUE TITLE
"None is not iterable" error

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#145]
From https://github.com/c2corg/v6_ui/issues/110

**Comment by tsauerwein** [comment]
See also: https://github.com/c2corg/v6_api/issues/55

**Comment by asaunier** [comment]
Closing since I think that c2corg/v6_ui#110 actually is a UI issue and #55 already have its own issue.

**Comment by asaunier** [comment]
Or else the API should accept both ``null`` or ``[]`` for unset/empty array attributes in the UI JSON requests?

@tsauerwein what do you think?

**Comment by tsauerwein** [comment]
> Or else the API should accept both null or [] for unset/empty array attributes in the UI JSON requests?

Yes.

I am closing this ticket as a duplicate of https://github.com/c2corg/v6_api/issues/55, but we (I) should fix this.
