### ISSUE TITLE
Auth management

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#16]
Interesting resources:

* http://blog.octo.com/en/design-a-rest-api/#security

> We recommend securing your API with OAuth2.

> Unlike OAuth1, OAuth2 allows you to manage authentication and resource authorization for any type of application (native mobile app, native tablet app, JavaScript app, server side web app, batch processing…) with or without the resource owner’s consent.
> OAuth2 is the de facto standard for securing APIs. Using another technology would slow down your API development and adoption.

* http://stackoverflow.com/questions/549/the-definitive-guide-to-form-based-website-authentication

Interesting (?) implementations:
* https://github.com/elliotpeele/pyramid_oauth2_provider
* https://github.com/tilgovi/pyramid-oauthlib
* https://github.com/idan/oauthlib
* https://github.com/sneridagh/osiris
* https://github.com/hathawsh/yasso
* http://peterhudec.github.io/authomatic/ - https://github.com/peterhudec/authomatic (but used to authenticate against a third-party oauth provider - not sure it may help us)
* https://github.com/omab/python-social-auth (auth through social networks tools)

**Comment by gberaudo** [comment]
According to the wikipedia page about OAuth, OAuth2 suffers from many
security flaws.
Are there some requirements about the version we need to use?

**Comment by asaunier** [comment]
> Are there some requirements about the version we need to use?

No. Using OAuth is not even required.

**Comment by tsauerwein** [comment]
Best-practice on how to implement a remember-me function: http://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website

**Comment by tsauerwein** [comment]
What requirements do we have for the authentication/authorization?

 * We must be able to support multiple clients.
 * It should scale. That is it should be possible to run multiple instances of the REST API.
 * ?

Two more resources that are worth reading:
https://scotch.io/tutorials/the-ins-and-outs-of-token-based-authentication
https://scotch.io/tutorials/the-anatomy-of-a-json-web-token

**Comment by asaunier** [comment]
Something that might be useful/required in the future: be able to sign in using a Facebook/Google/Twitter/... account (ie. a third-party auth service).

**Comment by asaunier** [comment]
> Three more resources that are worth reading:

Thanks @tsauerwein those articles are indeed really interesting. In short they explain what token-based auth brings: stateless/scalability, increased security, mobile app support, etc.

**Comment by tsauerwein** [comment]
Eric pointed me to the Pyramid [AuthTK authentication module](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html#authentication-module), which is used in c2cgeoportal. It is also a token based approach, so no state is saved on the server. It uses a [cookie](http://stackoverflow.com/questions/12765349/pyramid-authtktauthenticationpolicy-secret-parameter/12767843#12767843) to pass around the token. Maybe that would be enough for our requirements.

**Comment by tsauerwein** [comment]
And one more link:
http://www.seedbox.com/en/blog/2015/06/05/oauth-2-vs-json-web-tokens-comment-securiser-un-api/

It compares OAuth with a token-based technique (JSON Web Tokens).

**Comment by elemoine** [comment]
JWT is interesting. And, AFAIU, it is very close to the AuthTkt approach we use in c2cgeoportal, except that AuthTkt uses cookies.

FWIW, my search engine has found https://github.com/ajkavanagh/pyramid_jwtauth.

**Comment by tsauerwein** [comment]
> JWT is interesting. And, AFAIU, it is very close to the AuthTkt approach we use in c2cgeoportal, except that AuthTkt uses cookies.

You can also store JWT in cookies. The main difference is that with AuthTkt the token is simply a hash. With JWT the token actually contains information, like the user id, the expire date, the roles that a user has, ... So the authentication server could include this information in the token, and the client can make use of it.

> FWIW, my search engine has found https://github.com/ajkavanagh/pyramid_jwtauth.

I tested this package, once you figure out on how to integrate it in a Pyramid app, it seems to work quite well.

**Comment by elemoine** [comment]
The AuthTkt cookie may also include user data. But Pyramid's AuthTktAuthenticationPolicy uses this user data to store the userid type, which is used at cookie decoding type to decode the userid into its correct type.

**Comment by elemoine** [comment]
AuthTkt and JWT are quite close. The advantage of JWT is that it's a modern protocol, developed by the IETF. Another advantage is that it's compatible with both the browser and mobile applications. For these reasons I think JWT is good choice. I'd go with that.

**Comment by tsauerwein** [comment]
> The advantage of JWT is that it's a modern protocol, developed by the IETF. Another advantage is that it's compatible with both the browser and mobile applications. For these reasons I think JWT is good choice. I'd go with that.

+1

**Comment by gberaudo** [comment]
There is an article about critical issues in libraries implementing JWT.
If we go with this, let's not forget to check it is fixed:
https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by elemoine** [comment]
Very nice article @gberaudo!

**Comment by tsauerwein** [comment]
Automatic renewal of tokens: http://stackoverflow.com/a/26834685/119937

Token expiration:
>
 This is the approach I'm taking with my system - all generated tokens are stored in a DB (redis) and on each request, I verify that the token is in my DB before I accept it. This way tokens can be revoked for any reason, such as tokens that were released into the wild somehow, user logout, password changes, secret changes, etc.
http://stackoverflow.com/questions/30523238/best-practices-for-server-side-handling-of-jwt-tokens

**Comment by asaunier** [comment]
Is this issue the right place to talk about usage quotas / preventing abusing usages?
@mfournier told me today that github uses a kind of token with a "per hour allowed actions" counter that is decremented whenever a user makes a request.

**Comment by tsauerwein** [comment]
I made a summary of our last discussion: https://github.com/c2corg/v6_api/wiki/Authentication-Concept

**Comment by tsauerwein** [comment]
@asaunier We have a separate ticket for that: https://github.com/c2corg/v6_api/issues/9

**Comment by asaunier** [comment]
OK, I just wanted to remind of this topic in case it could/should be handled through the auth tools.

**Comment by asaunier** [comment]
Any objection to closing this issue?

**Comment by elemoine** [comment]
Not at all :)

**Comment by asaunier** [comment]
Thanks Eric!
I'm glad to see that you miss the project (and the project misses you) :)

**Comment by tsauerwein** [comment]
:)
