### ISSUE TITLE
Migration script: abstract tag

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#165]
> The current script to migrate the topoguide, detects the [abs] tags to put the content into the new abstract field.
> In the V5, there are 2 tags to define an abstract : [abs] and [abstract]. They are decoded in the same html code. "abs" is only a shortcut for "abstract".
> The content between [abstract] tags must be migrated as the [abs] tags.

from https://github.com/c2corg/v6_ui/issues/213

**Comment by fbunoz** [comment]
The abstract tag migrating doesn't work : 
- [abstract] tag content is lost, and "abstract" field is filled with "tract".
- [abs] tag content is lost, and "abstract" field is empty

**Comment by tsauerwein** [comment]
Thanks for noticing, fix is in PR https://github.com/c2corg/v6_api/pull/323

**Comment by fbunoz** [comment]
Alpha 2 tests shows that the issue is fixed.
