### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#18]
As for now the collection_get() method returns the whole list of documents, which is not realistic since we have too many items.

Applying a default limit and using pagination technics is then required.

By the way it seems the usual LIMIT/OFFSET approach [1]  might cause performance issues when the offset increases (because postgresql has to deal with more rows before slicing them).

Some resources on the web recommend to use the "seek method":
http://leopard.in.ua/2014/10/11/postgresql-paginattion/
http://chrisdone.com/posts/postgresql-pagination
http://winand.at/slides/PaginationDoneTheRightWay.pdf
that does not use OFFSET but a standard WHERE clause combined to LIMIT.

A drawback is that you need to know the id of the last item of the current page to get the x items whose ids are next. It seems it is especially recommended for "infinite scrolling" requests or for "next page" links.

[1] With SQLAlchemy: most likely done using slice() http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html#sqlalchemy.orm.query.Query.slice

**Comment by elemoine** [comment]
Here's another interesting article on implementing "pagination" the right way: http://www.servicedenuages.fr/pagination-continuation-token.

**Comment by asaunier** [comment]
Perhaps we should have a look at Cliquet (at least how it works) since it seems to provide pagination: http://cliquet.readthedocs.org/en/latest/api/resource.html#paginate

**Comment by tsauerwein** [comment]
For the *traditional* limit/offset approach there is a module that makes it easy to do pagination in Pyramid apps: `webhelpers.paginate`
http://sluggo.scrapping.cc/python/WebHelpers/modules/paginate.html
Hera an example on how to use it: https://github.com/camptocamp/c2cgeoform/blob/master/c2cgeoform/views.py#L255-L274

Even if we want to do token pagination, we can maybe borrow ideas from `webhelpers.paginate` about the abstraction.
