### ISSUE TITLE
Manage merged documents

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#185]
For instance:
http://www.camptocamp.org/routes/640047/fr/depuis-les-baudes-boucle-par-le-plan-des-eaux-et-le-col-de-bounavalette
appears normally in v6 (with no associated WP):
http://c2corgv6-demo.gis.internal/routes/640047/fr

How does the API returns merged documents?

Perhaps migrating to v6 would be a good opportunity to get rid of the old merged documents during the migration (but we will still need to support documents merged in v6).

**Comment by tsauerwein** [comment]
Merged documents are migrated as such but not yet handled differently.

**Comment by tsauerwein** [comment]
> Perhaps migrating to v6 would be a good opportunity to get rid of the old merged documents during the migration (but we will still need to support documents merged in v6).

We could ignore merged documents during the migration. But wouldn't you somehow lose the history of a document? I mean we could also simply migrate only the last version, but still we get all versions.

> How does the API returns merged documents?

How exactly should merged documents be handled?

- Not indexed in ElasticSearch.
- Not editable.
- What should be returned? Only `{merged: 12345}` or all the data?

**Comment by asaunier** [comment]
> But wouldn't you somehow lose the history of a document?

Merged documents are already neither searchable nor listed. If you don't have the link you cannot find such documents. Merged documents are generally poor quality documents or not very useful. It's no use having them editable.
It's not a big deal if they are removed. For me it is unnecessary complexity to have those merged documents remaining in the DB. In addition they cause a search engine issue: instead of keeping them (even with a link toward the remaining document), it would probably be better to make a 301 redirection.

> How exactly should merged documents be handled?

Of course not indexed and not editable.
Returning only the id of the target document would make sense so that the UI makes a 301 redirection.
