### ISSUE TITLE
Sending emails

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#186]
How are we going to send emails?
Do we have credentials for an smtp server?

**Comment by gberaudo** [comment]
@mfournier says we are currently using the psemail SMTP relay.
An alternative would be to use an external service.

The psemail relay is available from the dev server (not from the desktops).

**Comment by tsauerwein** [comment]
How many mails are currently being sent? E.g. SparkPost offers a free service for less than 100 000 mails per month: https://www.sparkpost.com/pricing

**Comment by gberaudo** [comment]
I configured the psemail SMTP relay like it was done in v5.
