### ISSUE TITLE
return additional values for outings list 

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#187]
In order to match the mock-ups, I would need additional values in the outings/index view, such as outing :
- activities
- ratings
- elevations
- areas

or other if those are relevant.

**Comment by tsauerwein** [comment]
Adding the fields `activities`, `elevation_max` and `height_diff_up` is no problem. But the ratings belong to associated routes. Is this information really needed, @asaunier?

**Comment by ginold** [comment]
Maybe i'm wrong saying i need ratings, but in the mockups there are some
'T1' and 'PD' values, maybe it is 'condition_rating'?

On Wed, Mar 16, 2016 at 4:38 PM, Tobias Sauerwein <notifications@github.com>
wrote:

> Adding the fields activities, elevation_max and height_diff_up is no
> problem. But the ratings belong to associated routes. Is this information
> really needed, @asaunier <https://github.com/asaunier>?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/c2corg/v6_api/issues/187#issuecomment-197387690>
>



-- 

*Adam Gina*JavaScript Developer
adam.gina@camptocamp.com

*Camptocamp SA*EPFL Innovation Park
Bâtiment A
1015 Lausanne

Tel + 41 21 619 10 10
http://www.camptocamp.com

**Comment by asaunier** [comment]
> Adding the fields activities, elevation_max and height_diff_up is no problem.

Those fields are directly related to the outing itself.

Ratings do belong to routes but are needed as well in the associated routes cards. See for instance in v5: http://www.camptocamp.org/outings/732749/fr/aiguille-du-midi-vallee-blanche-classique

Perhaps the ratings should be added to the "listing" fields?

**Comment by tsauerwein** [comment]
@asaunier We are talking about the outing listings. In the mockups and [v5](http://www.camptocamp.org/outings/), the ratings (which belong to associated routes) are shown for each outing. Is this really required? Does it hurt the usability if you have to click on an outing to see the ratings of associated routes? If so I would have to make at least one additional database query to get these ratings for the list view.

**Comment by asaunier** [comment]
> Is this really required?

Kind of, yes. Because it gives important data about the outing itself to know what routes have been done, with the orientations and the ratings. For instance to understand the snow and avalanche conditions.

**Comment by tsauerwein** [comment]
> Kind of, yes. Because it gives important data about the outing itself to know what routes have been done, with the orientations and the ratings. For instance to understand the snow and avalanche conditions.

But is it required that this information is available in the list view? You will see it when you go to the detail page of an outing.

> ... with the orientations and ...

The orientation is not shown in the outings list view of v5.

**Comment by asaunier** [comment]
> But is it required that this information is available in the list view?

I have just asked the client. I'll let you know.

**Comment by asaunier** [comment]
Personally I think ratings are not that important in outings list page and that we should only display outing-related info in outing cards.

By the way we will use cards layout to list associated outings in a route page, we then do not need to display route-related info in those outings cards. To be consistent we should then not display ratings in outing cards, wherever they are displayed.

In addition those ratings stuff are quite complicated since we may have several ratings (including from several activities) at the same time. And if the outing is associated to several routes, the highest ratings must be displayed.

Arf...

Many people in the association are reluctant to give up ratings in outing lists. So we might have to show them anyway.

But as for now, I recommend not having route-related info (eg. ratings) in outing lists/cards, only outing-related attributes.

**Comment by asaunier** [comment]
> Many people in the association are reluctant to give up ratings in outing lists. So we might have to show them anyway.

It seems that when v5 came out in 2007/2008, associated routes ratings were not displayed in outings list and that users were pretty upset: http://www.camptocamp.org/forums/viewtopic.php?id=114512
Those info had to be added eventually. Not sure we can avoid this in v6.

**Comment by tsauerwein** [comment]
Ok, I didn't know that the ratings are so useful. We can add the ratings, I just wanted to be sure that they are of use.

>  And if the outing is associated to several routes, the highest ratings must be displayed.

v5 takes the rating of the highest associated route: https://github.com/c2corg/camptocamp.org/blob/602b46c9388436cbbd21f99dde856065d33d0fed/batch/pushOutings.php#L62-L82

That sounds more reasonable than trying to compare different ratings.

**Comment by asaunier** [comment]
> v5 takes the rating of the highest associated route:

This script is used to push outings to an outings meta engine that aggregates outings from various websites: http://meta.camptocamp.org/

It is not used for showing data in the v5 outings :)

By the way what does "the highest associated route" means? If you have done 2 routes on the same summit, which one is the highest? :P 

I'm trying to figure out where the ratings displayed in outings are gathered.

**Comment by asaunier** [comment]
> I'm trying to figure out where the ratings displayed in outings are gathered.

The outings listing view:
* gets the list of outings
* gets the list of outings associated to all those outings

See https://github.com/c2corg/camptocamp.org/blob/602b46c9388436cbbd21f99dde856065d33d0fed/apps/frontend/modules/outings/actions/actions.class.php#L645

For a given outing, it loops among the associated routes and figures out the biggest value for each route attribute available:
https://github.com/c2corg/camptocamp.org/blob/8e240652f9bcf9c19e2e7499751aaa970355e07d/lib/model/doctrine/Outing.class.php#L930-L938

**Comment by tsauerwein** [comment]
> ... for each route attribute available:

Are really all route attributes required. As far as I can see only the ratings and facings are actually used when showing an outing. Is that correct?

**Comment by fbunoz** [comment]
> Are really all route attributes required. As far as I can see only the ratings and facings are actually used when showing an outing. Is that correct?

The max_elevation and height_diff_up route fields are also used in V5, to replace the similar outing fields when they are empty. Specially for the outings created in the V4, because the migrating V4>V5 didn't copy these fields. But it is not critical for the V6.

**Comment by asaunier** [comment]
> The max_elevation and height_diff_up route fields are also used in V5, to replace the similar outing fields when they are empty.

You mean, in the document page itself, not in the lists (cards)?
In v5, aren't those route data used to fill the corresponding outing attributes with default values in the editing form?

Then we would not need to get them from associated routes when generating the lists/cards, only the ratings and facings (not available in the outings anyway)?

**Comment by ginold** [comment]
I still need:
- quality 
- GPS track
- height diff difficulties
- height diff
- orientations

**Comment by asaunier** [comment]
> quality

This is a standard document attribute.

> GPS track

This is the geometry.

> orientations
> height diff difficulties

Those are are not outing attributes => ignore them.

> height diff

Use ``height_diff_up`` https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/outing.py#L53

**Comment by ginold** [comment]
Attributes above are not returned in simple search nor in associated documents, where I need them.

**Comment by ginold** [comment]
I probably posted this comment in the wrong issue :p

**Comment by asaunier** [comment]
> Attributes above are not returned in simple search nor in associated documents, where I need them.

This is not an API issue, you should update https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L44-L53

**Comment by stef74** [comment]
@ginold @asaunier issue still relevant ?

**Comment by stef74** [comment]
@asaunier we probably decide to add condition ... we need to add "locales.conditions" in DEFAULT listing of field_outings.py  ?

**Comment by asaunier** [comment]
``locales`` contains all the text attributes of a document. ``locales.conditions`` is the text attribute where people write sentences about conditions. Is it really the attribute you want to add to the cards?

I guess it's rather ``condition_rating``?
https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L31
If yes it should be added to ``DEFAULT_LISTING`` here
https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_outing.py#L42

**Comment by cbeauchesne** [comment]
Ratings is now part of outing's model. Close issue.
