### ISSUE TITLE
Add a geom table to archive the geometry field

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#19]
Since a document geometry may be a bit big, it is a pity to duplicate it in the archives every time someone makes a change in the docs figures.

A solution would be to separate the geometry field into a dedicated geom archives table that would be joined to the other archive tables using a foreign key in the documents_versions table.

To be able to store the geometries of the various doc types (point, line, polygon), using a generic "geometry" type is probably relevant. Would such a field have drawbacks on the other hand?

What about documents with no geometry by nature (books, articles) or with a null geometry? Would they have a null FK in documents_versions?

**Comment by elemoine** [comment]
Theoretically, this sounds good to me.

**Comment by tsauerwein** [comment]
Done with #42.

> What about documents with no geometry by nature (books, articles) or with a null geometry? Would they have a null FK in documents_versions?

The geometry is not required, like you say the FK in document_versions will be null in that case. To enforce a geometry for a specific document type (e.g. for waypoint), we can add a validator only for waypoint.
