### ISSUE TITLE
Return the same fields for simple search as for listings?

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#192]
Currently the schema for the documents returned in the simple search is the same as in listings. Are all these fields required? Currently only the title is used in the UI, so I wonder if we could omit the other fields (like geometry, elevation, activities, ...).

**Comment by asaunier** [comment]
Maybe geometry yes. But we will need additional info to distinguish the homonym documents.
For instance we have 2 "Mont Blanc".

Giving the area and elevation would help for WP.
For routes, we would need the activities and the ratings I think.
