### ISSUE TITLE
Handle i18n when sending emails

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#194]
See #190, notably https://github.com/c2corg/v6_api/pull/190#issuecomment-199720299.
TODO:
- [x] register email;
- [x] change password email.

> For the translations for the email: I would propose to start simple without a translation framework and have an email template for each language, e.g.
> 
> /email_templates
>     /registration
>         en.mako
>         fr.mako
>         ...
>     /password_forgotten
>         ...

**Comment by tsauerwein** [comment]
How well does gettext work for longer texts like email templates?

**Comment by asaunier** [comment]
I guess those gettext (or whatever) translations be done on the API server. Then it means it is completely separated from the translations on the UI, thus being a separated gettext project on transifex. Anyway we have to make sure those server translations are not provided in the JSON i18n files downloaded by the browsers.

By the way, if we had translations on the API side, should we translate the error/info messages returned by the API directly on the API side and no longer in the UI?

**Comment by asaunier** [comment]
> How well does gettext work for longer texts like email templates?

Why would it be a problem? gettext msgids may contain "variables" that would then be replaced by the username and validation links for instance.

Please note we will probably have to send emails not only for user subscription or password renewal. For instance in v5, notification emails are sent when a user is associated to an outing.
The corresponding email translation in v5 PO files:
https://github.com/c2corg/camptocamp.org/blob/master/apps/frontend/i18n/messages.fr.po#L3015-L3023

**Comment by tsauerwein** [comment]
> Why would it be a problem? gettext msgids may contain "variables" that would then be replaced by the username and validation links for instance.

Sure it's possible. But is it convenient? Because the email template would be a multi-line string. Would you create a separate translation string for each paragraph? Or have one translation string for the whole text? What if you want to use html for the email?

**Comment by asaunier** [comment]
Just have a look at my example above :P 
A msgstr may contain several lines and HTML tags.

Anyway we don't need to send long emails. Only a few sentences/lines.

**Comment by tsauerwein** [comment]
> Just have a look at my example above :P 

Sorry, I didn't click on the link. :)

**Comment by tsauerwein** [comment]
@gberaudo Can be closed? For gettext there is a separate issue: #238
