### ISSUE TITLE
Clean non validated users

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#195]
When a user is registered but the email is not validated in the delay, the user must be deleted.
See also https://github.com/c2corg/v6_api/pull/190#discussion_r57027022.

**Comment by tsauerwein** [comment]
Or rather:

>  Maybe it would make sense to delay the creation of the user-profile until the account is confirmed. Otherwise un-confimed users might show up in the search and listings.

**Comment by asaunier** [comment]
+1 with @tsauerwein proposal: no use creating the profile until the account is confirmed.

**Comment by asaunier** [comment]
Closing since duplicate of https://github.com/c2corg/v6_api/issues/218
