### ISSUE TITLE
Outings list should be antichronologically ordered by default

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#197]
Unless a criteria says the contrary, outings should always be listed the newest first.
As for now the default outings list page shows outings from 2015, 2004, 2002...

**Comment by tsauerwein** [comment]
Like the other documents, outings are ordered by the document id (like in v5). As it is possible to date back an outing, you are seeing outings from 2004.

But it would make sense to order outings by `date_start` or `date_end`.

**Comment by asaunier** [comment]
Do you mean we should always explicitely provide the sorting parameters to the API request?

**Comment by tsauerwein** [comment]
> Do you mean we should always explicitely provide the sorting parameters to the API request?

**Comment by asaunier** [comment]
I mean it doesn't make sense that default outings lists in v5 are not date-sorted.
Perhaps the UI should call the API specifiying

**Comment by asaunier** [comment]
Oops closed the issue by mistake :P 

> But it would make sense to order outings by date_start or date_end.

:+1: 

I have just asked the client how outings should be sorted when date_start != date_end. For instance what date should be used in outings lists. Most likely ``date_end``.
