### ISSUE TITLE
Convert PHP serialized object to JSON

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#200]
Outing property "conditions_levels" is a serialized PHP array, it would be great if during the next DB migration it were converted into a JSON object so i can manipulate it with angular. For now it looks like :
`a:6:{
  i:0;
  a:4:{
    s:11:"level_place";
    s:64:"Départ du virage 1380 entre Liddes et Chandonne (torrent), 8h30";
    s:22:"level_snow_height_soft";
    s:1:"0";
    s:23:"level_snow_height_total";
    s:0:"";
    s:13:"level_comment";
    s:149:"Neige dure, 10m de déchaussage en passant par le clou mais sinon nickel. La neige est un peu plus meuble dans les parties ombragées dans la forêt.";
  }
}`

**Comment by tsauerwein** [comment]
A serialized PHP object?! :O

**Comment by ginold** [comment]
*array :P

**Comment by asaunier** [comment]
Perhaps we should use the python package "phpserialize" https://pypi.python.org/pypi/phpserialize in the migration script in order to unserialize those PHP objects and then ``json.dumps``?

**Comment by tsauerwein** [comment]
`phpserialize` looks promising!
