### ISSUE TITLE
Do not store archive versions for user profiles

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#203]
Quoting Alex:

> I recommend then that all history and archives are public, including for outings => same policy for all documents.
> 
> * User profiles are a bit special though because they may indeed contain really private info such as phone numbers etc. + I admit people might be reluctant that their activity is too easily accessible to anyone. This page is anyway very special since:
> - only one user is supposed to change it (the user himself - even though moderators can do changes as well - but generally don't have to).
> - the page content is mainly a description attribute + some figures (user categories and practised activities) + possibly a point geometry + links towards the user's outings, forum posts, etc. But will also provide a feed similar to the homepage (most likely using AJAX requests).
> - the page title (guidebook name) comes from the user settings.
>
> ...
> For user profiles I would then recommend to:
> - not archive old versions => when a user changes his description, no new version is created, the description is simply updated in the database => not history or old versions

**Comment by asaunier** [comment]
I think we should also change the migration script so that only the last profile version is imported to v6.

**Comment by tsauerwein** [comment]
As discussed with @asaunier, we decided to keep the history also for user profiles to avoid additional work. Also this enables us to later add a history page for profiles if required.
