### ISSUE TITLE
Consider using a sitemap for SEO

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#205]
The advanced search will replace the current listing pages. On advanced search pages, new results will be fetched with a XHR request. But for SEO reasons we would also need to render some kind of listing pages on the server-side so that search engines are able to discover all pages.

If we would use the advanced search for these pages rendered on the server-side, ElasticSearch would always be involved. To reduce the load on ES, we could consider generating sitemap files only for the search engines. These sitemaps would be very easy to cache and would be generated without sending requests to ES.

See also: http://www.sitemaps.org/protocol.html#index

**Comment by asaunier** [comment]
Shouldn't this be an issue in the UI rather than the API?

**Comment by tsauerwein** [comment]
It's relevant for both.

**Comment by asaunier** [comment]
> It's relevant for both.

Do you plan to have a sitemap for the API as well?
Or only on the UI side?

**Comment by tsauerwein** [comment]
Where will the UI get the information to generate the sitemap? From the API. :)

You won't use the existing list views to request the data for the sitemap. We will need some optimized service which returns simply the document ids (probably also the locales) for each document type (paginated).

**Comment by asaunier** [comment]
OK, I thought we could use the usual API list view with ``?a=0`` to skip the associations. Don't you think it could be enough? What optimizations do you think of?
Sure we need the lastmod which is probably not available in the usual list views (but it could? what about having the info in the detail view as well?).

**Comment by tsauerwein** [comment]
> OK, I thought we could use the usual API list view with ?a=0 to skip the associations. Don't you think it could be enough? What optimizations do you think of?

We only need document id, available locales and a `lastmod` date, not all the other fields that are included for normal list views. And considering that this sitemap view is going to return all documents, it should be optimized to avoid putting unnecessary load on the database.
