### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#206]
- [ ] The simple search sometimes returns unexpected results. For instance:
- "calanques oule" does not find "Calanques - L'Oule (Belvédère)". "calanques belvedere" does.
-  Route "Pic de Roche Motte : boucle sud nord": "boucle sud nord" -> nothing, "boucle sud no" -> ok (from https://github.com/c2corg/v6_api/issues/243#issuecomment-211292897)
- For example typing "beau comme un r" gives me some results without routes, then adding continuing with "beau comme un re" gives me plenty of routes, "beau comme un rev" with routes, but deleting "v" -> back to "beau comme un re" gives results with routes.
- When creating an outing, the tool to associate other members does not find some members: it's OK for "Bruno Besson", "Frédéric Bunoz", but it does not find "LaurentB2", "Pierre P",.... And there is no more "Plus de résultats" button to see more results.

**Comment by asaunier** [comment]
* [ ] the performances (at least on the dev server) are quite poor

**Comment by asaunier** [comment]
I have removed the "advanced Search" label since it's rather an ElasticSearch issue (concerns the simple search as well).

Another example of results with a poor relevancy:

typing "Dent de Barme", the simple search returns results like "Dent d'Oche" or "Dent du Géant", as if the search was on "dent" OR "barme" instead of "dent" AND "barme".

<img width="520" alt="capture d ecran 2016-05-14 a 13 51 18" src="https://cloud.githubusercontent.com/assets/1192331/15268338/4dca88aa-19db-11e6-9ef8-352e3e72a057.png">

**Comment by tsauerwein** [comment]
@fjacon Should this be addressed for alpha2?

**Comment by fjacon** [comment]
yes, for alpha2

**Comment by asaunier** [comment]
As for now, the text search is really unusable because it returns too many unrelevant results.
Perhaps the tool indexes too many data. Not sure it is a good idea to index the ``description`` field. Or at least it should have a much lower weight than ``abstract`` (not sure it is really useful to index it) and especially than ``title``.

Exact hits should also be returned first. For instance if I search for "mont de grange", summit "Mont de Grange" (hit: 100%) appears 2nd in the list after "Montsec d'Ares - Cap del Ras"  (hit: much lower than 100%). The following results are weird too (perhaps their descriptions match the search??)
<img width="736" alt="capture d ecran 2016-07-23 a 17 23 26" src="https://cloud.githubusercontent.com/assets/1192331/17078704/4566a4fe-50fa-11e6-87c7-cc287c9e1322.png">

**Comment by asaunier** [comment]
Another weird thing: if I search for a silly string, the search engine almost always find something!!

<img width="617" alt="capture d ecran 2016-07-23 a 17 27 20" src="https://cloud.githubusercontent.com/assets/1192331/17078735/fd93dcd6-50fa-11e6-8119-67f53b1d1c03.png">

**Comment by ginold** [comment]
I remember I already have reported the problem with writing whatever I want and that it always returned a result. @tsauerwein seemed to tell there was a reason for that.

**Comment by asaunier** [comment]
> I remember I already have reported the problem with writing whatever I want and that it always returned a result. @tsauerwein seemed to tell there was a reason for that.

What the use of listing results with no connection (?) with the query string?

In addition it prevents from displaying your "create a WP/route/..." button since it only appears when there is no result. Anyway the latter behaviour is probably incorrect: one may want to create a WP/route if no suggested result actually match his/her searching...

**Comment by tsauerwein** [comment]
Transferred from https://github.com/c2corg/v6_ui/issues/493#issue-165599832:

> When creating an outing, the tool to associate other members does not find some members: it's OK for "Bruno Besson", "Frédéric Bunoz", but it does not find "LaurentB2", "Pierre P",.... And there is no more "Plus de résultats" button to see more results.

**Comment by stef74** [comment]
On article if you search "source petzl" you have too many result (731) Could you investiguate

**Comment by tsauerwein** [comment]
@stef74 Your example is related to the advanced search (the simple search for "source petzl" reports a total of [25 results](https://api.demov6.camptocamp.org/search?q=source%20petzl&t=c&pl=fr))? In that case I would like to handle it in https://github.com/c2corg/v6_api/issues/397.

Also, I am closing this issue. If there are more problems, a new one can be opened.
