### ISSUE TITLE
Waypoint model: wrong type for "custodianship"

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#207]
WP attribute is currently defined as a boolean:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L142

The specs on google docs say it is an enum attribute (but single selected value) whose values are:
>   oui - fermé hors gardiennage
  oui - ouvert hors gardiennage
  clé à récupérer
  non gardienné

**Comment by ginold** [comment]
I can't find those values in attributes.py, should I create it, use a <select> tag with those explicit <option> values  or is it somewhere else?

**Comment by asaunier** [comment]
Yep, we need to create the values (in english - can be simplified) in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py 
Then the enum must be added in https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/enums.py and finally used in https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L142
