### ISSUE TITLE
Return areas in order

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#210]
The API does not return document['areas'] in the order we want - for now they are returned randomly for different documents.
It would be nice if it always returned in this order : 
- range
- admin limits
- country

**Comment by asaunier** [comment]
Seems that now the areas are always returned using the country > admin > range order, which is fine. Closing.

**Comment by tsauerwein** [comment]
> Seems that now the areas are always returned using the country > admin > range order, which is fine. Closing.

I didn't do anything in regards to that.

**Comment by asaunier** [comment]
OK, at least the order seems OK in the UI, perhaps something has been done in the UI to sort the areas.
