### ISSUE TITLE
Missing attributes for routes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#216]
See https://docs.google.com/spreadsheets/d/1p7-RakklDot9gFnciEGox75833zU0ZuC5pRAoLZKziY/edit#gid=1418510514
- [ ] "Temps de parcours des difficultés"

**Comment by tsauerwein** [comment]
This field did not exist when I created the model. Are there more fields, also in other models, that have been added or changed? It is a bit difficult to track changes in these huge spreadsheets...

**Comment by asaunier** [comment]
@fbunoz Could you check all attributes are actually listed in https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py please?

**Comment by asaunier** [comment]
Still no answer 6 months later => closing.
