### ISSUE TITLE
Quality of migrated documents

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#220]
- [x] All migrated documents should have a quality value = "correct" (3rd level in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L610-L616).
- [ ] Nice to have: set quality to "medium" (2rd level) if "[ebauche]" or "[ébauche]" or "(ébauche)" is detected in the document title: http://www.camptocamp.org/routes/list/srnam/ebauche/orderby/rnam/order/asc
- [ ] Nice to have 2: remove this tag from title if detected.

**Comment by stef74** [comment]
@asaunier propose to close ... nice to have will be manual task

**Comment by asaunier** [comment]
OK, closing then
