### ISSUE TITLE
Handle null geometry

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#226]
When updating a route with ``geometry: null``, the API says:
> {"description": "\"None\" is not a mapping type: Does not implement dict-like functionality.", "name": "document.geometry", "location": "body"}

We should support null geometry. Or maybe require that the associated WP geoms are provided as ``route['geometry']['geom']``?

**Comment by tsauerwein** [comment]
This is related to https://github.com/c2corg/v6_api/issues/55
