### ISSUE TITLE
Matress/heating/... data for huts are not saved correctly

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#229]
Starting from a v5-migrated hut with no mat(t)ress/blanket/gas/heating data, I have set matress=true, blanket=false and kept gas=null heating=null. The JSON request looks like:
```
...
gas_unstaffed: null
heating_unstaffed: null
blanket_unstaffed: false
matress_unstaffed: true
```

The PUT request succeeds but when I GET the hut again is see in the JSON response that:
```
gas_unstaffed: true,
heating_unstaffed: true,
blanket_unstaffed: false,
matress_unstaffed: true,
```
=> gas and heating a set to true (yes) instead of null (no info)

If I edit the hut again and set blanket and gas to "no info", the new PUT request is:
```
heating_unstaffed: true
matress_unstaffed: true
```
(gas_unstaffed and blanket_unstaffed are not passed to the API, not even as null).

This time the GET response is correct:
```
matress_unstaffed: true,
heating_unstaffed: true,
blanket_unstaffed: null,
gas_unstaffed: null,
```

It seems that the API behaves differently depending if a scalar attribute is set to "null" (=> evaluated to true!) or not passed at all. Could it be related to https://github.com/c2corg/v6_api/issues/55 as well?

**Comment by tsauerwein** [comment]
Thanks for the good report, I will have to investigate where things are going wrong.

**Comment by asaunier** [comment]
Do you agree that a ``null`` value in the JSON request should be the same as "not provided"? ie. it's not a UI problem, only an API issue, right?

**Comment by tsauerwein** [comment]
Yes, this should be the same. It is an API issue.

**Comment by tsauerwein** [comment]
I added a test-case to reproduce the problem but it works as expected:
https://github.com/c2corg/v6_api/commit/04ffc3fa6af37a2166a16bbf3614fdd50c81db78

I can still test on the real database.
