### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#243]
I find that there is an issue with what the api returns as results : 
I can literally type anything similar to " paoihn;'a[ioHYB$80273" and there are always results found and returned! But it's very hard to find the exact document when typing its entire name, for example when i'm on the list page and try to find the ones i already see.

I also have the feeling that I rarely get the same result when typing the exact same query, like 1 time out of 3 it is the same. 

For example typing "beau comme un r" gives me some results without routes, then adding continuing with "beau comme un re" gives me plenty of routes, "beau comme un rev" with routes, but deleting "v" -> back to "beau comme un re" gives results with routes. As if i were always one letter behind or something. 
Maybe it's a problem with typehead, I don't know. Just saying.

"1578940" gives nothing, "1578940a';dwj'piw" lots of results :open_mouth: 
I'm working on the case when there are no results and it's very difficult to find a query that doesn't return anything :no_good:

**Comment by tsauerwein** [comment]
> I find that there is an issue with what the api returns as results :
> I can literally type anything similar to " paoihn;'a[ioHYB$80273" and there are always results found and returned! 

ElasticSearch is using fuzzy [partial-matching](https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html) so it might search for documents containg "pao" or "io".

> But it's very hard to find the exact document when typing its entire name, for example when i'm on the list page and try to find the ones i already see.

Can you give examples?

> 
> I also have the feeling that I rarely get the same result when typing the exact same query, like 1 time out of 3 it is the same.

If you experience this the next time, can you directly check the API response to see if it's a Typeahead issue?
> 
> For example typing "beau comme un r" gives me some results without routes, then adding continuing with "beau comme un re" gives me plenty of routes, "beau comme un rev" with routes, but deleting "v" -> back to "beau comme un re" gives results with routes. As if i were always one letter behind or something.

Interesting, for me it only finds outings. I will have to investigate.

> Maybe it's a problem with typehead, I don't know. Just saying.
> 
> "1578940" gives nothing, "1578940a';dwj'piw" lots of results

If you are searching for "1578940" the search is assuming a document id, and directly checks if there is a document with this id. "1578940a';dwj'piw" triggers fuzzy partial-matching.

**Comment by ginold** [comment]
> Can you give examples?
Well now it seems to work a little bit better, but it still happens to type the word and to not find the document, but after deleting a letter it does. It happened to me with the route "Pic de Roche Motte : boucle sud nord". I typed "boucle sud nord" -> nothing then "boucle sud no" and yep.

Now i notice that I just typed "versant se depuis puy-st-andre" instead of (Versant SE depuis Puy-st-André) and it didn't highlight, because it's case- and stress-sensitve (à, é != a, e), but that seems like my job to fix this :P 

> If you are searching for "1578940" the search is assuming a document id
is there any good reason to let it look for document id ? I don't feel like the users are going to look up by document id and it might limit unwanted results.

**Comment by tsauerwein** [comment]
> is there any good reason to let it look for document id ? I don't feel like the users are going to look up by document id and it might limit unwanted results.

This was actually an explicit request. For example if you want to associate a document and know the document id (e.g. it is faster to copy&paste the id instead of searching for a document by name).

**Comment by ginold** [comment]
that would in fact be a thing if not the fact that the document_ids are not displayed anywhere in the UI. So are they supposed to look in the console or we do have to put it somewhere in the ui?

**Comment by tsauerwein** [comment]
I think it is more a feature for advanced users. The document id is shown in the URL.

**Comment by asaunier** [comment]
There was already a similar issue https://github.com/c2corg/v6_api/issues/206 Perhaps we should close one.

I agree that the simple search generally returns too many results not that relevant because too far from the searched keyword. I have also observed many times that the types of returned documents are not consistent: sometimes only waypoints, sometimes waypoints+routes (for the same searched keyword).

In addition the performances are not really good.

**Comment by tsauerwein** [comment]
> There was already a similar issue #206 Perhaps we should close one.

I listed the failing examples from this ticket in #206.

> I have also observed many times that the types of returned documents are not consistent: sometimes only waypoints, sometimes waypoints+routes (for the same searched keyword).

This still sounds like a known bug in Typeahead. This should be fixed with @ginold's pr. If not check the xhr request to see if it is an API or Typeahead problem.

> In addition the performances are not really good.

The demo server is not the strongest. But I also have some ideas to optimize the query.
