### ISSUE TITLE
Make sure ES is updated when user name changes

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#244]
Changing the user-name does not create an entry in the history table, so the syncer script will not know that something has changed. We could add a column `last_updated` to `User`.

**Comment by asaunier** [comment]
Do we really need to update the indexing of documents created/updated by a user when the user name changes?

**Comment by tsauerwein** [comment]
In the search you should be able to search for the user-name, right? So, if the user-name is changed, the corresponding profile document in ES has to be updated.

**Comment by asaunier** [comment]
Indeed. I thought you meant we had to reindex all documents updated by the user, not only his profile.
