### ISSUE TITLE
Jobs and multiple processes / instances

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#256]
Non activated accounts and expired tokens are purged by an scheduler started by the WSGI application.
This is fine as long as only one instance/process of the application is run.

If it is not the case, the feature should be extracted out in an independant standalone application.
See #253.

**Comment by tsauerwein** [comment]
Wsgi applications are usually run with multiple processes, so this is definitely the case.

**Comment by tsauerwein** [comment]
Can this ticket be closed? Done in https://github.com/c2corg/v6_api/pull/253/commits/7a14e7b42aa38406d30d1cbe2b90c78c476998ec, right?
