### ISSUE TITLE
Return document type

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#257]
Would it be possible to return for each document its document type?
It could be set like for example `route_doc : {'doctype' : 'routes'}`, `wp_doc : {'doctype' : 'waypoints'}` etc.

I need this info more and more and I cannot base myself on the doc_id, I have to check if the doc has waypoint_type (= it's a wp) or route_type (=it's a route) and so on, it's a bit time and code-lines consuming.

I don't need it's singular form, we nearly exclusively use the plural.

**Comment by tsauerwein** [comment]
For which web-service(s)?

**Comment by asaunier** [comment]
I have indeed noticed that you had to add the document type directly in the mako templates for your PR https://github.com/c2corg/v6_ui/pull/318, for instance at https://github.com/c2corg/v6_ui/blob/add-outing-to-route-editing/c2corg_ui/templates/outing/view.html#L15

which looks weird => the info, if needed, should already be provided by the view.

**Comment by ginold** [comment]
that is only one example, but i need this info everywhere now, to differentiate templates or where to put it in the object, fox example associations[routes/waypoints/outings?]

**Comment by tsauerwein** [comment]
Every-time you make a request to the API, you know what document type you are getting. E.g. if you make a request `GET /waypoints`, you know that you are getting waypoints. Or if you are doing a search, you get `{'waypoints': [..], 'routes': [..]}`. So you shouldn't have to probe for `waypoint_type` or `route_type`.

 But if it helps we can include a `type` field, which is one of these values:
https://github.com/c2corg/v6_common/blob/master/c2corg_common/document_types.py

**Comment by ginold** [comment]
yeah it would help greatly, this would be welcome :)
