### ISSUE TITLE
Missing geometry for climbing_indoor waypoints in list view?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#259]
Double-checking with the other "climbing_indoor" WP would be needed but I at least observe that no geometry attribute is provided for WP 733992 when listing WP in the demo instance with ``/waypoints?pl=fr``:
> {
available_langs: [
"fr",
"en"
],
document_id: 733992,
areas: [
{
available_langs: null,
document_id: 14271,
area_type: "country",
locales: [
{
lang: "fr",
version: 1,
title: "Allemagne"
}
],
protected: false,
version: 1
}
],
locales: [
{
summary: null,
lang: "fr",
version: 1,
title: "Boulderhaus"
}
],
protected: false,
version: 1,
waypoint_type: "climbing_indoor"
},

whereas the ``geometry`` attribute is indeed available when GETting the document itself with ``waypoints/733992?l=fr``:
> geometry: {
version: 1,
geom: "{"coordinates": [966163.4565760338, 6340678.802009442], "type": "Point"}"
},

**Comment by tsauerwein** [comment]
Indeed, this is how it configured in [c2corg_common/fields_waypoint.py](https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py#L98-L100).

**Comment by asaunier** [comment]
Thanks for the tip. I think it's an error in the WP config, climbing_indoor geometries should be returned (unlike elevation that is not relevant for an indoor gym). Fixed with #260
