### ISSUE TITLE
3D/4D geometries seem not supported

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#262]
When sending a 4D route geometry (with elevation + timestamp for each point) like

```
{"type":"MultiLineString","coordinates":[[[849344.3376596108,5800875.452693369,1691,1460269443],[849385.5258712043,5800824.053639301,1679,1460270468]
```

the API refuses the document arguing that "Invalid geometry"
https://github.com/c2corg/v6_api/blob/947c2284557a31564e121ed0082a348f882eaad1/c2corg_api/ext/colander_ext.py#L76-L81

OK with the same geometry passed in 2D with only lat/lon:

```
{"type":"MultiLineString","coordinates":[[[849344.3376596108,5800875.452693369],[849385.5258712043,5800824.053639301]
```

No idea if this works with the elevation but no timestamp.

Supporting elevation and timestamp would be useful for displaying a profile of the route/outing as well as a "time profile". See in v5: http://www.camptocamp.org/outings/745686/fr/blanc-de-moming-en-boucle-mountet-glacier-de-moming-par-l-arete-sw#elevation_profile_container

By the way timestamps in geometries (for outings) would be useful in the future for instance to automatically geolocalize the pictures associated to the outing.

**Comment by tsauerwein** [comment]
Yes, not (yet) supported, see https://github.com/c2corg/v6_api/issues/181.

**Comment by asaunier** [comment]
> Yes, not (yet) supported, see #181.

OK, good to know: the 3D is lost during the migration as well.

**Comment by fjacon** [comment]
@asaunier @tsauerwein 
Should we close this ?
Or create a new one about migration because 3D is lost ?

**Comment by asaunier** [comment]
Why closing the issue? We still have the problem:
* elevation/time dimensions of the outing geometries are lost during the migration (I think route geometries are 2D in v5 - a bit a pity!?)
* 3D/4D tracks (eg. provided by submitting a GPX file) are not supported by the API (because of the geometry cols definition in the DB?)

By the way, the map editing tool provided in v6 is 2D. No elevations are detected when drawing a track on the map. An elevation service would be needed. (not in the specs)

**Comment by tsauerwein** [comment]
@fjacon What is the priority for this?

**Comment by asaunier** [comment]
Don't we need this before 6.0? If those data are not migrated for 6.0, they will be lost, won't they?

**Comment by tsauerwein** [comment]
> If those data are not migrated for 6.0, they will be lost, won't they?

Indeed.
