### ISSUE TITLE
Allow only three level hierarchy associations

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#272]
See https://github.com/c2corg/v6_ui/issues/348#issuecomment-218116248

And also check that there are no associations between siblings. E.g if there is a hierarchy:

```
A - B
  - C
```

There should be no association between B and C.

**Comment by fjacon** [comment]
@tsauerwein I think according to this : https://github.com/c2corg/v6_ui/issues/348#issuecomment-235562746 
this ticket can be closed.

**Comment by tsauerwein** [comment]
Not sure. If you open the page for a waypoint, you see the routes of the waypoint itself and also of the child and grand-child waypoints. But not the routes of the grand-grand-waypoints.

So, you still would have to restrict three level hierarchies.

**Comment by asaunier** [comment]
> If you open the page for a waypoint, you see the routes of the waypoint itself and also of the child and grand-child waypoints. But not the routes of the grand-grand-waypoints.

What do you call "grand-grand-waypoints"? grand-grand-children waypoints?

If yes, perhaps it's not a big deal!?
We could allow any number of hierarchy levels but only show routes associated to the current WP, its child-waypoints and grand-child-waypoints?!
This would avoid having too many routes shown for a given WP.

**Comment by tsauerwein** [comment]
Yes, that would also work.

**Comment by asaunier** [comment]
I think that's a good solution because it doesn't make the code even more complicated. And we don't add complicated usage rules (eg. "no more than 3 levels of hierarchy").

@stef74 OK for you?
@fjacon If no one objects, I think you can close the issue.

**Comment by asaunier** [comment]
Do we still have something to do about this issue? Can it be closed?

**Comment by stef74** [comment]
Ok for me to have only direct relation
