### ISSUE TITLE
Create/delete associations when creating/updating a document

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#274]
The way creating/updating a document is done in the UI requires that associations can be created/deleted at the same time. The create/update web-service must be adapted so that associations can be passed together with the document.

**Comment by ginold** [comment]
So the UI web-service should return `document : { blabla : blabla, associations : [...] }` and the API will handle the rest?

**Comment by tsauerwein** [comment]
@ginold Yes, I added some details in this PR: https://github.com/c2corg/v6_api/pull/293
