### ISSUE TITLE
Searching users crash

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#286]
at least on the demo instance.

When typing a user name in the user-associating tool in the outing editing interface, one gets 500-error results from the API, the logs saying that

> [Sat May 14 13:57:18.016505 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189] mod_wsgi (pid=25547): Exception occurred processing WSGI script '/var/www/vhosts/c2corgv6-api/private/v6_api/apache/app-c2corg_api.wsgi'.
[Sat May 14 13:57:18.016900 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189] Traceback (most recent call last):
[Sat May 14 13:57:18.017269 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 223, in __call__
[Sat May 14 13:57:18.017298 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = self.invoke_subrequest(request, use_tweens=True)
[Sat May 14 13:57:18.017367 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 198, in invoke_subrequest
[Sat May 14 13:57:18.017389 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = handle_request(request)
[Sat May 14 13:57:18.017487 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/__init__.py", line 46, in tween
[Sat May 14 13:57:18.017512 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     return handler(request)
[Sat May 14 13:57:18.017590 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 48, in excview_tween
[Sat May 14 13:57:18.017616 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     request_iface=request_iface.combined
[Sat May 14 13:57:18.017700 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 541, in _call_view
[Sat May 14 13:57:18.017721 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = view_callable(context, request)
[Sat May 14 13:57:18.017818 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
[Sat May 14 13:57:18.017842 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     result = view(context, request)
[Sat May 14 13:57:18.017907 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 20, in excview_tween
[Sat May 14 13:57:18.017928 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = handler(request)
[Sat May 14 13:57:18.017998 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
[Sat May 14 13:57:18.018030 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     reraise(*exc_info)
[Sat May 14 13:57:18.018105 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
[Sat May 14 13:57:18.018128 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     raise value
[Sat May 14 13:57:18.018179 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
[Sat May 14 13:57:18.018201 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = handler(request)
[Sat May 14 13:57:18.018258 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 145, in handle_request
[Sat May 14 13:57:18.018282 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     view_name
[Sat May 14 13:57:18.018341 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 541, in _call_view
[Sat May 14 13:57:18.018365 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = view_callable(context, request)
[Sat May 14 13:57:18.018452 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 602, in __call__
[Sat May 14 13:57:18.018478 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     return view(context, request)
[Sat May 14 13:57:18.018531 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 328, in attr_view
[Sat May 14 13:57:18.018555 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     return view(context, request)
[Sat May 14 13:57:18.018613 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
[Sat May 14 13:57:18.018637 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     return view(context, request)
[Sat May 14 13:57:18.018689 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 353, in rendered_view
[Sat May 14 13:57:18.018713 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     result = view(context, request)
[Sat May 14 13:57:18.018762 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
[Sat May 14 13:57:18.018786 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = view(request)
[Sat May 14 13:57:18.018869 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/cornice/service.py", line 571, in wrapper
[Sat May 14 13:57:18.018904 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     response = view_()
[Sat May 14 13:57:18.019031 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/views/search.py", line 102, in get
[Sat May 14 13:57:18.019060 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     return search.search_for_types(search_types, search_term, limit, lang)
[Sat May 14 13:57:18.019148 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/search/search.py", line 22, in search_for_types
[Sat May 14 13:57:18.019172 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     search_types, search_term, limit)
[Sat May 14 13:57:18.019233 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/search/search.py", line 64, in do_multi_search_for_types
[Sat May 14 13:57:18.019257 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     responses = multi_search.execute()
[Sat May 14 13:57:18.019339 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch_dsl/search.py", line 665, in execute
[Sat May 14 13:57:18.019365 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     **self._params
[Sat May 14 13:57:18.019465 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
[Sat May 14 13:57:18.019490 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     return func(*args, params=params, **kwargs)
[Sat May 14 13:57:18.019573 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]   File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 814, in msearch
[Sat May 14 13:57:18.019598 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189]     raise ValueError("Empty value passed for a required argument 'body'.")
[Sat May 14 13:57:18.019706 2016] [wsgi:error] [pid 25547] [remote 10.27.71.4:20189] ValueError: Empty value passed for a required argument 'body'.

**Comment by tsauerwein** [comment]
Could it be that you were not logged-in when doing the search?

**Comment by asaunier** [comment]
> Could it be that you were not logged-in when doing the search?

I had this problem while trying to associate users in the outing editing interface => I was logged in.

**Comment by tsauerwein** [comment]
And what about:

> Or is the authentication header not sent for the search request? (search results for users are only included when authenticated)

**Comment by asaunier** [comment]
Indeed I see no authentication header sent with the search request.
Should it return a 401 error instead of a 500 error in that case?

**Comment by tsauerwein** [comment]
With https://github.com/c2corg/v6_api/issues/288 the return code is 200. When you are not authenticated and are searching for all document types, you get the results excluding the users. So it would be the same behavior.

If you are not authenticated and only searching for users, we might consider returning 401. Or you could check if `users` is not given in the response.
