### ISSUE TITLE
ORM query object from REST url for filter

### ISSUE THREAD

**Issue by gberaudo** [c2corg/v6_api#29]
The API will have to handle the transformation of REST urls like
`http://www.camptocamp.org/outings/list/summits/639674-41487-40127/orderby/act/order/asc` to
SQLAlchemy Query objects.
In v5, this is done by parsing the URL and delagating to a collection of helper functions like found at `https://github.com/c2corg/camptocamp.org/blob/master/lib/model/doctrine/generated/BaseDocument.class.php#L214`.
I have not found ready to use libraries for handling this.

**Comment by asaunier** [comment]
In v5, the criteria are handled in the Document model (if I got it right). Should we do the same in v6? Dispatch in the various Waypoint/Route/... models depending on the doc type? Handle them in the views?
