### ISSUE TITLE
Inconsistencies in associated documents response

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#296]
I have noticed a few inconsistencies in the ``associations`` data in the document attributes returned by the API.

For instance the ``recent_outings`` attribute contains:
* a ``total`` attribute containing the total number of outings associated to the current document
* an ``outings`` attribute containing the 10 most recent outings associated to the current document
like this
```
recent_outings: {
  total: 123.
  outings: [ ... ]
}
```

=> What about switching to this:
```
outings: {
  total: 123.
  recent_outings: [ ... ]
}
```
?

Ditto for routes. As for now we have:
```
all_routes: {
  total: 123,
  routes: [ ... ]
}
``` 
what about:
```
routes: {
  total: 123,
  last_routes: [ ... ]
}
```
?

This would be a bit less confusing I think.

**Comment by asaunier** [comment]
On the other hand I notice that for an outing document, the ``associations`` attribute contains a ``routes`` attributes which is a list, not a dict (having different names according to the type makes sense here).

**Comment by tsauerwein** [comment]
> On the other hand I notice that for an outing document, the associations attribute contains a routes attributes which is a list, not a dict (having different names according to the type makes sense here).

Yes, that was the motivation to use a different name. About outings: `recent_outings` makes it clear that you are not getting all outings.

**Comment by asaunier** [comment]
You may be right for outings. What about ``all_routes``? This name seems to mean you get all the routes, doesn't it?

**Comment by tsauerwein** [comment]
That is indeed a bit confusing. I have chosen "all_..." to express that you are also getting the routes of child waypoints.

**Comment by asaunier** [comment]
OK, let's say it's good like this.
