### ISSUE TITLE
Search for routes/outings given an associated document

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#297]
For instance ``routes?w=37355``

As already available for outings, that can be filtered on "w" (waypoint id) or "r" (route id).

**It should be possible to search:**

- a route given a waypoint id
- an outing given a waypoint id, an user id and a route id.

When searching with a waypoint id, children of the waypoint should also be considered (see https://github.com/c2corg/v6_api/issues/283).

**Comment by tsauerwein** [comment]
> As already available for outings, that can be filtered on "w" (waypoint id) or "r" (route id).

Note that these filters can currently not be combined with other filter criteria. The queries to get the documents are directly run on the database and not on ElasticSearch.

If we add support to search for routes associated to a waypoint, I would propose to do this search in ES. We could then do the same for outings.

**Comment by asaunier** [comment]
> If we add support to search for routes associated to a waypoint, I would propose to do this search in ES. We could then do the same for outings.

Yes, this would be helpful to be able to make some additional filtering on the related outings/routes (for instance to get the routes of a given activity for some waypoint). In addition it would be more intuitive for users that when showing the list of routes of a waypoint, something actually happens when changing the criterias available in the page :)
