### ISSUE TITLE
Creating an outing

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#299]
I cleanall-install-upgrade-upgrade-dev'ed the API but the upgrade #293 where I should be able to send associations along the outing data seems not to work in my case. I still get the errors 
```
- outing is missing
- route_id is missing
- user_ids is missing
```

BTW still waiting for #266 to be solved as well.

**Comment by tsauerwein** [comment]
That doesn't sound like you are using the latest version. Are you sure you fetched the latest version form GitHub?

**Comment by ginold** [comment]
I hope so, but I'll retry and give you a sign.

**Comment by ginold** [comment]
Indeed I forgot to git fetch first :p
however the #266 issue is still valid.
