### ISSUE TITLE
Getting a document "list attributes"?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#300]
I am making changes in the UI so that the AngularJS card directive and partials (used for the advanced search) are used also for:
* listing associated documents as cards (instead of Mako) => done at https://github.com/c2corg/v6_ui/pull/328
* adding a new card when a document has just been associated.

For the latter usage I am in troubles because the data returned by the association tool (based upon the simple search service) does not return all the attributes needed for the "listing" cards (in addition the "externs" types are different).

2 options:
* when creating the newly associated document card, I make a request to the API to get the document attributes. I could make a standard document request but it's a bit overkill because I only need the "listing" attributes => is it possible to make a "list" request to the API for a given document id. For instance ``waypoints?w=1234``?
* we use consistent data structure for the listing and simple-search request, with consistent "externs" types.

What do you think?

**Comment by tsauerwein** [comment]
If I get you right, the actual problem is that the simple search service does not return all required attributes?

The simple search service is used in different places, for the actual search at the top of the page and to find new associations. Either we use the same schema for all these uses, or we let the simple search service return different attributes depending on the use. E.g. `/search?q=...&l=1` could return all attributes required for listings.

See also https://github.com/c2corg/v6_api/issues/192

**Comment by asaunier** [comment]
> See also #192

That's indeed the same issue (duplicate? Should I move this one as a comment of #192 ?).

> If I get you right, the actual problem is that the simple search service does not return all required attributes?

As for now in https://github.com/c2corg/v6_ui/pull/328 I have been able to create cards when associating new documents with the simpleSearch/association tool and had no error. Maybe that's because the cards are currently quite simple(?). Maybe we'll have troubles later when adding more info to the cards? So it seems the problem is not that urgent.

Anyway it is probably a good thing that simple search and advanced search (=listing) responses are consistent (and share the same types in the UI?).

 > or we let the simple search service return different attributes depending on the use. E.g. /search?q=...&l=1 could return all attributes required for listings.

Maybe. But I wonder if it is really a good idea to add special cases etc.

**Comment by asaunier** [comment]
> I have been able to create cards when associating new documents with the simpleSearch/association tool and had no error.

Since I rebased c2corg/v6_ui#328 to take into account the merging of https://github.com/c2corg/v6_ui/pull/372 which introduced externs for document types (eg. https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/externs/appx.js#L227-L280), Closure complains for instance because
> ERR! compile /home/alex/Desktop/v6_ui/c2corg_ui/static/js/addassociation.js:108: ERROR - actual parameter 1 of Array.prototype.push does not match formal parameter
ERR! compile found   : {
ERR! compile   documentType: string,
ERR! compile   document_id: number,
ERR! compile   document_type: string,
ERR! compile   label: string,
ERR! compile   locales: (Array<appx.SimpleSearchDocumentLocale>|null)
ERR! compile }
ERR! compile required: (appx.Waypoint|undefined)
ERR! compile       this.document_.associations.waypoint_children.push(doc);

That would really help that the simple search returns the same response than the usual listing requests .

**Comment by asaunier** [comment]
By the way @gberaudo I wonder if we won't have troubles with using such precise externs for document types: since the simple search / listing requests return only a subset of the documents attributes, won't we have problems since the typedefs define the whole list of attributes? Should the "omitted" attributes by marked as optional?

**Comment by gberaudo** [comment]
No, that should not be a problem.
