### ISSUE TITLE
Associations: routes vs all_routes & waypoints vs waypoint_children/parents

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#301]
I am struggling with the associations in the UI https://github.com/c2corg/v6_ui/pull/328

From my perspective the newly added distinctions:
* routes / all_routes
* waypoints / waypoint_children / waypoint_parents
add a bunch of complexity and confusion!

Because in the code (directives/partials/mako) we have to make complex detections to figure out which one to use. And it's confusing to have sometimes "routes", sometimes "all_routes" (in addition the name "all_routes" is really not self explicit since it's actually a subset of associated routes).

I know having dozens (or hundreds) of associated routes is a problem and may cause slow requests but:
* couldn't we say it's the responsibility of the client not to have waypoints with hundreds of routes?
* or if we prefer to apply a limit anyway, couldn't we always have the same associations object for route, whatever the type of the current document ? For instance:
```
associations: {
  routes: {
    total: 123,
    documents: []
  }
}
```

Concerning waypoints, since it's only possible to associate a waypoint to another as a "child waypoint", couldn't we merge ``waypoints`` and ``waypoint_children`` and keep only ``waypoints``? This way when associating a waypoint to a route or a waypoint, the newly associated waypoint will be added to the ``waypoints`` list in both cases.
``waypoint_parents`` could be kept as is (and is not used by the association creation tools anyway).

**Comment by tsauerwein** [comment]
> couldn't we say it's the responsibility of the client not to have waypoints with hundreds of routes?

Yes, let's simply move a route from the Verdon to the Normandy because there are only a few?!

> or if we prefer to apply a limit anyway, couldn't we always have the same associations object for route, whatever the type of the current document? For instance:
> 
> associations: {
>   routes: {
>     total: 123,
>     documents: []
>   }
> }

There is a difference between getting a document for editing and viewing. If you get a document for editing all associations are returned in the same format. For viewing, there are two additional types (`recent_outings` and `all_routes` (I am open to change that name)) that contain aggregated and transitive associations. And only these two use a different schema to account for the fact that not all can be returned at once.


> 
> Concerning waypoints, since it's only possible to associate a waypoint to another as a "child waypoint", 

Are you talking about associating a waypoint from the view or from the edit page?

> couldn't we merge waypoints and waypoint_children and keep only waypoints? 

You mean `waypoint_parents` and `waypoint_children`? Note that this is likely going to change because of https://github.com/c2corg/v6_api/issues/132.

**Comment by asaunier** [comment]
> There is a difference between getting a document for editing and viewing.

So you mean that when editing a WP with a bunch of associated routes, the viewing will get a limit number of routes whereas the editing will get all of them? If yes, is it really consistent?

As I said it's a bit a nightmare to have to handle those special cases (``routes`` vs ``all_routes``, ditto with waypoints) in the cards depending on the current document types, and (?) depending on the viewing/editing mode. I think we need something simpler.

In addition I think it is confusing for users not to see all associated routes in a waypoint page. When associating a route, how can you know that the route is not already associated (but simply not displayed)? You wait for the association tool to report an error because the route is already associated? That doesn't sound very user friendly :)

I admit having a bunch of associated routes causes performances issues + usability issues (lots of scrolling to do to browse among the cards).
But I more and more feel like showing only a subset of cards causes many other problems. 

> Are you talking about associating a waypoint from the view or from the edit page?

Both.
Whereas one is associating a waypoint in editing or viewing mode, it will be added to ``waypoints`` or ``waypoint_children``.

It would be cool if we could simply add it to ``waypoints``, whereas the current document is a waypoint or a route.

**Comment by tsauerwein** [comment]
> So you mean that when editing a WP with a bunch of associated routes, the viewing will get a limit number of routes whereas the editing will get all of them? If yes, is it really consistent?

No. When editing you don't get `all_routes`, you only get the directly associated routes.

> In addition I think it is confusing for users not to see all associated routes in a waypoint page. When associating a route, how can you know that the route is not already associated (but simply not displayed)? You wait for the association tool to report an error because the route is already associated? That doesn't sound very user friendly :)

Do you think it helps the user if they see 500 associated routes? Do you think they will scan this list to find out if a route is already associated? Do you call that user friendly? ;)

**Comment by asaunier** [comment]
> No. When editing you don't get all_routes, you only get the directly associated routes.

Mmm
What about always returning the directly associated routes in ``routes`` (with no restriction) and provide the child-waypoint-associated routes in a separated object (with a limit) named for instance ``children_routes``?

This way we could:
* display child-waypoint-associated routes in a separated block (by the way for those routes I guess it doesn't make sense to provide a "delete association" button since there is no direct association). A bit like the "recent_outings" block in the waypoint pages.
* be consistent among the viewing and editing modes: the same list of routes are shown as "directly associated routes" in both pages.
* use consistent object names in the API response (which would greatly simplify my task about the associated documents cards).

**Comment by asaunier** [comment]
@tsauerwein and I just had an hangout to discuss this issue. Here is what we have decided:
* ``waypoint_childent`` will be renamed to ``waypoints``
* in a waypoint page. it is not possible to associate a new waypoint as "parent", but always as "child" (as in v5 I think) [NB: if really needed we would have to display a dedicated instance of the association tool]
 * ``waypoint_parents`` cannot be unassociated as well => the unassociate button will be removed
* concerning associated routes in a waypoint page:
 * since it's a problem listing hundreds of associated-routes cards, a limit is applied ("master" already behaves like this) to show a subset (+ a show more button redirecting to the advanced search page)
 * as already in master, the list of associated routes will remain stored in a single attribute. It would stay named "all_routes" (a bit confusing since it might be a subset - but listing routes from all-associated WP as well) since we have no better short name.
 * @tsauerwein will make sure this list shows the directly-associated routes first and then child-waypoints-associated routes.
 * since only a subset of routes might be shown, it doesn't make sense adding or removing route-associations. Ditto in the editing mode.

**Comment by tsauerwein** [comment]
> waypoint_childent will be renamed to waypoints

Shouldn't `waypoint_parents` be renamed to `waypoints`? For all other [association types](https://github.com/c2corg/v6_common/blob/master/c2corg_common/associations.py) waypoint takes the role of the parent.

**Comment by asaunier** [comment]
> Shouldn't waypoint_parents be renamed to waypoints? For all other association types waypoint takes the role of the parent.

Perhaps. On the other hand renaming "waypoint_children" to "waypoints" would have simplified the code of UI associations code (associated waypoints to whatever other document type - waypoint, route, image etc. would have always been listed in ``waypoints``).
We can merge your PR #305 as is and I will see if in can deal with it on the UI side.

**Comment by tsauerwein** [comment]
> On the other hand renaming "waypoint_children" to "waypoints" would have simplified the code of UI associations code (associated waypoints to whatever other document type - waypoint, route, image etc. would have always been listed in waypoints).

I think renaming `waypoint_parents` to `waypoints` simplifies. For example if you have a route: For the associations between waypoint and route, waypoint takes the parent role and route the child route. So all associated waypoints in `waypoints` are *parents* of the route. Now if you have a waypoint, it would make sense to have all parents in `waypoints` to have that simplification.
