### ISSUE TITLE
Is user forum_name used by elastic search

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_api#310]
I see that we make for an elastic search update when forum_username is changed, but forum_username do not seems to be used by elastic seach.

https://github.com/c2corg/v6_api/blob/a55bc4991b8e99fd9dd27c3b4a68c0a12067cb59/c2corg_api/views/user.py#L461

@gberaudo : can you confirm ?

**Comment by gberaudo** [comment]
@asaunier, @tsauerwein, is the forum_username supposed or planned to be available in searches?

**Comment by asaunier** [comment]
No idea. But I guess that users might also type the "pseudo" when looking for a contributor.

**Comment by tsauerwein** [comment]
Yes, I think it would also make sense to index the forum user name.
