### ISSUE TITLE
Missing search fields

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#311]
I will add here the search fields that proved missing while implementing the UI advanced search (see https://github.com/c2corg/v6_ui/pull/373):
* [x] waypoint prominence "prom" https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L37
* [x] waypoint's ``climbing_outdoor_types`` https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L52
* [x] waypoint's ``climbing_indoor_types`` https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/waypoint.py#L55

Fields that are probably not needed (to be confirmed):
* [x] ``has_phone`` https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/waypoint_mapping.py#L21-L22

**Comment by ginold** [comment]
prominence is available, but only for type summit.

**Comment by tsauerwein** [comment]
What fields are you listing here? The fields that are indexed in ElasticSearch?

**Comment by asaunier** [comment]
Yes, for instance the ones in https://github.com/c2corg/v6_api/blob/master/c2corg_api/search/mappings/waypoint_mapping.py

**Comment by tsauerwein** [comment]
`prominence`, `climbing_outdoor_types` and `climbing_indoor_types` are added in #324.

**Comment by tsauerwein** [comment]
I am closing this issue with https://github.com/c2corg/v6_api/pull/324 being merged. If there are other fields missing, a new issue can be opened.
