### ISSUE TITLE
'durations' field 

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#312]
there is probably an error with the naming: is it `durationS` or `duration`?

API says it's an attribute without s https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L155

Common -> with s https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py#L23

In both cases, the value doesn't seem to be saved.

**Comment by tsauerwein** [comment]
Thanks for noticing, it should `durations`. PR is here: https://github.com/c2corg/v6_api/pull/314
