### ISSUE TITLE
Make it more convenient to search for a rating range

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#313]
See https://github.com/c2corg/v6_ui/issues/368

- when searching for routes with a rating between PD and ED+, the filter would have to be set to `PD-,PD,PD+,...,ED-,ED,ED+`. It should be possible to search with `PD,ED+`. This should also be done for all other *sortable* criteria.

**Waypoint**
   - [x] quality
   - [x] access_time
   - [x] climbing_rating_max/climbing_rating_min
   - [x] paragliding_rating
   - [x] exposition_rating
   - [x] equipment_ratings

**Route**
   - [x] quality
   - [x] durations
   - [x] ski_rating
   - [x] ski_exposition
   - [x] labande_ski_rating
   - [x] labande_global_rating
   - [x] global_rating
   - [x] engagement_rating
   - [x] risk_rating
   - [x] equipment_rating
   - [x] ice_rating
   - [x] mixed_rating
   - [x] exposition_rock_rating
   - [x] rock_free_rating
   - [x] rock_required_rating
   - [x] aid_rating
   - [x] via_ferrata_rating
   - [x] hiking_rating
   - [x] hiking_mtb_exposition
   - [x] snowshoe_rating
   - [x] mtb_up_rating
   - [x] mtb_down_rating

**Outing**
   - [x] quality
   - [x] frequentation_types
   - [ ] ~~awesomeness~~
   - [x] condition_rating
   - [x] snow_quantity
   - [x] snow_quality
   - [x] glacier_rating

- `min_rating` and `max_rating` should be combined into `rating`.

**Waypoint**
   - [x] climbing_rating_max/climbing_rating_min

**Route**
   - [x] elevation_min/elevation_max?

**Outing**
   - [ ] ?

**Comment by tsauerwein** [comment]
@asaunier Could you please double-check if this  are all the attributes that should be searchable with a range? And also the "combinded" attributes (like min/max rating)?

**Comment by asaunier** [comment]
@tsauerwein I have double-checked, that looks good.

For outings, it seems that the "awesomeness" attribute will be removed => no need to take it into account.

**Comment by tsauerwein** [comment]
Is the field `climbing_rating_median` required?

**Comment by asaunier** [comment]
In my opinion no. But it's in the list of searchable fields and people at the association think it is useful. So if possible, yes.
