### ISSUE TITLE
Logout doesn't work (forum)

### ISSUE THREAD

**Issue by celinestern** [c2corg/v6_api#317]
Deconnection doesn't work (for forum). Staying in connect mode.

**Comment by asaunier** [comment]
I cannot reproduce the problem: logging in/out to/from the forum etc. works as expected for me. Perhaps you don't use the right instance of the forum? The forum to test is the one linked in the left menu of the main demo website.

**Comment by asaunier** [comment]
@celinestern Could you tell me if this issue is still valid? Thanks :)

**Comment by celinestern** [comment]
It's working now. I couldn't see this problem anymore.
