### ISSUE TITLE
User document_id

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#321]
Similar issue to the previous I created:

users have a `document_id` normally, whereas for saving an outing the API expects to receive `id` instead of `document_ids `.
Would it be possible to make it more consistent?

**Comment by tsauerwein** [comment]
What you are getting in `associations.users` are [User](https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/user.py) objects, which do not have a `document_id`. I understand that you have to treat user associations differently in the UI, but the API would also have to explicitly add a document id.
