### ISSUE TITLE
Missing advanced search attributes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#332]
(might be updated later)

Routes:
* [ ] document language ("rcult" in the google sheets but "rlang" would make more sense)

Outings:
* [ ] document language ("ocult" in the google sheets but "olang" would make more sense)

**Comment by tsauerwein** [comment]
There are no fields `rcult` or `ocult`. There is only a field `l` which is the same for all document types:
https://github.com/c2corg/v6_api/blob/2965f0c/c2corg_api/search/mapping.py#L40
