### ISSUE TITLE
route fields missing

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#341]
"Temps de parcours des difficultés" is missing, it is defined at line 45 https://docs.google.com/spreadsheets/d/1p7-RakklDot9gFnciEGox75833zU0ZuC5pRAoLZKziY/edit#gid=1418510514

I will add it to the view and name it `duration_difficulties` as in outing.

I will add other fields if I find other.

**Comment by asaunier** [comment]
``difficulties_duration`` would make more sense, I guess, similarly to ``difficulties_height`` https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L49 (by the way the name of the latter attribute is confusing and should rather be ``difficulties_elevation``).

> I will add it to the view and name it duration_difficulties as in outing.

You mean on the UI side? Wouldn't it make more sense to add it on the API side first and only then on the UI side? It is no use adding an attribute to the interface if the UI cannot retrieve/save it via the API.
And honestly I think this attribute (in minutes according to the google sheet!) is not that useful, we already have too many attributes!

**Comment by asaunier** [comment]
> "Temps de parcours des difficultés" is missing

This attribute is given up.
