### ISSUE TITLE
Migration: pb field "Matériel Glacier"

### ISSUE THREAD

**Issue by loicperrin** [c2corg/v6_api#343]
In routes, field "Materiel Glacier" seems to have not been migrated. See for example routes/45547

**Comment by fbunoz** [comment]
The field is correctly migred (we can show it at the edition), but it is not showed in the doc.
It must be showed at the head of the text field "gear", as on the V5. But for now the field "gear" is not managed correctly (it misses all the automatic links to "le contenu du sac: ..." articles (ex : http://www.camptocamp.org/articles/185750/fr/le-contenu-du-sac-alpinisme-neige-glace-mixte-de-f-a-pd)

**Comment by loicperrin** [comment]
> The field is correctly migred (we can show it at the edition), but it is not showed in the doc

In my example (routes/45547) the checkbox is checked in V5, whereas in V6 the field is empty. The value of the field should be "Glacier".
But indeed I have seen other cases where the migration to "Glacier" is OK.

For routes with the checkbox unchecked in V5, it should be migrated to "No" in V6. It seems to be migrated to "null" (see routes/49678 for examples).

**Comment by fbunoz** [comment]
> In my example (routes/45547) the checkbox is checked in V5, whereas in V6 the field is empty. The value of the field should be "Glacier".

On the V5, you have turned to true the "glacier" check box, the 12 june 2016 : http://www.camptocamp.org/routes/diff/45547/fr/7/6

The V6 demo uses an older V5 base.

**Comment by loicperrin** [comment]
Indeed ! OK for migration "checkbox checked V5" -> V6
But not OK for "checkbox unchecked V5" -> "No" V6

**Comment by asaunier** [comment]
> But for now the field "gear" is not managed correctly (it misses all the automatic links to "le contenu du sac: ..." articles (ex : http://www.camptocamp.org/articles/185750/fr/le-contenu-du-sac-alpinisme-neige-glace-mixte-de-f-a-pd)

I am not sure this point has been described/ordered anywhere.

**Comment by fbunoz** [comment]
> OK for migration "checkbox checked V5" -> V6
> But not OK for "checkbox unchecked V5" -> "No" V6

Yes, it was not described correctly on the route fields doc (I added details).
- If the V5 field is "true", then the V6 field must be "matériel de glacier" (the value used for last migrating).
- For any other value (false, null, ...), the V6 field must be "no".
For the last migrating, only few routes has the field at "no", the most have an empty field.

**Comment by asaunier** [comment]
Is this issue still valid?
The text attribute for "gear" is actually migrated and displayed in the document detail view + editing form.
The automatic gear links are indeed not displayed but this is described in another issue, see https://github.com/c2corg/v6_ui/issues/526

No idea whether the part @fbunoz talks about in his comment above is OK or not.

**Comment by fbunoz** [comment]
It is not correct on the demo beta : there is only 105 routes with glacier field at "no", instead of 32000.
All the route must have the field filled to "glacier" or to "no".

**Comment by stef74** [comment]
@asaunier some work identified on SA side ?

**Comment by asaunier** [comment]
no clue

**Comment by stef74** [comment]
@loicperrin @shortoland @fbunoz please test

**Comment by fbunoz** [comment]
It is OK : 33432 routes with 'no', 3366 with 'glacier', and 36798 routes => all route has the 'glacier_gear' field filled.
