### ISSUE TITLE
Incorrectly saved outing date

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#345]
maybe an API issue?
Related to the last point of https://github.com/c2corg/v6_ui/issues/406#issuecomment-234980027

When saving an outing with dates 
```
date_end: Thu Jul 07 2016 00:00:00 GMT+0200 (CEST)
date_start: Wed Jul 06 2016 00:00:00 GMT+0200 (CEST)
```

they will first be read in the view page as

```
date_end: "2016-07-06"
date_start: "2016-07-05"
```

so one day before the actually saved date, both are shifted by 1 day.

But if you go afterwards and edit the dates, they will be saved correctly this time.
```
date_end: Thu Jul 07 2016 00:00:00 GMT+0200 (CEST)
date_start: Wed Jul 06 2016 00:00:00 GMT+0200 (CEST)
```

will be as it should :
```
date_end: "2016-07-07"
date_start: "2016-07-06"
```

If you create only a `date_start` and save -> it will be ok. But when you go and edit and add a `date_end` -> it will be also 1 day before the saved date (only `date_end` will be affected, not `date_start`). 

Maybe there is a problem with the creating function ?

**Comment by tsauerwein** [comment]
Always use the format `2016-07-06`, because it is only a date and not datetime. The time `Thu Jul 07 2016 00:00:00 GMT+0200 (CEST)` is normalized to UTC, so that you might get a different day.
