### ISSUE TITLE
Migration of the outings associated to climbing sites

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#351]
In v5, it is possible to create an outing from a "climbing site" page => no route is associated to the outing. See for instance: http://www.camptocamp.org/outings/538339/fr/gaillands (associated to the climbing site http://www.camptocamp.org/sites/102326/fr/gaillands)

In v6:
- the climbing sites pages are transformed into waypoint pages, for ex. http://c2corgv6.demo-camptocamp.com/waypoints/102326/fr
- the matching v5 outings are actually migrated to v6: http://c2corgv6.demo-camptocamp.com/outings/538339/fr but have a waypoint-outing association, which is no longer possible in the v6 interface (the association tool in outing pages only allows to associate route).

@tsauerwein do you think it would be possible when migrating such outings (not associated to a route but to a climbing site) to create a basic route (if not already existing) which would be named the same way than the climbing_site waypoint and to associate it between the WP and the outing?

(Of course we could keep the current way those outings are migrated if the above solution is too complicated - I didn't realize until now it was possible- but that would be a bit confusing and not consistent to have those old outings still associated to the climbing site waypoints.)

**Comment by tsauerwein** [comment]
Makes sense.

**Comment by asaunier** [comment]
This topic should be considered quite soon, it's rather important.

**Comment by tsauerwein** [comment]
The following would have to be done:

For all climbing sites (waypoint type = climbing_outdoor or climbing_indoor) that are associated to outings that are not associated to a route, create fake routes:

* These fake routes have the same geometry as the climbing site, the same locales (only the title is set) and activities is set to `rock_climbing`. All other fields are empty.
* Create version and history entries for the fake routes.
* Create an association between the fake route and the climbing site.
* Create an association log entry for this association.
* For the outings without route association, change the association between outing and climbing site to the fake route.
* Update the association log for these associations.
* Remove all other waypoint-outing associations.
* Remove association log entries for all waypoint-outing associations.

**Comment by asaunier** [comment]
Makes sense. Thanks for the analysis!

**Comment by stef74** [comment]
@asaunier @tsauerwein when do you plan ?

**Comment by tsauerwein** [comment]
I was planning to tackle this today.

**Comment by asaunier** [comment]
@stef74 @fbunoz what name do you recommend for the fake routes?

@tsauerwein has observed that since the climbing site will be set as the main waypoint, its name will be displayed as prefix in the route name, so it's not relevant to reuse the site name as the fake route name.
He has suggested to use "dummy route" for instance. Would it fit? Do you have a better idea?

**Comment by tsauerwein** [comment]
In the description we could also show a link that points to an article that explains the idea behind "dummy/fake" routes for climbing sites. It would be up to the association to create such article.

**Comment by asaunier** [comment]
> It would be up to the association to create such article.

If such an article is created, it should be added in v5 because the document_id must be available before running the migration.

**Comment by tsauerwein** [comment]
Should the created dummy/fake route be protected, so that only moderators can modify it?

**Comment by fbunoz** [comment]
> For all climbing sites (waypoint type = climbing_outdoor or climbing_indoor) that are associated to outings that are not associated to a route

No, all outings associated with a climbing site must be treated. In V5, we can associate an outing to 1 or several routes AND to 1 or several sites : http://www.camptocamp.org/outings/list/routes/+/sites/+
During the migration, these outing must keep all there associations.
I think it is not difficult to respect this rule ?

> It would be up to the association to create such article.

Yes : http://www.camptocamp.org/articles/822764/fr/saisir-une-sortie-couenne-sur-la-v6

> Should the created dummy/fake route be protected, so that only moderators can modify it?
Yes.
In V5, a moderator can't modify a protected doc, except to unprotect it, but it is better to allow a moderator to modifiy a doc any time.

> what name do you recommend for the fake routes?

undefined ? :) 
I don't know, but the asociation must decide before the migration.

**Comment by asaunier** [comment]
> I don't know, but the asociation must decide before the migration

Not only before the migration, but before this issue is closed = ASAP = before monday, thanks :)

**Comment by asaunier** [comment]
@tsauerwein What about the outings that are associated to several climbing sites? For instance http://www.camptocamp.org/outings/538678/fr/j3-a-fontainebleau-trois-pignons-circuit-jaune-pd-du-rocher-des-potets-puis-petit-tour-au-91-1
Will this outing be associated to 2 fake routes instead?

**Comment by tsauerwein** [comment]
> No, all outings associated with a climbing site must be treated. In V5, we can associate an outing to 1 or several routes AND to 1 or several sites : http://www.camptocamp.org/outings/list/routes/+/sites/+
> During the migration, these outing must keep all there associations.
> I think it is not difficult to respect this rule ?

Ok, no problem. That makes the query even easier.

> What about the outings that are associated to several climbing sites? For instance http://www.camptocamp.org/outings/538678/fr/j3-a-fontainebleau-trois-pignons-circuit-jaune-pd-du-rocher-des-potets-puis-petit-tour-au-91-1
> Will this outing be associated to 2 fake routes instead?

Yes. That would be in line with what @fbunoz said above ("During the migration, these outings must keep all their associations").

**Comment by fbunoz** [comment]
The feedback from the association about the dummy route : 
- Lang : FR.
- Name (FR) : "Accès pédestre".
- Activity : "hiking".
- Max altitude : climbing site altitude.
- Route type : return trip.
- Duration : 1 day.
- Quality : empty.
- The climbing site is associated as main WP.

**Comment by stef74** [comment]
@shortoland @loicperrin @fbunoz please test

**Comment by fbunoz** [comment]
I verified that all rock climbing outings are georeferenced (using the carto and comparing with not using the carto, it is not friendly as there is a bug on doc count when with zoom on whole world).

**Comment by asaunier** [comment]
> there is a bug on doc count when with zoom on whole world

What do you mean? Is there an issue describing it?

> It is not enough to close this issue.

Could you please precise what is actually preventing from closing the issue?

**Comment by fbunoz** [comment]
> Is there an issue describing it?

Yes : https://github.com/c2corg/v6_api/issues/538

> Could you please precise what is actually preventing from closing the issue?

We must check that the outings are associated to the dummy route of the right climbing site, and that an outing associated to a V5 route and a V5 site is migrated correctly, and another things.

**Comment by loicperrin** [comment]
I have checked with these 2 outings:
http://www.demov6.camptocamp.org/outings/777334/fr/saint-egreve-jardins-du-rif-tronchard-pain-de-sucre-et-secteur-du-dessous
http://www.demov6.camptocamp.org/outings/467958/fr/charmant-som-en-boucle-par-pre-batard-et-qq-voies-a-ste-egreve-au-passage

It seems to be OK.
