### ISSUE TITLE
glacier_gear not saved

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#354]
when creating a route with the property `glacier_gear`, the property is lost.

`glacier_gear: "glacier_crampons"` but then nothing like that returned in the JSON in the view.

**Comment by tsauerwein** [comment]
I can't reproduce. I changed the tests like shown below and it works.

```
diff --git a/c2corg_api/tests/views/test_route.py b/c2corg_api/tests/views/test_route.py
index 65ed671..b34b371 100644
--- a/c2corg_api/tests/views/test_route.py
+++ b/c2corg_api/tests/views/test_route.py
@@ -252,6 +252,7 @@ class TestRouteRest(BaseDocumentTestRest):
             'height_diff_up': 800,
             'height_diff_down': 800,
             'durations': ['1'],
+            'glacier_gear': 'glacier_crampons',
             'geometry': {
                 'id': 5678, 'version': 6789,
                 'geom_detail':
@@ -269,6 +270,7 @@ class TestRouteRest(BaseDocumentTestRest):
         body, doc = self.post_success(body)
         self._assert_geometry(body)
         self._assert_default_geometry(body)
+        self.assertEqual(body.get('glacier_gear'), 'glacier_crampons')
 
         version = doc.versions[0]
```

**Comment by ginold** [comment]
ok I think it's because the client tried to create a route with activity via ferrata witch doesn't have a `glacier_gear`, can it be? 
If so, we should add this property for via ferrata. I'm waiting for client to answer.

**Comment by tsauerwein** [comment]
Right, `glacier_gear` is not a field for via ferrata (which makes sense): https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_route.py#L217-L232

**Comment by ginold** [comment]
We don't need to change. Closing.
