### ISSUE TITLE
converted image aspec ratio

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#356]
The resized uploaded images (for example the ones ending on "SI" - small image) do not hold their original aspect ratio. They are all squares, therefore they appear distorted on thumbnails.

**Comment by tsauerwein** [comment]
Transfered to https://github.com/c2corg/v6_images/issues/5

**Comment by asaunier** [comment]
Yes, in v5, thumbnails are cropped and squared.
2 options:
* we keep the thumbnails as squares and display them as is in the list of images
* we regenerate the thumbnails to keep the full image format.
