### ISSUE TITLE
Simple ID service for documents is needed

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#364]
We need a service that returns very basic data about a document. Eg. title (+title_prefix), id, lang, slug ?!
If the service receives no lang param but a prefered language param, it should figure what is the best locale available.

See https://github.com/c2corg/v6_ui/pull/558

**Comment by asaunier** [comment]
@tsauerwein What do you think is the best approach: have a dedicated web service or use the usual "get document" service with some parameter that would skip the associations and return a subset of attribute (a bit like ``?e=1``?).

To get a subset of attributes, should we use a special schema for each document type?

**Comment by tsauerwein** [comment]
I would create a new web-service. And I don't think we have to create a schema for each type, because you have the same attributes for all types (e.g. `title_prefix` for routes).

**Comment by tsauerwein** [comment]
As discussed with @asaunier: The service accepts a `document_id` and a `lang`. It is supposed to return:

```
{document_id: ..., locales: [{lang: 'en', title: '...', title_prefix: '...']}
```

If the document does not have a locale in the given `lang`, the "best locale" is returned.
