### ISSUE TITLE
Returning a document for a single culture

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#37]
When displaying a document, in most cases it is no use retrieving all cultures, since only one is displayed.

As for now the API returns all available cultures for a given document call.
It would be useful to be able to specify the desired culture.

**Comment by tsauerwein** [comment]
You can do so by appending `?l=en` to the request.

**Comment by asaunier** [comment]
Right, thanks.

I realize that even if we just need a given culture, in the UI "view" page we need to know the other available cultures in order to  generate the links towards the other cultures...
