### ISSUE TITLE
Returning all attributes when creating a document?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#38]
As for now when creating a document, all attributes for all cultures are returned in the JSON response. Ditto when updating?

It might be useful for the mobile app (?) in order to display the full document after creating it.
In the UI, after creating, visitors are redirected to the document "view" page. For instance:
 http://www.camptocamp.org/routes/53123/fr/col-du-bonhomme-depuis-notre-dame-de-la-gorge

This page anyway makes an API call to get the document attributes.
In that case it is no use to return all attributes in the doc creation response (the doc id is enough).

Should we be able to add a parameter in the API call to tell if doc attributes must be returned in the creation response?

**Comment by gberaudo** [comment]
+1 for not returning the attributes when not required. For example it should not be necessary for PUT methods since the client already has the latest version.

**Comment by asaunier** [comment]
Is this issue still relevant?

**Comment by tsauerwein** [comment]
> Is this issue still relevant?

Yes.

**Comment by tsauerwein** [comment]
> Ditto when updating?

When you update a document, you always return to the view page?

**Comment by asaunier** [comment]
> When you update a document, you always return to the view page?

Indeed as far as I know.

**Comment by tsauerwein** [comment]
Ok, so it will be ok with the changes I made in #150.
