### ISSUE TITLE
Create images without title

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_api#399]
@ginold says that API return error 500 when posting images without title.
He wants API to accept images without title.

I observe that in image upload dialog, title is filled with source file name, so it is necessary to empty it by hand.

IMHO this really seems tricky to accept images without title.
=> guidebook.documents_locales.title is mandatory
Not sure document wihout any locale will be correctly handled by the application.

**Comment by asaunier** [comment]
That would be a pity that one cannot upload an image without a title.
In v5 people often use a dummy title for images (eg. "****" or "1234" or the outing title). It's better to have no title at all.
The uploaded filename is indeed not a suitable default title.

**Comment by arnaud-morvan** [comment]
Ok for the no title concept, but no locale ?

**Comment by asaunier** [comment]
No clue :)
Perhaps we could have a locale with an empty title ``''``?
@tsauerwein what do you think?

**Comment by arnaud-morvan** [comment]
empty string is not NULL, should be accepted

**Comment by arnaud-morvan** [comment]
I will try to reproduce and get better idea what is posted and what case the error 500
