### ISSUE TITLE
Possible memory leak with the ES syncer?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#400]
From time to time the dev server has memory problem (almost no free memory).
@gberaudo has then observed that the biggest memory consumers were:
- redis-server;
- es/syncher.py

Would there be something to do to reduce the memory consumer by the syncher?

**Comment by tsauerwein** [comment]
Does the syncer script accumulate memory, or does it only consume much memory when a synchronization is run?

**Comment by asaunier** [comment]
Sorry, no idea.
Actually it's not even sure there's a memory problem with the syncer. Just a suspicion.

**Comment by asaunier** [comment]
Closing because only suspicions.
