### ISSUE TITLE
Add feed filter preferences web-services

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#402]
Add web-services to get/update feed filter preferences (area + activities).

**Comment by asaunier** [comment]
Here are possible specs/examples for the  API services needed to get/set the user's preferred filters.

* Getting the user's filters:
```
GET http://api/users/preferences?user_id=1234
{
  "activities": ["skitouring", "hiking"],
  "areas": [12345, 23456]
}
```
* Setting/updating the prefs:
```
POST/PUT? http://api/users/preferences?user_id=1234
{
  "activities": ["skitouring", "hiking"],
  "areas": [12345, 23456]
}
```
or should we pass the user id inside the JSON object?
* to build the pref UI, we also need to get the list of areas, as described in https://github.com/c2corg/v6_ui/issues/598#issuecomment-250695229
 * what about simply using the usual areas list request http://c2corgv6-demo.gis.internal:6545/areas ?
 * filtering on the ``area_type`` is needed (ditto for the area advanced search, see https://github.com/c2corg/v6_api/issues/419)
 * we would probably need to list all areas of a given ``area_type`` (with no limit as in the current list request)?

**Comment by asaunier** [comment]
> to build the pref UI, we also need to get the list of areas,

Maybe we don't if the pref UI only use a search tool for areas, see https://github.com/c2corg/v6_ui/issues/598#issuecomment-252208853

Then it means we have to make sure the areas are actually indexed by ES and supported by the simple search / association tool.

**Comment by tsauerwein** [comment]
> or should we pass the user id inside the JSON object?

The user-id is not needed at all. It can be obtained from the authorization header.

**Comment by asaunier** [comment]
Great, this way we can also make sure that only the user can access his/her prefs.
I have updated my comment above.
