### ISSUE TITLE
Missing translations for API email messages

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#406]
Those translations are not managed using Transifex as for the UI strings.
They must be added to the code in https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n

Currently only FR and EN texts are available (perhaps they could be improved!?).
We also need them for CA, DE, ES, EU, IT.

Related to https://github.com/c2corg/v6_api/issues/238

**Comment by asaunier** [comment]
@shortoland Do we have translations for those email texts?

**Comment by asaunier** [comment]
Those strings are not used in the UI and are not pulled/pushed between the UI and Transifex.

I am not sure it is possible to add them by hand to Transifex. If yes, not sure either they won't be removed next time new translations are pushed to Transifex (remember the translations that have been lost because the source strings had been modified).

Finally we don't want that those translations are pushed back to the UI (and finally added to the files that browsers will download) since they are not used in the UI. Only by the API.
Anyway adding them to the API requires a manual change to https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n

I know it's not very convenient but there are only a few strings to translate: https://github.com/c2corg/v6_api/tree/master/c2corg_api/emails/i18n/fr
Perhaps you could send them by email to translators?

**Comment by shortoland** [comment]
I will.

**Comment by shortoland** [comment]
@asaunier Waiting for basque translation before sending you info.

**Comment by asaunier** [comment]
@shortoland great, thanks!

Could you post those translations in this issue when available?

**Comment by shortoland** [comment]
@asaunier Yes, of course.

**Comment by shortoland** [comment]
Here are the traductions:

[Traductions emails.xlsx](https://github.com/c2corg/v6_api/files/574109/Traductions.emails.xlsx)

Shall we close the ticket ?

**Comment by asaunier** [comment]
@shortoland Thanks!
No, it's better to keep the issue open until the translations are actually integrated.

**Comment by asaunier** [comment]
@shortoland I have made a pull request with the translations you have provided: https://github.com/c2corg/v6_api/pull/480

Just one thing (sorry for not mentioning it earlier): the email bodies are a bit raw and minimalistic: only one sentence with a link.
We could have been a bit more detailed, explaining why people receive the email.

At least that would be better to start the messages with ``Hello <user name>`` and close it by a signature such as ``The Camptocamp.org team`` or something like that.

Could you provide me the translations for such expressions? I can also try google translate, perhaps it's faster and good enough for such simple expressions?

**Comment by asaunier** [comment]
Argh, I had not noticed there were some other strings to translate (+ some code to change to enable the translations):
https://github.com/c2corg/v6_api/blob/de9e3a730f299b5fcc98183edaee04de7027e1a5/c2corg_api/emails/email_service.py#L78-L79

* ``Email change on Camptocamp.org``
* ``To activate your new email click on %s``

**Comment by asaunier** [comment]
> Could you provide me the translations for such expressions? I can also try google translate, perhaps it's faster and good enough for such simple expressions?

I have updated my PR https://github.com/c2corg/v6_api/pull/480 relying on Google Translate.
It's probably possible to add the name of the user after "Hello" but I'm not sure the attribute is always available. So I have used the simplest solution.

Concerning the untranslated email for a new email activitation, I have created a dedicated issue https://github.com/c2corg/v6_api/issues/481
@gberaudo Do you remember why it has not been already done? Missing lang attribute?

@shortoland Anyway it would make sense to prepare the translations for:
* ``Email change on Camptocamp.org``
* ``To activate your new email click on %s``
This way we will be able to integrate them when issue https://github.com/c2corg/v6_api/issues/481 is fixed. Thanks!

**Comment by gberaudo** [comment]
@asaunier, there is no special reason: it was simply missed when email translation was added.

**Comment by asaunier** [comment]
Does it mean I can use ``_send_email_with_link`` as for the other emails:
https://github.com/c2corg/v6_api/blob/de9e3a730f299b5fcc98183edaee04de7027e1a5/c2corg_api/emails/email_service.py#L68-L72
?

Or perhaps there is a problem with the fact that we should use ``user.email_to_validate`` instead of ``user.email``?
Then I could rather update the ``send_change_email_confirmation`` function to use 
https://github.com/c2corg/v6_api/blob/de9e3a730f299b5fcc98183edaee04de7027e1a5/c2corg_api/emails/email_service.py#L65-L66

**Comment by shortoland** [comment]
@asaunier AAaahhhhhh ... hope you are not in a hurry ;-)

Here is the file with new columns for new translations. Please confirm it's OK and definitly enough for you.

[Traductions emails.xlsx](https://github.com/c2corg/v6_api/files/576263/Traductions.emails.xlsx)

**Comment by asaunier** [comment]
> Here is the file with new columns for new translations.

It's OK. I don't need the translations for "Hello" :)
Please rather use a Google Sheet instead of an .xslx file, really not handy.

**Comment by shortoland** [comment]
Do you know how to say "Hello" in basque ? (I don't ;-)

I have send the request to the translators, waiting for their feedback. I will forward you when completed.
I am quite busy so sorry, I will keep this excel format this time.

**Comment by asaunier** [comment]
> Do you know how to say "Hello" in basque ? (I don't ;-)

Easy: "Kaixo"
https://translate.google.fr/#fr/eu/Bonjour

> I am quite busy so sorry, I will keep this excel format this time.

Come on, that's not an excuse and it would save time to everyone (for instance no need to upload the file again in the issue). It's only a copy-paste...

I have done it for you : https://docs.google.com/spreadsheets/d/1XnO8mx203MKq8FevHoEbKkcxLJ6_BgCy_0CVFBOQ12A/edit?usp=sharing

Please use it, thanks :)

**Comment by shortoland** [comment]
Using automatic translators is cheating ;-)

Translators will use your Google sheet.

**Comment by asaunier** [comment]
Thanks, I have just added a column with translations for "The Camptocamp.org team".

**Comment by asaunier** [comment]
@shortoland I have made the file accessible and editable by anyone. Or do you prefer we give edit rights on a per user basis?

**Comment by asaunier** [comment]
@shortoland Do you think we could get the missing ES and EU translations in https://docs.google.com/spreadsheets/d/1XnO8mx203MKq8FevHoEbKkcxLJ6_BgCy_0CVFBOQ12A/edit#gid=0 soon?

**Comment by shortoland** [comment]
@asaunier I have sent a reminder yesterday to the concerned translators. No answer yet.

**Comment by stef74** [comment]
I remove the blocking tag ... ES/EU is not blocking ;-)

**Comment by shortoland** [comment]
Spanish translation is now online. Only waiting for basque ...

**Comment by asaunier** [comment]
The email change strings are still missing for EU, I have used google translate and compared to other email strings in EU. PR https://github.com/c2corg/v6_api/pull/487 has been merged a few days ago. If changes must be done in EU or in another language, please reopen the issue or create a new one.

**Comment by shortoland** [comment]
Basque translation added (just in case ...)

**Comment by asaunier** [comment]
Thanks @shortoland I have created PR https://github.com/c2corg/v6_api/pull/544 to take the new translations into account.
