### ISSUE TITLE
List of attributes for listing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#41]
As for now a listing request (eg. waypoints/) returns all the attributes of every documents.

In most cases only a few attributes such as the title, elevation, etc. are actually needed.
http://www.camptocamp.org/outings

In some cases, having a more comprehensive set of attributes is useful. For instance the "conditions" page:
http://www.camptocamp.org/outings/conditions/orderby/date/order/desc

**Comment by tsauerwein** [comment]
In the listings you would also need to know in which cultures a document is available, right?

**Comment by asaunier** [comment]
That might be useful indeed.

For instance in http://www.camptocamp.org/routes it would make sense, if several cultures are available for a given route, to pick the most appropriate culture (depending on the interface language or the user's prefs).
