### ISSUE TITLE
Add version web-service for all document types

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#410]
Currently not all document types have a web-service to get a specific version of a document. It is missing for:
- [x] area
- [x] image
- [ ] ~~map~~

Note: There should be no such service for user profiles.

**Comment by asaunier** [comment]
Showing an old version of an image or an area is useful indeed.
Maps are not real documents in v6, there are not even a detail view page for maps. So it's no use having a web-service to get a version of a map.

**Comment by asaunier** [comment]
Maybe somehow related: https://github.com/c2corg/v6_api/issues/412 ?

**Comment by tsauerwein** [comment]
> Maybe somehow related: #412 ?

Except that it concerns the API, no. ;)

**Comment by tsauerwein** [comment]
Fixed with #631
