### ISSUE TITLE
Explicit associations between areas and images

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#412]
For instance when uploading an image on an area detail view page (see https://github.com/c2corg/v6_ui/issues/668):
* the ``associations`` attribute remains empty in the API detail view response of the area (=> no image listed)
* the ``associations`` attribute of the image detail view response has no "areas" entry.

Probably related to https://github.com/c2corg/v6_api/issues/389

**Comment by asaunier** [comment]
It seems also that the ``profile`` service does not provide the user's associations.
We probably don't need all associated documents (for instance outings) but it would be useful for associated images. For instance: http://www.camptocamp.org/users/377/fr#images

**Comment by tsauerwein** [comment]
> the associations attribute of the image detail view response has no "areas" entry.

Like for the other document types, the implicit associations between a document and areas are listed in the `areas` attribute. For example: http://localhost:6544/images/23474

**Comment by asaunier** [comment]
Area documents seem a bit special. We obviously don't want to display all "geo-associated" documents. It's the goal of the "waypoints", "routes", "outings" buttons in the "associated documents" section. For example http://c2corgv6.demo-camptocamp.com/areas/14411/fr/chablais
We could add buttons for other document types such as images etc.

On the other hand, as a standard document, it should be possible to upload an image to an area document ("direct association", not "geo-association"). Such associated images should be available in the detail view page, as for the other documents.
Do you think that's a problem?

**Comment by tsauerwein** [comment]
> the associations attribute remains empty in the API detail view response of the area (=> no image listed)

Currently no explicit associations are possible between and other document types (only implicit associations using the document geometries that are updated automatically).

But we could include the latest 30? images that are implicitly associated to the area.

**Comment by asaunier** [comment]
I don't think it makes sense. Only the images explicitely associated to an area are worth being shown in the area detail view.

Let's say that you made a ski outing in Savoie and that the outing images are georeferenced. Then they will be geo-associated to the area "Savoie". But they are probably not relevant in the detail view of area "Savoie". When you look at the document "Savoie" you are interested by data and images about the area itself, not images taken in this area.
A bit like the wikipedia page for Savoie: https://fr.wikipedia.org/wiki/Savoie => you see images about Savoie.

Ditto when viewing a WP detail view: you want to see images about the WP, not images of routes or outings associated to this WP.

**Comment by tsauerwein** [comment]
> On the other hand, as a standard document, it should be possible to upload an image to an area document ("direct association", not "geo-association"). Such associated images should be available in the detail view page, as for the other documents.
> Do you think that's a problem?

We can do an exception for area-image associations. But having explicit and implicit associations between images and areas might cause confusions.

**Comment by asaunier** [comment]
In v5 that's 2 separated concepts: "associations" and "geoassociations". I don't remember if we have such  a distinction in v6.

For users, I think it's not confusing at all because people don't really realize images may be "geo-associated" to an area. They just think they can upload images to an area document.
