### ISSUE TITLE
IntegrityError while using the migration script

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#416]
I have just run the migration script from a fresh v5 dump.

The first part of the migration has worked as expected, including the importation of articles:

> Importing articles
Total: 4751 rows
1 of 4751
Done (duration: 0:00:07.405211)
Importing locales of articles
Total: 12467 rows
1 of 12467
792 of 12467
1873 of 12467
2833 of 12467
3535 of 12467
4665 of 12467
5549 of 12467
7019 of 12467
7425 of 12467
8359 of 12467
8715 of 12467
9407 of 12467
10345 of 12467
10722 of 12467
11563 of 12467
Done (duration: 0:00:49.614066)

But the next step (importing history_metadata) failed because of an integrity error:

> Importing history_metadata
Total: 1199480 rows
1 of 1199480
3003 of 1199480
6006 of 1199480
9009 of 1199480
12012 of 1199480
Traceback (most recent call last):
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 447, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.IntegrityError: insert or update on table "history_metadata" violates foreign key constraint "history_metadata_user_id_fkey"
DETAIL:  Key (user_id)=(745118) is not present in table "user".

(...)

> DETAIL:  Key (user_id)=(745118) is not present in table "user". 
 [SQL: 'INSERT INTO guidebook.history_metadata (id, user_id, comment, written_at) VALUES (%(id)s, %(user_id)s, %(comment)s, %(written_at)s)'] [parameters: ({'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 182042), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14153}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 200346), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14154}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 225037), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14155}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 239037), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14156}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 250433), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14157}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 261180), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14158}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 288986), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14160}, {'written_at': datetime.datetime(2007, 11, 7, 13, 5, 35, 301448), 'user_id': 2, 'comment': 'Automatically imported', 'id': 14161}  ... displaying 10 of 1001 total bound parameter sets ...  {'written_at': datetime.datetime(2007, 11, 7, 13, 6, 0, 271143), 'user_id': 768, 'comment': 'imported from v4', 'id': 15455}, {'written_at': datetime.datetime(2007, 11, 7, 13, 6, 0, 283861), 'user_id': 768, 'comment': 'imported from v4', 'id': 15456})]

**Comment by asaunier** [comment]
There are integrity errors in the source v5 dump because user 745118 is partily missing. It's a special user account gathering contributions of deleted accounts. For some (unknown) reason this account has been deleted twice this year, but the contributions and their history metedata still remain:

```
c2corg=# select count(*) from app_users_private_data where id = 745118;
 count 
-------
     0
(1 row)

c2corg=# select count(*) from app_history_metadata where user_id = 745118;
 count 
-------
  3655
(1 row)
```

**Comment by tsauerwein** [comment]
Would it be possible to "restore" this account?

**Comment by asaunier** [comment]
Perhaps. We could try to recreate by hand the missing:
* app_users_private_data entry
* app_users_groups entry
* standard user document (figures + locales) entries + related history_metadata

But I think I will rather try to find an old v5 dump first and restore/migrate it.

**Comment by asaunier** [comment]
I have imported an older v5 dump where this user is not missing and it worked as expected.
Since the problem is in v5 and do not require an action in v6, I close the issue.
