### ISSUE TITLE
Text formating conversions to do in the migration script

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#417]
- [x] `[q]` => `[quote]`
- [x] `[c]` => `[code]`
- [ ] ~~`[toc(.*)]` (regexp) => `[toc]`~~

Related to https://github.com/c2corg/v6_ui/issues/131#issuecomment-237195445 and https://github.com/c2corg/v6_ui/pull/695

**Comment by asaunier** [comment]
* [ ] Also convert the wikilinks of old v5 URLs that are no longer supported in v6. For instance:
 * ``[[users/12345|Toto]]`` => ``[[profiles/12345|Toto]]``
 * ditto with ``summits``, ``huts``, ``parkings``, etc. => ``waypoints``.

**Comment by asaunier** [comment]
* [ ] converting common bbcode tags to markdown?? See https://github.com/c2corg/v6_ui/issues/131#issuecomment-256396802

**Comment by stef74** [comment]
@asaunier for me you conversion is probably an good idea but not realistic in term of planning ... So i Propose to close (no other action needed ?).

**Comment by asaunier** [comment]
I prefer to leave it open until the migration is actually done.

**Comment by tsauerwein** [comment]
I created a separate issue for the remaining problem (bbcode -> Markdown): c2corg/v6_api#516
