### ISSUE TITLE
Check that locales of user profile are not included in query for listings

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#423]
When querying a user profile for listing views, no fields from the locales are needed, so there should be no join on the locales table.

**Comment by asaunier** [comment]
Returning the langs available for a given profile is useful (but not required), for instance to generate profile links with both id and lang.

**Comment by tsauerwein** [comment]
Yes, right. See https://github.com/c2corg/v6_api/issues/446

I will close this issue.

**Comment by tsauerwein** [comment]
Or return the `available_langs`.
