### ISSUE TITLE
User profiles access rights

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#425]
It should be possible for user to choose whether their profile page is public or only accessible to authenticated users (or even completely private?? not available in v5).

See https://github.com/c2corg/v6_ui/issues/335 and https://github.com/c2corg/v6_ui/pull/728 for the UI part

If the visitor is not granted access to the current profile, perhaps we could return very minimal information, such as the guidebook name (and forum name?) since this attribute is anyway available in outings for instance.

**Comment by tsauerwein** [comment]
TODO:

* [ ] Add field `is_profile_public` to `User`
* [ ]  Migrate field `is_profile_public`
* [ ] Include field in `/users/account` web-service
* [ ] Adapt web-service `/profiles/{user_id}` to check for `is_profile_public`
