### ISSUE TITLE
Mailing list service

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#426]
- [x] service returning the list of mailing lists + the registration status for the passed user id
- [x] service to register/unregister to a mailing list
- [x] update the sympa table when a user updates their email address => trigger
- [x] migration from v5? (dump/restore of the v5 "sympa" table?)
 * [x] remove emails that are no available in the user account table (syncro errors in v5?)
- [ ] ~~install the tools existing in v5 to get the snow reports from SLF or MF and send them via the Sympa system~~ => done by the association

**Comment by tsauerwein** [comment]
How do you get/set that information in the API?

**Comment by asaunier** [comment]
It's probably part of a bigger tas: installing/setting up Sympa in the API https://www.sympa.org/
It's already used in v5. https://github.com/c2corg/camptocamp.org/blob/master/lib/model/doctrine/generated/BaseSympa.class.php

Basically Sympa has a table whose cols are the list identifier and the subscriber's email.
The API should then update this table to add/remove entries with the subscriber's email for the desired list identifier.

That's not an high priority task (not needed for beta).

**Comment by stef74** [comment]
@asaunier do you have discuss with @mfournier to identify action nedeed ?

**Comment by asaunier** [comment]
Yes, there is a mail discussion on the dev mailing list. I will give feedbacks when the PR are merged.
