### ISSUE TITLE
Filter documents feed according to quality attribute

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#432]
One of the goal of the `quality` attribute is to be able to strip poor documents (especially outings) out of the homepage (because people are not interested by outings with 0 or almost 0 information).

The idea would be that only documents with a minimal quality ("mean"?) would be added to the feed.

My concerns:
- the filtering should only apply to the homepage feed (for the user profile feed, all docs created by the user should be listed).
- I am not sure people will always remind to update the `quality` attribute when creating an outing or an other document. Then they will complain because it doesn't show up in the feed...
- If an outing is created with quality "draft" (thus is not added to the feed - or at least not shown), will it be possible to make it appear into the feed when its `quality` is eventually upgraded (I think the feed only takes document creations into account - not updates)?
- on the other hand if someone has created an empty outing but set its quality to `good` (never trust users :P ), moderators may edit the outing the downgrade the quality but will the outing be removed from the feed?

**Comment by tsauerwein** [comment]
> I am not sure people will always remind to update the quality attribute when creating an outing or an other document. Then they will complain because it doesn't show up in the feed...

That's my main concern. Me as a user, I wouldn't know what to do with that field. And I wouldn't *rate* my own outings as *good quality*.

**Comment by fbunoz** [comment]
> on the other hand if someone has created an empty outing but set its quality to good (never trust users :P ), moderators may edit the outing the downgrade the quality but will the outing be removed from the feed?

Idealy, an empty outing should be set automaticaly to "empty" quality when the contributor store its outing, then the feed can not see "good quality" in the DB.
The conditions to set automatically the "empty" grade is simple. For the other grades, it's more complicated and it's simpler to let the contributors/moderators choose the better grade.

**Comment by asaunier** [comment]
> Idealy, an empty outing should be set automaticaly to "empty" quality when the contributor store its outing, then the feed can not see "good quality" in the DB.

There's no such plan. This attribute is always set by hand.

**Comment by loicperrin** [comment]
> the filtering should only apply to the homepage feed (for the user profile feed, all docs created by the user should be listed)

Yes

> If an outing is created with quality "draft" (thus is not added to the feed - or at least not shown), will it be possible to make it appear into the feed when its quality is eventually upgraded (I think the feed only takes document creations into account - not updates)?

Outing with quality "draft" should be displayed on homepage feed. Only outing with quality "empty" should be filtered.
For me, it is not a problem if the outing is not upgraded in the list when updated, but it should appear in the list (according to its creation date) when quality is modified from "empty" to another value.

> on the other hand if someone has created an empty outing but set its quality to good (never trust users :P ), moderators may edit the outing the downgrade the quality but will the outing be removed from the feed?

It should indeed.

**Comment by asaunier** [comment]
> For me, it is not a problem if the outing is not upgraded in the list when updated, but it should appear in the list (according to its creation date) when quality is modified from "empty" to another value.

The problem is that only document creations are added to the feed, to avoid overflowing the feed with many "doc update" notifications (the use case was "a moderator updates many documents in a row").
As for now, only the initial quality of the outing would be taken into account. As a result filtering on quality is not that relevant.

**Comment by cbeauchesne** [comment]
It's now handled on UI side. Not the best solution (useless data loading), but it does the job. And as the future of the feed page is not clear, I close this issue.
