### ISSUE TITLE
Auth vs profile-feed

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#441]
It seems that the profile-feed service is only available to authenticated users.

Actually it should depend on if the profile is public or not.

If not public => only authenticated users may access the service
If public => anyone may access the service.

Currently when displaying a user profile, the profile attributes are shown as expected but the user feed fails because:
> Getting feed data failed:
debug_authorization of url http://c2corgv6-demo.gis.internal:6545/profile-feed?pl=fr&u=377 (view name '' against context <c2corg_api.RootFactory object at 0x7fa1ab236c18>): ACLDenied permission 'authenticated' via ACE '<default deny>' in ACL [('Allow', 'system.Everyone', 'public'), ('Allow', 'system.Authenticated', 'authenticated'), ('Allow', 'group:moderators', 'moderator')] on context <c2corg_api.RootFactory object at 0x7fa1ab236c18> for principals ['system.Everyone'] : Forbidden

**Comment by tsauerwein** [comment]
> If not public => only authenticated users may access the service
> If public => anyone may access the service.

Can't you check this client-side before requesting the feed?

**Comment by asaunier** [comment]
I don't understand. Check what?

Currently, as descirbed above, if an anonymous user loads a public profile, the user feed fails saying ``ACLDenied permission 'authenticated' via ACE ``

In the "user profile" PR https://github.com/c2corg/v6_ui/pull/728
I have done this 
https://github.com/c2corg/v6_ui/pull/728/commits/c3c192f45d2aed46e04c8fb24b9d1de4d6245001https://github.com/c2corg/v6_ui/blob/c3c192f45d2aed46e04c8fb24b9d1de4d6245001/c2corg_ui/static/js/auth/authservice.js#L352-L354

**Comment by tsauerwein** [comment]
Sorry, I misunderstood. Yes, checking if the profile is public or not would be the right thing.
