### ISSUE TITLE
Include user locale for history and version web-service

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#446]
When generating the link to the user-profile page, it would be useful to know the available locales of the user-profile. Currently only the user id is returned, so the UI server-side has to make a request to the API to get the available locales. To avoid this request, the history and version web-services could directly include the locales.

See also https://github.com/c2corg/v6_ui/pull/728#discussion_r84428234

**Comment by cbeauchesne** [comment]
Now useless, with the new UI/API model.
