### ISSUE TITLE
Support of the "accidents" doctype

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#449]
"xreports" in v5 (same name in v6)
http://www.camptocamp.org/xreports

See the attributes list here (sorry, in French): https://docs.google.com/spreadsheets/d/1Q_fl7UQKPMgzlnk5tvAGqrmesrwfA5gges8p25XLes8/edit#gid=1416655053

The DB structure in v5: https://github.com/c2corg/camptocamp.org/blob/master/data/sql/tables/db_xreports.sql
- [x] model and DB structure
- [x] migration script
- [x] API services (views)?

**Comment by tsauerwein** [comment]
> API services (views)?

xreports are a bit special, right? E.g. you can create reports anonymously? And not all of the information is public?

**Comment by asaunier** [comment]
> E.g. you can create reports anonymously?

You do need to have a user account anyway.
"Anonymous" reports are created by the moderators using a generic account. See
http://www.camptocamp.org/articles/697210/en/serac-database-of-incident-and-accident-reports
> If you prefer to remain anonymous, or not to link this report to your c2c account, send the report (along with any photos) by email to base-accidents@camptocamp.org, and it will be entered via the SERAC database account.

> not all of the information is public?

I think so. See http://www.camptocamp.org/articles/697210/en/serac-database-of-incident-and-accident-reports#who-will-be-able-to-see-my-report-how-might-it-be-used
> However, your personal information is only visible by moderators and researchers.
This personal information includes: how often you do this activity, number of excursions during the year, autonomy in the activity, age at the time of the event, gender, number of previous injuries.

**Comment by dkocich** [comment]
@asaunier hello :) I have few questions on You.

1) In old DB (`app_xreports_archives`) there are columns `avalanche_level (smallint),` and `avalanche_slope (smallint),`. I can't see them in GDoc. Do you want to throw that data away?

2) Same table - there is `author_status smallint`. Which [should contain values 0,1,2,3,4,](https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/apps/frontend/modules/xreports/config/module.yml#L57-L63), but rows contain only 30,100,10,20,40 (same numbers with extra 0). Can you check what data is on old site camptocamp.org (I can't access it)? Maybe I should just remove extra 0's and convert everything to good values.

**Comment by asaunier** [comment]
> 1) In old DB (app_xreports_archives) there are columns avalanche_level (smallint), and avalanche_slope (smallint),. I can't see them in GDoc. Do you want to throw that data away?

I don't know. This document type has been introduced recently (end of 2015), I think there is no reason that v5 attributes are dropped in v6. Perhaps an error in the google docs.
@stef74 @fbunoz @gottferdom could you confirm?

>  there is author_status smallint. Which should contain values 0,1,2,3,4,,

That's correct.
That's indeed the values that are available in the table ``app_xreports_archives`` available in our copy of the v5 database (``c2corg`` on the dev server):
```
c2corg=# select distinct(author_status) from app_xreports_archives;
 author_status 
---------------
              
             1
             2
             3
             4
(5 rows)
```
Where have you found 30,100,10,20,40?

**Comment by dkocich** [comment]
I checked again - it was a problem with my query... It should be fine now and column looks ok. Thanks.

**Comment by asaunier** [comment]
> 1) In old DB (app_xreports_archives) there are columns avalanche_level (smallint), and avalanche_slope (smallint),. I can't see them in GDoc. Do you want to throw that data away?

I have checked with the client: all attributes from v5 should be ported to v6. I have added the missing attributes in the google sheet and added a column with the name of the attributes in the v5 tables so that it's easier for you.

**Comment by dkocich** [comment]
I noticed few other things...
1)
Event type [here](https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/apps/frontend/modules/xreports/config/module.yml#L11-L22) do not contain value `5` which is in the data during migration (only 3 times from +-300 rows).
2)
avalanche_slope has also missing values (`39,42,45`) [here](https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/apps/frontend/modules/xreports/config/module.yml#L45-L55) , but here I did change myself. Is it ok? Probably someone just changed intervals range...
        '39': '39-41°',
        '42': '42-44°',
        '45': '45-47°',
3)
I see that some of the reports geometries are empty (normal and archived also). Now we are changing migration script to not import articles/books which should not have geometry. We should look at it later...
 
![image](https://cloud.githubusercontent.com/assets/6165660/19808991/86212536-9d27-11e6-89c3-3585633406bb.png).

**Comment by asaunier** [comment]
> 1) Event type here do not contain value 5 which is in the data during migration (only 3 times from +-300 rows).

@stef74 @fbunoz do you know what's this value 5 and what we should to with the 3 entries that has such an event_type?

> 2) avalanche_slope has also missing values (39,42,45) here ,

It seems the indices of https://github.com/c2corg/camptocamp.org/blob/72e777075f2e6260b1d2ef563ab0f90c383038ba/apps/frontend/modules/xreports/config/module.yml#L45-L55 are the upper slope angle.
What's the problem with  values (39,42,45)? They are also found in the database entries?

> 3) I see that some of the reports geometries are empty

It seems that geolocalizing those events is not mandatory. As a result some reports may have no geometry. It should work the same than for images (some have geometries, others have none).
Is there a problem here?
If there's something special done with events with no geometry, do we do the same for images with no geometry?

**Comment by stef74** [comment]
@asaunier I don't know ...
@fbunoz could you help ?
