### ISSUE TITLE
Handle activities as multi-selectable for routes/outings/...

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#45]
As for now one can select only one activity at a time (I think).
See for instance:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L21-L23

**Comment by tsauerwein** [comment]
Done for routes with #53

**Comment by asaunier** [comment]
> Done for routes with #53

OK. We will have to make sure it's handled the same when we will add outings.
Perhaps we could already update the "image" model:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/image.py#L22-L24
to change it accordingly to the "route" model:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/route.py#L30

**Comment by tsauerwein** [comment]
Closing as outings are now implemented with activities as multi-selectable.
