### ISSUE TITLE
Feed - added photos issue

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#454]
when uploading multiple images, the feed will return the action 'added photos' with 3 times the same image.
![screenshot from 2016-10-26 12-50-57](https://cloud.githubusercontent.com/assets/7814311/19723314/fcd979d4-9b7a-11e6-984c-31d8f06f18a1.png)

**Comment by tsauerwein** [comment]
Did you try this on the demo instance? What document type was it that you added the images to? Did you create the document, or some other user?

And it would be great if you could show me what was stored in the database:

    select * guidebook.feed_document_changes from document_id = ?;

Thanks!

**Comment by tsauerwein** [comment]
@ginold It's ok, I found the problem. PR to come.
