### ISSUE TITLE
Feed update when adding images to an outing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#464]
See https://github.com/c2corg/v6_ui/issues/816

> I have uploaded images to 2 outings (made no other change in the outings) and the feed reports that I have updated those outings. Shouldn't it report that I have added images to them, instead?
>
> On the other hand I have also uploaded images to a route previously and the feed actually reports that I have added images to it.

**Comment by tsauerwein** [comment]
See https://github.com/c2corg/v6_ui/issues/816#issuecomment-258467129
