### ISSUE TITLE
Missing "delete document" tool

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#465]

**Comment by asaunier** [comment]
Can this issue really wait for 6.1? It means moderators would have no way to neutralize incorrect or inappropriate documents.

**Comment by tsauerwein** [comment]
> It means moderators would have no way to neutralize incorrect or inappropriate documents.

Except doing it by hand in the database.

**Comment by asaunier** [comment]
OK then, but is it really a good option:
* high risk of making damages in the DB (if incorrect or missing commands)
* quite a lot of actions to do: remove the archives and last version (both figures and locales and geometries), remove associations, remove history, invalidate cache, etc.

**Comment by asaunier** [comment]
### Description

In this issue we will assume that we only delete "standard" documents: **waypoints, routes, outings, articles, xreports, books**. Since creating areas or maps is not accessible to the public, we might consider it is not needed to support those types (by the way maps are not "wiki" documents as the others).

**Deleting a user account is needed as well but should probably be considered in a dedicated PR** that would be an evolution of the current one. It's a bit more complicated since both the user account and the profile document should be removed. In addition changes should be done in the history of all edited documents. In v5, user account deleting was in fact done by merging the target account to a special account.

When removing a document, say a route, entries must be deleted in:
* main tables ``routes``, ``documents``, ``routes_locales``, ``documents_locales``, ``documents_geometries`` _[Note: delete entries for all available languages]_
* archives tables ``routes_archives``, ``documents_archives``, ``routes_locales_archives``, ``documents_locales_archives``, ``documents_geometries_archives``
* metadata tables ``documents_versions`` and ``history_metadata``
* associations tables ``associations``, ``association_log``, ``area_associations``, ``map_associations``
* comment table ``documents_topics`` + the comments should be removed in Discourse (for all langs)

Additional tasks:
* invalidate the API and UI caches for the deleted document
* update the ElasticSearch index
* for images: delete the related files in the images backend (that requires to get the list of filenames in the ``images`` and ``images_archives`` before deleting them). See https://github.com/c2corg/v6_images/issues/35

### Constraints

**It might be necessary to check for constraints before removing a document.**
For instance since routes should have at least one associated waypoint, it should not be possible to delete a waypoint if it's the only one associated to some routes. Ditto for outings: deleting a route should not be possible if outings are only associated to this route.

### Implementation

I am at the very beginning of the study but I have noticed Cornice supports DELETE requests. See for instance:
* http://cornice.readthedocs.io/en/latest/tutorial.html?highlight=delete#users-management
* http://cornice.readthedocs.io/en/latest/api.html?highlight=delete
