### ISSUE TITLE
Search functionality not working for created documents

### ISSUE THREAD

**Issue by dkocich** [c2corg/v6_api#473]
Did you tried to use "search by title" for some document type you just created (new waypoint/article/etc.)??? Did it work?

Search by title for already imported documents works normally, but -

- when I create a new article called "our awesome journey"

I can see it on a main page of articles after the load. When I try to use search by title, I get nothing (only other articles).

![image](https://cloud.githubusercontent.com/assets/6165660/20010575/de9e6d8c-a2a8-11e6-8259-83f0773dac00.png)

When I try to use search manually - POST query to ES (text/plain) on http://localhost:9200/c2corg_dkocich/c/_msearch I get no result (search for other articles work).

```
{"type": ["c"], "index": ["c2corg_dkocich"]},
{"from": 0, "query": {"multi_match": {"fields": ["title_*.ngram", "title_*.raw^2"], "query": "our awesome journey"}}, "size": 10}

```
(do not forget to add blank line after ES query)

- when I create 2 new waypoints called Prague castle I can't search them, but here it is maybe more complicated:
  - when I try to use search and my URL updates to http://localhost:6558/waypoints#q I get no result again like in the case of articles
OR
  - when I activate "Filter on map extent" points also disappear => search by BBOX do not work too?

![image](https://cloud.githubusercontent.com/assets/6165660/20011439/f1436fb6-a2ab-11e6-9a5c-353ee1a95c35.png)

**Comment by asaunier** [comment]
Perhaps because the ES syncer script is not running in your API?
https://github.com/c2corg/v6_api#run-the-application

**Comment by dkocich** [comment]
Ok, it works now. It was a problem of the ES syncer which was not running properly. I am closing this issue.
