### ISSUE TITLE
Attributes migration

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#474]
### Waypoints

* [x] access: there should be a blank line and a title (depending on the language of the document) before accomodation info _(moved from https://github.com/c2corg/v6_ui/issues/791#issuecomment-258194538)_  see https://github.com/c2corg/v6_api/pull/512

### Routes

* [x] During migration, all routes whose "activities" field has "rock_climbing" AND has not "hiking", the field "climbing_outdoor_type" must be set to "multi". [low prio / nice to have] _(moved from https://github.com/c2corg/v6_api/issues/477)_

**Comment by fbunoz** [comment]
For the "climbing_outdoor_type" field, I committed a proposal in a branch to manage it : 
https://github.com/c2corg/v6_api/commit/618ba4f7e0a73eeb50a5d0472c6755e5ae63dbbb
It is not tested.

**Comment by asaunier** [comment]
> For the "climbing_outdoor_type" field, I committed a proposal in a branch to manage it : 
618ba4f

Please create a pull request, thanks.
