### ISSUE TITLE
Make sure it is possible to block an account

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#484]
Related to https://github.com/c2corg/v6_api/issues/9
especially https://github.com/c2corg/v6_api/issues/9#issuecomment-257904999

To do:

* [x] Add a field `blocked` (boolean, default: `false`) to `User` (write an Alembic migration script)
* [x] Add a web-service to block/unblock a user (requires moderator rights).
* [x] For authenticated requests when validating the authentication token: Check if the user is not blocked, otherwise fail.
* [x] On login, check if the account is not blocked.
* [x] Add a web-service to get all blocked accounts.
* [x] Block/unblock accounts in Discourse ([suspend](https://meta.discourse.org/t/whats-the-difference-between-suspended-and-blocked-users/7171))

**Comment by tsauerwein** [comment]
I updated the description with a todo list.

**Comment by desnoes** [comment]
I have created a fake account for the test. I checked i am able to block the authentication. But i was not able to check the action of a user already connected can be blocked. I do not succeed to have simultaneously 2 windows: one with my account and one with the fake account.
@asaunier @tsauerwein : do you know how i could proceed ?

**Comment by dkocich** [comment]
open different browser or use incognito window for 2nd login?

**Comment by desnoes** [comment]
@dkocich : thanks for the tips

> For authenticated requests when validating the authentication token: Check if the user is not blocked, otherwise fail.

Test is ok. Access is denied if the user is blocked (maybe the message could be for explanatory)

If the user is already authenticated, he cannot modify a document nor add images.

So for me, the test is passed successufully.
