### ISSUE TITLE
Do not return JSON array as top-level element

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#49]
`/waypoints` currently returns an array which is a security problem: http://flask.pocoo.org/docs/0.10/security/#json-security

Though new browsers are not affected (see http://stackoverflow.com/a/16880162/119937), it would be safer simply not to return an array.

**Comment by asaunier** [comment]
What should be returned instead?

**Comment by tsauerwein** [comment]
For example:

    {'waypoints': [ ...] }

**Comment by gberaudo** [comment]
@tsauerwein, are you we are vulnerable to this issue?
Our services expect the request to have content type `application/json` and will
not send back the data otherwise.

**Comment by tsauerwein** [comment]
> Our services expect the request to have content type application/json and will not send back the data otherwise.

Only POST and PUT expect JSON. This is related to GET.

**Comment by gberaudo** [comment]
Oh, yes you are right.

There is also the barrier of authentication: without credentials, the
cracker will not be able to
access restricted content.

**Comment by tsauerwein** [comment]
> without credentials, the cracker will not be able to access restricted content.

The token is in a cookie, which will be sent with every request to the domain. So, that's no protection.

**Comment by gberaudo** [comment]
If we go with cookie based authentication, I think we must restrict
origin to a whitelist of domains and require preflight for all methods.

**Comment by tsauerwein** [comment]
Will be fixed with #28

**Comment by gberaudo** [comment]
@tsauerwein, it is easy to wrap the arrays in an object but is it worth it?
Is the issue only affecting obsolete browsers (<ES5?)? I did not find much information about which browsers were vulnerable and when it was fixed. IE9 is from 2011, several years after the disclosure.

**Comment by tsauerwein** [comment]
Like I said above:

> Though new browsers are not affected (see http://stackoverflow.com/a/16880162/119937), it would be safer simply not to return an array.

Now, it is also a question of consistency, because elsewhere we are always returning an object containing the list and not the list. It is also easier to add information to an object (like the number of entries) later on.

**Comment by gberaudo** [comment]
For the searches, we are returning objects like `{documents:[], total:int}`.

In order to make the API regular, do you think we should rename `documents` to a more generics word (`results`?). Then, for unpaginated results (like document history), should we add a `total` property with a value of `results.length`?

**Comment by asaunier** [comment]
> In order to make the API regular, do you think we should rename documents to a more generics word (results?).

I would stick to the current naming, "documents" is more explicit than "results".

> Then, for unpaginated results (like document history), should we add a total property with a value of results.length?

What's the point of adding properties we don't need? You can get this value by asking for "versions.length" for instance.

**Comment by tsauerwein** [comment]
I agree with Alex.

**Comment by gberaudo** [comment]
Well, then if I summarize the discussions:
- there is no security reason preventing to return an array;
- there is no need for a regular API but instead we should be minimal and specific.
We did not develop about extensibility.

**Comment by tsauerwein** [comment]
> there is no security reason preventing to return an array;

On old browsers returning an array is a security problem. Even though we aim for modern browsers, c2c.org could by opened with an old browser. And because it is a minimal effort not to return an array, I see no reason to return an array.

> there is no need for a regular API but instead we should be minimal and specific. We did not develop about extensibility.

The API should be consistent, but we don't have to add properties that are not needed. For example about this `total` field: For paged results the `total` field is relevant, but if you are returning all results there is no need for it.

**Comment by gberaudo** [comment]
@tsauerwein, non ES5 browsers will immediately throw.
Anyway, let's always return objects since you are more comfortable with this.

**Comment by tsauerwein** [comment]
Thanks :)
