### ISSUE TITLE
Update SMTP config

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#492]
Current SMTP server does not work for the demo server. Registering to a commercial service seems required. Once the service is set up, the config should be updated in Discourse and in the API:
https://github.com/c2corg/v6_api/blob/0d11bad2a003d20324c90f449c4c45fe3cbf8494/config/default#L64-L65

**Comment by mfournier** [comment]
I sent the details (API key, etc) to @arnaud-morvan by email yesterday evening. So we should be close to done with this issue.

**Comment by arnaud-morvan** [comment]
It seems OK for the settings, emails where sent from my workstation. I'm working problems with encoding to read mail templates files in utf-8.

**Comment by fjacon** [comment]
tested on demov6 for the creation of a new account.
Dont see any encoding problem
Something to solve yet ?

**Comment by arnaud-morvan** [comment]
Encoding problem has been fixed by https://github.com/c2corg/v6_api/pull/497/commits/355d456fb96f78f356d9eefb6d2bc0a183fdf9d6
Note that we should make a short test using this SMTP server with discourse.

**Comment by asaunier** [comment]
@arnaud-morvan Shall we close this issue? It seems the emails are sent as expected in the demo.

**Comment by stef74** [comment]
@arnaud-morvan do you close some tets confirm no issue ?

**Comment by stef74** [comment]
@arnaud-morvan work needed on this topic ?

**Comment by stef74** [comment]
fee free to reopen
