### ISSUE TITLE
Route creation: pb with 'Durée (jours)'

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_api#502]
When creating a new route, it is possible to select multiple durations while it should be forbiden (only one selection). If my recollection is correct, this bug was reported in a previous issue.
![bug duree](https://cloud.githubusercontent.com/assets/19892089/20353930/c2feccca-ac1c-11e6-8a3e-f05870f45783.jpg)

**Comment by fbunoz** [comment]
It is not a bug, it is a feature :-)

See the google doc for route fields.
