### ISSUE TITLE
Route: the field 'orientation' is not displayed 

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_api#505]
The field 'orientation' is not displayed in the route document (see: http://www.demov6.camptocamp.org/routes/822280/fr/tete-de-vauclave-essai-beta-via-ferrata). On the other hand, it is displayed in the corresponding card (see the card from the associated WP: http://www.demov6.camptocamp.org/waypoints/262930/fr/tete-de-vauclave)

**Comment by asaunier** [comment]
That looks like a UI issue, not an API one :P 
Please create the issue in https://github.com/c2corg/v6_ui/issues and close this one. Thanks :)

**Comment by desnoes** [comment]
yes, i mixed up
