### ISSUE TITLE
Restrict geometry type depending on document type

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#506]
The field `Geometry.geom_detail`is used to store tracks for routes and outings, but also to store polygons for areas. But the API would not error if you would try to store a polygon for a route (this is restricted on the UI though).

It would make sense to restrict the geometry type depending on the document type to avoid inconsistent data.

**Comment by asaunier** [comment]
An example of incorrect geometry types (waypoint stored in a route geometry): https://github.com/c2corg/v6_ui/issues/1143#issuecomment-270881720

**Comment by asaunier** [comment]
I don't think this issue can easily be tested  by the association. Then I directly close it.
Thanks for the fix :)
