### ISSUE TITLE
Convert bbcode tags to Markdown

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#516]
Transfered from https://github.com/c2corg/v6_api/issues/417

See also https://github.com/c2corg/v6_ui/issues/131#issuecomment-256396802

**Comment by asaunier** [comment]
This issue cannot be set to milestone 6.1: it has to be done during the migration (or dropped).

**Comment by stef74** [comment]
probaly dropped ...

**Comment by asaunier** [comment]
OK
