### ISSUE TITLE
Search pertinency

### ISSUE THREAD

**Issue by stef74** [c2corg/v6_api#519]
If you serach "source petzl" on article ... you have 731 result vs 29 on v5 
I don't say I want to see only 29 ... but not 700 !

**Comment by asaunier** [comment]
Perhaps a duplicate of https://github.com/c2corg/v6_api/issues/206 ?

**Comment by stef74** [comment]
#397 is on demo ... so I complete the #206

**Comment by tsauerwein** [comment]
Example added to https://github.com/c2corg/v6_api/issues/397
