### ISSUE TITLE
Missing an article category

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#523]
The article categories was based on a old V5 dump.
Since 19 january 2016, the 'gear_and_technique' category has been splitted into 'gear' and 'technical'.
We must update the migration and API code to be consistent withe the last version of the V5.

To do this, I made 2 pull requests : 
- migration : https://github.com/c2corg/v6_api/pull/522
- category list : https://github.com/c2corg/v6_common/pull/45

This changes have not been tested.

**Comment by asaunier** [comment]
Don't forget to make the required changes in the UI as well, see https://github.com/c2corg/v6_common/pull/45#issuecomment-262362339

Your PRs cannot be merged unless the UI PR is provided as well.

**Comment by asaunier** [comment]
Tagging this issue as blocking since it must be addressed before the migration.
