### ISSUE TITLE
Simplify route and outing geometries

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#529]
From https://github.com/c2corg/v6_api/issues/489#issuecomment-262524104

- During the migration simplify the geometries for outings and routes.
- If a new geometry is set on an outing or route, store a simplified geometry.

Geometries are already simplified on the client-side before being sent to the API, so the 2nd part is not that critical for the Go Live.

**Comment by asaunier** [comment]
Example of big route geometry:
http://www.camptocamp.org/routes/211687/fr/mont-de-grange-traversee-bel-air-coicon
The GPX file available on v5 is > 800 kB!
