### ISSUE TITLE
Rename "reports" to "xreports"?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#539]
In v6 the accident reports are known as "reports":
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/report.py
whereas in v5 they were "xreports".

I do think they should remain "xreports", mainly because it would avoid having to redirects all v5 UI "xreports" URLs to "reports" in v6. Is there a reason to make such a change in v6?
See https://github.com/c2corg/v6_ui/pull/905#issuecomment-262858171

I tag this issue blocking because it would probably be more work to do the change after the migration.

**Comment by tsauerwein** [comment]
Yes, this would make sense.

**Comment by dkocich** [comment]
I adapted also UI part to https://github.com/c2corg/v6_ui/pull/905 .
Maybe feel free to close (after some test full migration)? Partial migration only of xreports worked fine.
