### ISSUE TITLE
Bad default value for WP activities

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#55]
Not sure if this is a bug in the API or misformed data on the UI side:

In the WP editing form, no "activities" field is available (yet?). If I edit an existing WP (the form model gets the WP model from the API), an "activities" attributes is available in the model with value "null". Then when I post the model to the API I get the following validation error:

> description: ""None" is not iterable"
location: "body"
name: "document.activities"

**Comment by tsauerwein** [comment]
This seems to be a problem in Cornice, see https://github.com/mozilla-services/cornice/pull/342

**Comment by asaunier** [comment]
Is this issue still valid? The PR in Cornice has been merged and WP no longer have the "activities" attribute.

**Comment by tsauerwein** [comment]
I will have to test if the problem still exists for routes.

**Comment by gberaudo** [comment]
See #146 which migrates to Cornice 1.2.0.

**Comment by asaunier** [comment]
Is this issue still valid?

**Comment by tsauerwein** [comment]
Yes, this is still an issue: https://github.com/mozilla-services/cornice/issues/349
