### ISSUE TITLE
Duplicated login_name in V5 database

### ISSUE THREAD

**Issue by arnaud-morvan** [c2corg/v6_api#552]
We have 24 duplicated logins in V5 database:
```
SELECT login_name, count(*)
FROM app_users_private_data
GROUP BY login_name
HAVING count(*) > 1
```
returns 24 lines.

I don't understand why we do get this error before.

**Comment by arnaud-morvan** [comment]
For a complete list:
```
SELECT *
FROM
(
SELECT
  id,
  username,
  login_name,
  email,
  to_timestamp(registered),
  count(id) OVER (PARTITION BY login_name) as count
FROM app_users_private_data
) AS test
WHERE count > 1
ORDER BY login_name
```

**Comment by arnaud-morvan** [comment]
Maybe some users have changed their login instead of forum_username.

**Comment by arnaud-morvan** [comment]
To be able to run then topoguide migration, I've overwritten the login_name with username for thoses lines:
```
UPDATE app_users_private_data
SET login_name = username
FROM (
  SELECT
    id,
    count(id) OVER (PARTITION BY login_name) as count
  FROM app_users_private_data
) AS duplicates
WHERE duplicates.id = app_users_private_data.id;
```
And it seems to make sense regarding the result of the preceding query (with ``PARTITION``).

**Comment by asaunier** [comment]
> Maybe some users have changed their login instead of forum_username.

Not possible in v5 (nor in v6).
All duplicates are older then 2002.

**Comment by asaunier** [comment]
All duplicates have been handled in the v5 prod database. The next nightly backup will be OK.
