### ISSUE TITLE
No stable pwd with some IDs, eMail pb ?

### ISSUE THREAD

**Issue by HSERGERAERT** [c2corg/v6_api#553]
It's not possible to have a stable connexion with the user ID ThomasR.
There is always a "Login Fail" even after a renew of the password.

I made a test and I have a strange feeling I would like to share...

1. I was first disconnected.
2. I tried to connect ThomasR ID with the given pwd : "login failed".
3. I asked the renew of the password but **I filled my eMail address** instead of the eMail of ThomasR. I was really surprised that I can put my eMail address to change a pwd of an ID which is not mine... hum...
4. I have got an eMail (perfect) with a link to reset the password. 
5. I did it. The system never asked me which ID is concerned by the change
6. I tried to connect ThomasR ID, "login failed"
7. I trie

d to connect my ID herve74, possible with the new pwd

I recognize that when we set an eMail address to change a pwd then the system checks if there is an ID with this pwd, if yes then an eMail is sent. By clicking on the hyperlink of the eMail we can reset a pwd, but of the ID identified by the system.

How the system can manage correctly the situation if there are more than two ID with the same eMail address.

ThomasR and Olivier-C are in the same situation.
If the root cause of the trouble is correct then this would be a blocking bug.

**Comment by asaunier** [comment]
I don't see the problem. If you have provided your email address, you have reset the password for your own account (linked to the email addressed you have provided), not ThomasR's.

**Comment by HSERGERAERT** [comment]
So why ThomasR can change his pwd but afterwards , on a second connexion,
he get the same error that login failed ?

Le mar. 29 nov. 2016 à 22:57, Alex Saunier <notifications@github.com> a
écrit :

I don't see the problem. If you have provided your email address, you have
reset the password for your own account (linked to the email addressed you
have provided), not ThomasR's.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/c2corg/v6_api/issues/553#issuecomment-263712633>, or mute
the thread

**Comment by asaunier** [comment]
> So why ThomasR can change his pwd but afterwards , on a second connexion,
he get the same error that login failed ?

No idea. But is there really a connection with the procedure you describe?

I have just tried to reset my password on demov6 and had no problem to log in with my new password. Including on another browser.

Could Thomas describe what he did and give us the login and password he uses. No need to provide us his real password but at least a password that can be used to reproduce the problem. For his login I can find it in the database if he prefers not to make it public here.

**Comment by HSERGERAERT** [comment]
I also changed my pwd w/o problem. I can only recognize that 2 users Olivier-C and ThomasR have the same issue, which looks like a problem somewhere.
Do you have the possibility on the demov6 to change the eMail of ThomasR and put mine herve.sergeraert@gmail.com ? this one is not used in any IDs.
Then I will be able to test the ThomasR ID... I will set back his eMail afterwards.

**Comment by tsauerwein** [comment]
> I asked the renew of the password but I filled my eMail address instead of the eMail of ThomasR. I was really surprised that I can put my eMail address **to change a pwd of an ID** which is not mine... hum...

Email addresses are unique, so you don't have to provide the username. If you provide your email, you are changing the password of your account.

**Comment by asaunier** [comment]
I don't know the passwords of ThomasR and Olivier C. (they are encrypted in the database) so I have changed them by hand to "toto" on the dev instance (http://c2corgv6.demo-camptocamp.com/).

No problem then to authenticate as their users on the dev demo (I have found their usernames in the database). There is no duplicate with their usernames.

I have not been able to test on the actual demov6 instance (no access).

**Comment by asaunier** [comment]
To investigate this issue we need to have more information on how to reproduce it => please provide user ids, logins and passwords (at least email me those data).

**Comment by asaunier** [comment]
I suspect a case problem: in the dev v6 database. Thomas and Olivier have lowercased usernames (logins). If I try to authenticated with the same logins but not the same case, the auth fails.

**Comment by HSERGERAERT** [comment]
I have tested with ThomasR et toto, same issue "login failed"

**Comment by asaunier** [comment]
Thomas's login is actually "thomasr", not "ThomasR".

**Comment by HSERGERAERT** [comment]
Request sent to Thomas to have  a screenshot of his account on v5

**Comment by HSERGERAERT** [comment]
**ThomasR** has confirmed, his user ID is **thomasr** instead of ThomasR.
That's the matter, v6 is case sensitive for the ID, not the v5
I will ask for a communication to contributors.
I close the item

**Comment by fbunoz** [comment]
The login doesn't work anymore for my account.
I must use my forum name instead of my login to log in my account.

**Comment by asaunier** [comment]
@fbunoz Thanks for reporting. Changes are  in progress to fix the problem.
