### ISSUE TITLE
A new version is created even if we do no change

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#574]
I created an outing, and I modify it.
After, I just edit it and save it without no change in the edit form.
But a new version has ben created.
The diff displays only one field: the geometry, which shows no change: 
https://www.demov6.camptocamp.org/outings/diff/828230/fr/1305281/1305282
Same problem on a route: https://www.demov6.camptocamp.org/routes/diff/807540/fr/1271704/1305287
Then, for a multi-language doc (FR+ES for instance), any text change in FR create a new version in ES: http://www.demov6.camptocamp.org/routes/diff/807540/es/1305286/1305290

There was the same problem on the V5, but only with routes having a GPX track (and articles).
With the increasing of a number of multi-language docs, there are more and more dummy versions which are created.

**Comment by cbeauchesne** [comment]
It's now fixed by removing the automatic calculation of geoloc from associated waypoints
