### ISSUE TITLE
Advanced-search fails if offset is too big

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#578]
When making a request to an advanced-search view with an offset > 10000 (for [example](http://localhost:6544/routes?bbox=457507%252C5594424%252C559627%252C5730176&offset=30000)), ElasticSearch complains:

> Result window is too large, from + size must be less than or equal to: [10000] but was [30030]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.

A simple solution could be to hide the "go to last page" button in the UI, because it does not really make sense to flip through thousand of pages.

**Comment by asaunier** [comment]
> A simple solution could be to hide the "go to last page" button in the UI, because it does not really make sense to flip through thousand of pages.

@tsauerwein Can we close the issue? I think the solution you have suggested above has been implemented in the UI.
