### ISSUE TITLE
Duplicated routes and outings in the lists on a waypoint page

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#589]
- [ ] If a route is associated to several sub-waypoints of the same over-waypoint (or associated to over-waypoint + sub-waypoint), it appears several times in the route list on the over-waypoint page.
The sub-waypoint routes must appear, but the duplicated results returned by the BD request must be removed (or maybe the BD can do this ?).
- [ ] If an outing is associated to several routes of the same waypoint, it appears several times in the outing list on the waypoint page.

**Comment by fbunoz** [comment]
Another issue exist in the UI (but it is an API issue) : https://github.com/c2corg/v6_ui/issues/1213

**Comment by asaunier** [comment]
Another example: https://forum.camptocamp.org/t/les-deux-soeurs-en-doublon/192884

**Comment by brunobesson** [comment]
Fixed by #1022 and #1019

**Comment by brunobesson** [comment]
Fixed.
