### ISSUE TITLE
Associated images sorting

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#596]
As for now, it seems that the images listed in the a document's ``associations`` attribute are id-sorted. It would make more sense to **have them chronologically sorted using the EXIF date** info if available.

This is especially useful for outings to make sure associated images are shown in the order they have been taken. Which is not the case currently if several people upload there images or if a contributor uploads their image in whatever order (for instance when an upload has failed).

**Comment by dkocich** [comment]
Related to UI issue https://github.com/c2corg/v6_ui/issues/1177

**Comment by dkocich** [comment]
Note - Currently, there are around 150 images in DB which have bad `date_time` set (it is between years 4500 and 2017)...

**Comment by desnoes** [comment]
fixed on demo
