### ISSUE TITLE
The EXIF date and time are not used when uploading an image

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#599]
Moved from https://github.com/c2corg/v6_images/issues/34

@fbunoz reported that

When we upload an image, the date and time should be extracted from Exif data.
But it is not the case : 

- [ ] The date/time extracted is not the Exif date, but the last edit date of the JPG file !
- [x] Only the date is extracted, and not the time. See also : https://github.com/c2corg/v6_ui/issues/1176

Ex 1 : https://www.camptocamp.org/images/839307/fr/des-beaux-piliers-au-soleil-rasant

- Photo taken the 31 dec 2016 (visible in the Exif of original image).
- Uploaded to the PC the 1st jan 2017.
- Edited on the PC the 7 jan 2017, to resize and fix the colors.

The displayed date is the 7 jan 2017, there is no time displayed, and the API returns 00:00:00 as time.

Ex 2 : https://www.camptocamp.org/images/839208/fr/pour-amoureux-des-vieilles-pierres

- Photo taken the 30 dec 2016 (visible in the Exif of original image).
- Uploaded to a PC the 1st jan 2017.
- Edited on the PC to be rotated.
- Uploaded to c2c the 6 jan 2017. 

The displayed date is 1st jan 2017. There is no time (the API returns 00:00:00 as time, instead of 09:53:03).

Ex 3 : https://www.camptocamp.org/images/839207/fr/encore-debout

- Photo taken the 30 dec 2016 (visible in the Exif of original image).
- Uploaded to a PC the 1st jan 2017.
- Uploaded to c2c the 6 jan 2017, without change since the upload to the PC.

The displayed date is 30 dec 2016. There is no time.

After fixing the bug, we'll need run a script to fix the date/time of all images uploaded in the V6 by extracting the right value from exif.
This concerns all images with an ID equal or higher than https://api.camptocamp.org/images/828237

**Comment by asaunier** [comment]
This seems to be an API issue because when saving an uploaded image to the API the datetime is actually provided by the UI:

![capture du 2017-01-10 15-14-50](https://cloud.githubusercontent.com/assets/1192331/21809343/9109e49c-d747-11e6-8167-de28a7e7b8e1.png)

**Comment by tsauerwein** [comment]
I am not sure why all the exif data is thrown at the API. The API only considers the fields defined in the [model](https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/image.py#L29). The `date_time` field only contains the date, see for [example](https://github.com/c2corg/v6_api/issues/600#issuecomment-273224256).

This is a UI issue setting the field correctly: https://github.com/c2corg/v6_ui/blob/ab1514dc90c4ecf6395faa0326a03e1f18fdbb80/c2corg_ui/static/js/editing/imageediting.js#L67

**Comment by tsauerwein** [comment]
Closing because this was a UI issue (https://github.com/c2corg/v6_ui/issues/1176)
