### ISSUE TITLE
Server caching

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#6]
Caching the output of some of the API actions would be relevant to increase the performances of the API. Using dogpile for instance.

I don't think caching the list output is relevant because new items are often added. On the other hand existing documents do not change every day: it's probably a good idea to cache the "get" output (perhaps the history as well).

**Comment by asaunier** [comment]
We need to pay attention that we have many documents available and that caching all of them might take quite a lot of space (in v5 the symfony cache grows really big).
We will probably also use Varnish in front of the API.

**Comment by mfournier** [comment]
One big issue we have with the current cache implementation is the overhead of using the filesystem. Dazillions of small files and directories hurt performance and are a nightmare to handle in production.

According to the doc, dogpile offers configurable cache backends, redis and memcached among others, which won't suffer from this problem. So it at least offers the flexibility we lack currently.

Regarding caching elements or not, IMHO the question to ask is not if the element is frequently changed or not but rather what is the cost of computing this piece of data.

Thinking this way you don't need to worry about the dilemma of which TTL to set on cached objects, but rather on an efficient strategy to purge or update outdated cached data (or change the identifier and let the LRU get rid of them).

HTH

**Comment by tsauerwein** [comment]
> Regarding caching elements or not, IMHO the question to ask is not if the element is frequently changed or not but rather what is the cost of computing this piece of data. 

> Thinking this way you don't need to worry about the dilemma of which TTL to set on cached objects, but rather on an efficient strategy to purge or update outdated cached data (or change the identifier and let the LRU get rid of them).

Good point!

**Comment by asaunier** [comment]
Should we have server caching both in the API app and in the UI app?

Having server caching in the API would make sense because it might be accessed by several clients (UI as well as mobile apps, etc.).

On the other hand, the UI pages will probably be server-cached as well.
It means that when a change is done, the cache should be invalidated both in the UI and in the API.

What about using Varnish in front of the API instead of using some server caching? How to make Varnish know that a document has changed?

**Comment by asaunier** [comment]
Some precisions from @mfournier 

>There's 2 levels of caching here (in-app using dogpile, and at the
http-level using http-protocol mechanisms). I think we should use both for
both services.

>You shouldn't look too much at the varnish config from v5 for inspiration.
This was slapped onto the system several years after it's inception, partly
to decrease the number of apache workers by serving static content directly
from the cache, and partly to work around perf issues we weren't able to
fix in the code (slow queries generated from the ORM) on highly requested
pages. A lot of legacy for which we have the opportunity to get rid of now.

>It's much better to make the application behave in a cache-friendly manner
(mostly by emitting sensible cache-related HTTP headers), as this will work
seamlessly on browsers caches. Varnish should indeed be considered as a
centralized remote browser cache:
 - out of reach (no purging possible)
 - the applications should not rely on varnish, they should behave the same
   with or without.

>Rules of thumb:
 - only GET/HEAD requests get cached
 - only response codes 20x and 30x get cached
 - only elements without cookies get cached
 - if an element should be cached, but can be invalidated at any time: add
   cache-friendly headers with a high TTL but version the object
   /my/blob.js?v=1234 -> /my/blob.js?v=5678
 - if an element can be cached for a predictable amount of time, add
   cache-friendly headers with a reasonable TTL. nb: 5 seconds would be a
   perfectly acceptable TTL, to make sure the REST endpoints don't get hit
   too hard by a flood of requests, while serving a reasonably up to date
   version to users.
 - if an element should not be cached, add cache-hostile headers (but avoid
   doing this by default, I'll git blame the code and will chase the
   culprit with a stick ;)
 - if the content of an element changes depending on the the browser's
   Accept-Encoding, Accept-Language or User-Agent, these fields should be
   normalized (varnish may do that) and the app should set the Vary header
   accordingly.

>As for dogpile, I'd favor redis over memcached as a backend for production,
for a couple of reasons:
 - redis can overflow to disk, the hottest elements staying mmap()ed
 - redis has effective mechanisms to selectively purge elements and keep
   others.
 - redis has much better instrumentation, making it a piece of cake to
   monitor & diagnose cache-related issues.

**Comment by asaunier** [comment]
Make sure the app does not crash when the cache is full (as in v5 - uses a filesystem based cache) => cache should be able to drop old elements when there is too many items to store.

**Comment by asaunier** [comment]
Probably a task we should not delay too much since it may impact many functionalities?!

**Comment by asaunier** [comment]
@tsauerwein can this issue be closed?

**Comment by tsauerwein** [comment]
Setting up Varnish hasn't been done yet. A basic configuration is in https://github.com/c2corg/v6_api/tree/varnish-caching

**Comment by cbeauchesne** [comment]
As I understand the actual state, we can close this issue .
