### ISSUE TITLE
Service listing all recent changes

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#605]
See the UI issue at https://github.com/c2corg/v6_ui/issues/1323

**Comment by tsauerwein** [comment]
What data would be required?

| Time | User | Type | Titel | Changed Locales |
| ------- | ----- |------- | ------ | --------------------- |
| 21/12/2016 00:35:04 | [Frédéric Bunoz](https://www.camptocamp.org/profiles/288) | waypoint | [Mont Blanc](https://www.camptocamp.org/waypoints/37355/fr/mont-blanc) | [fr](https://www.camptocamp.org/waypoints/history/37355/fr) - [en](https://www.camptocamp.org/waypoints/history/37355/en) |

For a table like this, the following data would be needed:

```
{
  "changes": [{
      "user": {
        "user_id": "...",
        "name": "...",
        ...
      },
      "comment": "...",
      "written_at": "...",
      "document": {
        "document_id": "...",
        "title": "...",
        "title_prefix": "...",
        "lang": "..."
      },
      "changed_langs": ["en", "fr"]
    }, ...
  ],
  pagination_token": "..."
}
```

**Comment by asaunier** [comment]
@stef74 What do you think?

**Comment by celinestern** [comment]
In V5 (http://www.pre-prod.dev.camptocamp.org/routes/whatsnew) we had:
Nom	Date	Auteur	Nature de la révision	Commentaire

Same data in V6 should be ok

**Comment by stef74** [comment]
@asaunier ok with your proposal (as in v5), confirmed by @celinestern

**Comment by stef74** [comment]
@fjacon why extra ?
