### ISSUE TITLE
'access' field for huts is not returned

### ISSUE THREAD

**Issue by brunobesson** [c2corg/v6_api#611]
See e.g. https://api.camptocamp.org/waypoints/104105
I have no access to the database, but I know the access field was filled in on v5, and it's supposedly migrated. In c2corg/v6_ui#1401, I can submit the 'access' field when editing a hut. I don't know if it is taken into account, at least the API doesn't complain. But the field is not returned either.

**Comment by tsauerwein** [comment]
It seems `locales.access` is missing for type `hut`: https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_waypoint.py#L138-L150

**Comment by brunobesson** [comment]
@tsauerwein this would be enough to solve this issue?
If it is that simple, could it be done, so that we can go forward with c2corg/v6_ui#1401

**Comment by desnoes** [comment]
@brunobesson: could you please test ? i don't knwo exactly the purpose of this issue.

**Comment by brunobesson** [comment]
Fixed.
