### ISSUE TITLE
Sequence problem with documents_locales.document_id?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#62]
Not sure if this is a significant problem but I read in the logs that:

> [Wed Nov 04 20:58:07.934469 2015] [wsgi:error] [pid 30447] /var/www/vhosts/c2cassoc_c2corgv6/private/v6_api/.build/venv/lib/python2.7/site-packages/sqlalchemy/sql/default_comparator.py:153: SAWarning: The IN-predicate on "documents_locales.document_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.

It seems not systematic, but showed from time to time (when trying to display a document on the main dev instance).

**Comment by tsauerwein** [comment]
The warning now also shows up when running the tests, which makes it easier to track down.

**Comment by tsauerwein** [comment]
@gberaudo I think you fixed this, right?

**Comment by gberaudo** [comment]
Yes, closing.
