### ISSUE TITLE
Whatsnew feed returns unwanted data

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#625]
* [x] User creations are reported => we don't want this.
* [x] The total number of feed elements are returned with every API requests, which is useless. Only once is useful (when there is no token?). Perhaps it would be simpler not to provide this info. See https://github.com/c2corg/v6_api/blob/e62ee25aac632b7abff648b56482df7ffc1f256b/c2corg_api/views/document_changes.py#L76-L81

Related to https://github.com/c2corg/v6_api/issues/605 and https://github.com/c2corg/v6_api/pull/620

**Comment by asaunier** [comment]
Perhaps we don't need outings changes either (only collaborative doc changes?)?
@desnoes @stef74 @celinestern @loicperrin @fbunoz What do you think?

**Comment by desnoes** [comment]
@asaunier : if it is realated to the latest changes, only collaborative doc are interesting => don't need outings changes.

**Comment by asaunier** [comment]
@dkocich I see you have checked the todo list items above, but I see no related PR?
