### ISSUE TITLE
Image : using EXIF creation date/time instead of last change date/time

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#627]
For now, the date/time extracted from a photo to fill the date/time field of the image doc, is the last photo change date/time.
Ex : the date time of [this photo](https://www.camptocamp.org/images/852016/fr/versant-w) is 13/02/2017 23:14:47 in the doc, whereas it is 2017-02-12 10:49:14 in the EXIF.
13/02/2017 23:14:47 is the date/time of the last change.

When this bug will be fixed, all images with an ID >= 828237 will have to be corrected by a script. See https://github.com/c2corg/v6_ui/issues/1419

**Comment by tsauerwein** [comment]
This is more a UI issue as the EXIF extraction is done on the client-side.

**Comment by desnoes** [comment]
@fbunoz : could you test ?

**Comment by fbunoz** [comment]
It is correct with this photo : http://www.demov6.camptocamp.org/images/828467/fr/ca-penche
Thanks !
To be tested on IE, Safari, ...

**Comment by desnoes** [comment]
tested on Edge => it's ok

**Comment by desnoes** [comment]
@stef74 : could ypu test on Safari ?

**Comment by fbunoz** [comment]
I close the issue because it works with 2 browsers, and the associated PR is in prod.
A new issue will be open if there is a bug with another browser.
