### ISSUE TITLE
SSL error when uploading images on the demo

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#637]
(perhaps only a setting issue with the demo, not impacting the prod?)

When uploading an image on the demo, the file is actually saved on the image backend. But when trying to confirm the image document to the API, the latter returns the following error:

![sans titre](https://cloud.githubusercontent.com/assets/1192331/23169603/ae75fc8e-f84c-11e6-8395-bafea4578460.png)

Not sure where to find the logs, but in my instance (using the same images backend), the API logs report that
```
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
2017-02-21 12:29:39,817 INFO  [c2corg_api.search.notify_sync][waitress] Notifying ElasticSearch syncer
```

@mfournier would you know what's happening?

**Comment by asaunier** [comment]
@mfournier Do you have any idea how we could fix this problem? Thanks!

**Comment by dkocich** [comment]
Note - I think that problem can be with `requests` package which is in version `2.11.1` but I am unable to test it on a demo... According to [requests documentation](https://pypi.python.org/pypi/requests/) there were some changes to the latest versions which can be possibly connected with this SSL error (_2.12.1 - change of PyOpenSSL backend in urllib3_).

**Comment by asaunier** [comment]
> problem can be with requests package which is in version 2.11.1

That's a possibility.
But I think we already had the problem on the demo with the previous release which is now in production. But uploading images seems to still work in production. So it's probably rather an instance related problem.

**Comment by arnaud-morvan** [comment]
I've removed https from internal urls on the demo, it is now possible to save images in the API.
