### ISSUE TITLE
TypeError: to_archive() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#64]
When trying to update a waypoint in the UI, the API fails with the following error:
>  File "/home/alex/v6_api/c2corg_api/views/waypoint.py", line 57, in put
    return self._put(Waypoint, schema_waypoint)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 86, in _put
    changed_langs)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 154, in _update_version
    locale_archive = self._get_locale_archive(locale, changed_langs)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 215, in _get_locale_archive
    locale_archive = locale.to_archive()
TypeError: to_archive() takes exactly 2 arguments (1 given)

Line 215 is
```
        if locale.culture in changed_langs:
            # create new archive version for this locale
            locale_archive = locale.to_archive()
```
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document.py#L213-L215
whereas DocumentLocale.to_locale() indeed requires a "locale" argument:
```
    def to_archive(self, locale):
        copy_attributes(self, locale, DocumentLocale._ATTRIBUTES)
        return locale
```
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L236-L238

**Comment by asaunier** [comment]
Updating a figure only (elevation) actually works but any change in the locale attributes causes a crash.

**Comment by asaunier** [comment]
Actually making changes in the locale works if the document has been created in v6. For instance: http://c2corgv6-demo.gis.internal:6555/waypoints/642980/fr

But it fails with an imported waypoints. For instance:
http://c2corgv6-demo.gis.internal:6555/waypoints/37203/fr

Most likely there is something wrong with the imported data (archive? history?).

**Comment by tsauerwein** [comment]
I think I know what's wrong. Will work on a fix.
