### ISSUE TITLE
Delete a locale from a document

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#645]
Note:
* check if the locale to delete is the only one available => if yes, delete the whole document (with the same constraints and effects as the "delete document" tool) => use the standard deleting tool
* if other locales are available => only remove the given locale (+ archived version of the locale and history metadata)

**Comment by desnoes** [comment]
It seems it is not possible to deletec more than one linguistic version of a document.
Cf. experiment detailed in https://github.com/c2corg/v6_ui/issues/1555
