### ISSUE TITLE
Locales should be created with their own HistoryMetadata

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#649]
I have noticed a problem/bug with function ``DocumentRest.create_new_version()`` defined at
https://github.com/c2corg/v6_api/blob/8091cc20a144f4f71fe7bf93623f0751608ec832/c2corg_api/views/document.py#L364

It used to create the ``DocumentVersion`` and ``HistoryMetadata`` entries
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document_history.py
when creating a new document:
https://github.com/c2corg/v6_api/blob/8091cc20a144f4f71fe7bf93623f0751608ec832/c2corg_api/views/document.py#L191-L203
as well as to build test data in the various unit tests:
https://github.com/c2corg/v6_api/search?q=create_new_version&type=&utf8=%E2%9C%93

A call to this function creates a single ``HistoryMetadata`` object that is shared by all locales of the document to create:
https://github.com/c2corg/v6_api/blob/8091cc20a144f4f71fe7bf93623f0751608ec832/c2corg_api/views/document.py#L370-L381

This is not really a problem in "real life" because locales for the same document are never created at the same time.

But this causes tests for the locale deleting tool (see https://github.com/c2corg/v6_api/pull/648) to fail because the removed ``HistoryMetadata`` was also used by some other locale created at the same time.

``DocumentRest.create_new_version()`` should be modified to make sure distinct ``HistoryMetadata`` objects are used for all locales.

**Comment by asaunier** [comment]
I have tried to change the function in order to make sure every a distinct ``HistoryMetadata`` is created for every locale but with no success. ``make check`` always remains blocked because
```
..............................E..............................................................E/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/scoping.py:106: SAWarning: At least one scoped session is already present.  configure() can not affect sessions that have already been created.
  warn('At least one scoped session is already present. '
```

**Comment by arnaud-morvan** [comment]
HistoryMetadata should not be made to support deletion. Versionning, in a general manner, do not support deletion on the backend side.
On another side, attaching HistoryMetadata to document locale will be a huge modification.
Have you considered to create a new HistoryMetadata (instead of deleting one) when the considered lang is deleted ?

**Comment by tsauerwein** [comment]
> But this causes tests for the locale deleting tool (see #648) to fail because the removed HistoryMetadata was also used by some other locale created at the same time.

Why are you deleting the `HistoryMetaData` entity if it is still used by other `DocumentVersion` entities?

The history metadata is the same for the versions of all locales, so there is no need to create distinct entities. In my opinion the problem is that you are trying to delete it if it is still used.

**Comment by asaunier** [comment]
> HistoryMetadata should not be made to support deletion. Versionning, in a general manner, do not support deletion on the backend side.

That's what we do when deleting the whole document (already implemented). I think it makes sense to remove all document data (including ``HistoryMetadata`` and ``DocumentVersion``) when deleting a document or a locale only. Anyway I think the foreign keys constraints make it mandatory.

> Why are you deleting the HistoryMetaData entity if it is still used by other DocumentVersion entities?
> The history metadata is the same for the versions of all locales

Are you sure of this? When you create or edit a document for real, only one locale is edited/created at a time, isn't it? So HistoryMetaData items are not shared among locales. Only in the tests because we set several locales by hand (which is not possible with the UI) and use ``DocumentRest.create_new_version()`` to save those locales (and create a single HistoryMetaData).

> the problem is that you are trying to delete it if it is still used.

Mmmm. I could test if the  HistoryMetaData is used by some other locale before deleting it but that will probably make the code more complicated and not match to a real use case (?). I will try. Thanks!

**Comment by tsauerwein** [comment]
> When you create or edit a document for real, only one locale is edited/created at a time, isn't it? So HistoryMetaData items are not shared among locales.

When you edit the figures of a document, a new version is created for all locales (using the same history metadata).

**Comment by asaunier** [comment]
> When you edit the figures of a document, a new version is created for all locales (using the same history metadata).

OK. Then I have no choice :P Closing the issue.
