### ISSUE TITLE
having public_transport field in response of /outings service

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_api#667]
Regarding this request : 
https://forum.camptocamp.org/t/v6-faites-evoluer-la-maquette-avec-nous/183795/370

It may be quite simple, but I would like to know if there is any opposition before proposing a PR.

**Comment by brunobesson** [comment]
No opposition, this field should be pretty straightforward to include and shouldn't bring any additional cost.

**Comment by cbeauchesne** [comment]
Done by @brunobesson
