### ISSUE TITLE
When a doc has been protected, then unprotected, a change return an error

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#668]
When a doc is protected (for modo only), or has been protected and unprotected (for all identified user), a change of the text only return an error : "unexpexted error, please consult server log".
But if we change a numeric value only, or text + numeric, it works.
After a successfull change (num or text + num), a change of text only works without error.

You can test on this doc which has been protected and unprotected : http://www.demov6.camptocamp.org/waypoints/44067/fr/col-de-la-vache-bleue

**Comment by asaunier** [comment]
I close this issue because a duplicate has been created in the meantime, see https://github.com/c2corg/v6_api/issues/692
