### ISSUE TITLE
Support document changes reverting

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#670]
Related to https://github.com/c2corg/v6_ui/issues/1068
The UI PR is https://github.com/c2corg/v6_ui/pull/1101

Problems we have when editing an archived version of a document (to revert to this archived version or use it as base for new changes):
* [ ] the API returns a version conflict when the UI sends the versions of an edited archived version. For instance:
> Conflict : version of locale 'fr' has changed
* [ ] associations are not managed when editing an archived version and are not passed within the editing request to the API. It seems the API requires this attribute for routes and outings. For instance when editing a route:
> associations.waypoints : at least one waypoint required

**Comment by asaunier** [comment]
>  the API returns a version conflict when the UI sends the versions of an edited archived version. For instance

The API indeed checks that the versions (of the geometry, locales and figures data) match the current versions of the document and throw a "Conflict" error if not:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/waypoint.py#L217-L219
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/document.py#L246

A possibility would be to disable this check for moderators and restrict the revert tool to moderators (which would by the way avoid the UI problems described at https://github.com/c2corg/v6_ui/pull/1101#issuecomment-303716041).

@tsauerwein Do you think skipping the version checks for moderators would cause problems? I guess that for instance if a moderator makes a standard edition at the same time than another user, the conflict with the latter user's changes will not be reported and those changes will be silently be archived.

Another option would be to provide the current document versions (as well as the current ``protected`` attribute and perhaps the associated users or author id? see https://github.com/c2corg/v6_ui/pull/1101#issuecomment-303688922) in addition to the ``previous_version_id``, ``next_version_id`` and ``version`` attributes provided as well as the standard ``document`` object. See for instance:
https://api.camptocamp.org/routes/46867/fr/334485

Of course the latter approach requires more work, in the API as well as in the UI, even though the results might be cleaner.

**Comment by asaunier** [comment]
> associations are not managed when editing an archived version and are not passed within the editing request to the API. It seems the API requires this attribute for routes and outings. For instance when editing a route

For instance when route editing request is sent, the API validates the change against some criterias, including associated waypoints, see ``validate_required_associations``:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/route.py#L124
https://github.com/c2corg/v6_api/blob/master/c2corg_api/views/route.py#L69-L82

2 possible approaches:

1. we pass a ``revert: true`` attribute to the request and bypass ``validate_required_associations`` (only for moderators??) for routes and outings

2. we actually pass the associations in the request. Problem: associations are not available when editing an archived version of a document => we must then get the associations when filling the archive editing form (as when editing the last version).
Please note that we should get the current associations, not the one at the time of the edited archive.
We might get an error if the ``main_waypoint_id`` attribute of edited route archive is no longer contained in the list of associated waypoints?!

**Comment by asaunier** [comment]
Another approach I have thought of:

instead of allowing to edit an archive version of a document (as in v5 and as proposed in PR https://github.com/c2corg/v6_ui/pull/1101) we could simply display a "restore this version" button in the archived doc view page (and in the history page?) - probably only to the moderators.

This button would request an API webservice that would copy the selected version as the new version of the document (versions in between would still be available in the history). Then no need to pass associations or check versions (only to check the requestor is a moderator?).

If further changes are required on the restored version, the user will have to open the editing page as usual.

**Comment by tsauerwein** [comment]
How should the reverting work?

If you have version 1, 2, 3, and 4 of a document and you revert to 3, do you end up with 1, 2, 3, 4, 3' or 1, 2, 3 ?

If the idea is 1, 2, 3, 4, 3', this sounds good to me:

> Another option would be to provide the current document versions

**Comment by asaunier** [comment]
> How should the reverting work?

Reverting means a new version is created using an archived versions in the editing form instead of the last version. No version is removed.

If you have version 1, 2, 3, and 4 of a document and you revert to 3, you end up with 1, 2, 3, 4, 3'

> If the idea is 1, 2, 3, 4, 3', this sounds good to me:

OK thanks! That's indeed the cleanest solution. My concern is that it might involve quite a lot of work left to pass all the required additional data along with the archived doc data whereas reverting versions is not that common.

I have the feeling that the last approach https://github.com/c2corg/v6_api/issues/670#issuecomment-303770491 could be an acceptable solution and probably simpler.

**Comment by tsauerwein** [comment]
> I have the feeling that the last approach #670 (comment) could be an acceptable solution and probably simpler.

Sorry, I didn't read all comments. But having a separate web-service only for reverting would indeed be cleaner. Good idea!

**Comment by asaunier** [comment]
@desnoes has confirmed this proposal is OK:
> we could simply display a "restore this version" button in the archived doc view page (and in the history page?) - probably only to the moderators.
This button would request an API webservice that would copy the selected version as the new version of the document (versions in between would still be available in the history).
