### ISSUE TITLE
log in with email instead of account name

### ISSUE THREAD

**Issue by Courgetteandratatouille** [c2corg/v6_api#677]
For some people its difficult to log in on the app (and probably on the website)

A good thing to do i guess, it's add the support of email instead of account name when authentificate. It's more naturel for most people.

**Comment by asaunier** [comment]
What happens when people no longer have access to their email address?
Why is it more natural to use an email address rather than a username? I don't really see the difference and usernames are shorter to type :)

**Comment by cbeauchesne** [comment]
Agree with @Courgetteandratatouille : login with email tends to be a standard. And I think supporting both method could be the best of two worlds.

**Comment by lbesson** [comment]
fixed in #1416
