### ISSUE TITLE
Outing's information: add GPS attribute

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_api#683]
Add a boolean "has_track" attribute set to true when the `geom_detail` is set (no need to transfer the whole geometry when listing cards).

**Comment by desnoes** [comment]
see also : https://github.com/c2corg/v6_ui/issues/1549

**Comment by asaunier** [comment]
Extending this to route documents (actually: any document type with a ``geom_detail`` attribute) would make sense as well, and probably won't add extra work. That's what I did in PR #687
