### ISSUE TITLE
Review types of primary keys in model

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#69]
Some types are currently integers, instead of serials, for example:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/models/document.py#L196

The migration script also has to be updated to adapt the new sequences.

**Comment by gberaudo** [comment]
Shouldn't sequences be used automatically?

PostgreSQL supports sequences, and SQLAlchemy uses these as the default means of creating new primary key values for integer-based primary key columns. When creating tables, SQLAlchemy will issue the SERIAL datatype for integer-based primary key columns, which generates a sequence and server side default corresponding to the column.

http://docs.sqlalchemy.org/en/rel_1_0/dialects/postgresql.html

**Comment by tsauerwein** [comment]
True, I am looking at the same page right now. :)

**Comment by tsauerwein** [comment]
And integer is also fine as type (currently the sequence for document_archives is at 808153, so there is enough room left.
