### ISSUE TITLE
Move text format parsers from UI to API?

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#698]
As for now, the conversion of text formatting tags is done on the UI side:
https://github.com/c2corg/v6_ui/blob/1f20a7b13af88b4650f5aecd64b216377cc65481/c2corg_ui/templates/utils/__init__.py#L35
with parsers defined in https://github.com/c2corg/v6_ui/tree/master/c2corg_ui/format
Unit tests: https://github.com/c2corg/v6_ui/blob/5582dec49acee1f1acf850cff31f7f0f8f71cca4/c2corg_ui/tests/format/test_format.py

It might be interesting to move the parsing to the API and have it propose a "cooked" version of the text attributes, opposed to the current "raw" - unconverted - version that is needed anyway to fill the editing forms. This would avoid that every API client had to implement its own parsers.

Note that such a change would have an impact on the UI preview service, that uses the parsers on the UI side to convert the text attributes submitted by the editing forms, without any call to the API (data are not saved yet). See https://github.com/c2corg/v6_ui/blob/master/c2corg_ui/views/document.py#L405-L410

**Comment by cbeauchesne** [comment]
For the preview, we could develop an endpoint on API that accepts C2C markdown code, and returns cooked version?

**Comment by asaunier** [comment]
> For the preview, we could develop an endpoint on API that accepts C2C markdown code, and returns cooked version?

Well, the problem is that the current preview service uses the UI templates to render a preview similar to the real UI pages, but obviously those templates are not available on the API side. Which means the UI preview service (on the server) would have to make a call to the API endpoint you are mentioning to get the cooked data and insert them in the templates before sending the answer to the editing form in the UI client.
That's of course possible but add a bit of complexity to the tool.

**Comment by cbeauchesne** [comment]
But the template is still present on client side no? The only thing that is missing is the cooked version of each field, or did I miss something?

**Comment by asaunier** [comment]
> I propose that the preview service won't need any call to UI server, only the API one, and, as it should already have the template.

That's not possible because the API know nothing about how the UI renders its pages (using its templates). UI templates are available only on the UI server. See for instance templates ``view.html`` and ``preview.html`` of outings at https://github.com/c2corg/v6_ui/tree/master/c2corg_ui/templates/outing
Please note that both templates use helper functions that factorize the common HTML parts.

**Comment by cbeauchesne** [comment]
Ok I see. Not easy point. On a bigger picture, I guess that's a question of rendering pattern : on server side with pyramid templates, versus on client side with angular templates.

And I guess that's not, for the moment, the most urgent issue :)

**Comment by asaunier** [comment]
The preview could indeed be made by the UI client, using AngularJS etc.
But that means we would have 2 fully distinct renderers: 1 JS-based preview vs 1 python-based view. That would mean we could not factorize code between those 2 kinds of pages as it is currently the case => if a change is made in the "view", we would have to duplicate the change into the "preview" as well.
I think it would make more sense to have the UI server call the API to get cooked data.

Or perhaps we could use [v6_common](https://github.com/c2corg/v6_common) to have the parsers available both in the UI and in the API. It's a python module that is included both by [v6_ui](https://github.com/c2corg/v6_ui/blob/master/requirements.txt#L30) and [v6_api](https://github.com/c2corg/v6_api/blob/master/requirements.txt#L51). As for now it only contains some lists of attributes, but I guess we could move the parsers to it as well.

**Comment by cbeauchesne** [comment]
Having two distinct renderers is obviously not a good solution.

V6_common is the good solution, imo.

**Comment by asaunier** [comment]
I would use v6_common, because it's the place for common code, no need to add again another package, we already have enough complexity :)

**Comment by cbeauchesne** [comment]
I close this issue, as it's done :)
