### ISSUE TITLE
A bad doc url with an area ID return a error 500 instead of 404

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#707]
An url using a area ID but a bad doc type, return an error 500 instead of 404 : 
https://www.camptocamp.org/routes/14403
https://www.camptocamp.org/articles/14403

For a waypoint ID, it return an error 404 : 
https://www.camptocamp.org/routes/43071
https://www.camptocamp.org/articles/43071/fr

But if there is a slug, it returns a 500 : 
https://www.camptocamp.org/articles/43071/fr/slug

**Comment by cbeauchesne** [comment]
I observe : 

## 14403 is an area : https://www.camptocamp.org/areas/14403

* https://api.camptocamp.org/routes/14403 => 200 io 404
* https://api.camptocamp.org/articles/14403 => 200 io 404
* https://api.camptocamp.org/waypoints/14403 => 200 io 404

## 43071 is a waypoint : https://www.camptocamp.org/waypoints/43071

* https://api.camptocamp.org/routes/43071 => 200 io 404
* https://api.camptocamp.org/articles/43071 => 200 io 404
* https://api.camptocamp.org/articles/43071?cook=fr => 200 io 404

Basiclly, it returns the good document id, but foes not check the document type

**Comment by cbeauchesne** [comment]
FI, it's a cahcing issue. If the document is not in cache, it returns 404. If it's the cache, the cache key does not include document type, and thus returns the document only based on the id.

**Comment by cbeauchesne** [comment]
fixed one year ago
