### ISSUE TITLE
When saving a route change, useless versions are created if the route hasn't a GPX track

### ISSUE THREAD

**Issue by fbunoz** [c2corg/v6_api#714]
When we save a change of a route description (text only) in a language, and if the route hasn't a GPX track, a new version is also created for each other languages, containing no difference about the last version.
The behaviour is the same if we simply edit a route without GPX track and save it without any change : a new version is created for each language, with no difference about the last version.

Ex : for the route https://www.demov6.camptocamp.org/routes/54561/fr/pointe-de-la-grande-gliere-arete-s-voie-normale , the 4 following versions has been created by editing the FR route then saving it without any change.
https://www.demov6.camptocamp.org/routes/diff/54561/fr/1510359/1735109
https://www.demov6.camptocamp.org/routes/diff/54561/it/1510360/1735111
https://www.demov6.camptocamp.org/routes/diff/54561/en/1510358/1735112
https://www.demov6.camptocamp.org/routes/diff/54561/de/1510357/1735110

For https://www.demov6.camptocamp.org/routes/54591/fr/roche-faurio-versant-se-voie-normale , there is a GPX track.
Then a edit and save without change doesn't create any new version.
And an edit, change the text only, and save, create a new version for the modified language only (FR here) : 
https://www.demov6.camptocamp.org/routes/history/54591/fr
https://www.demov6.camptocamp.org/routes/history/54591/en

**Comment by cbeauchesne** [comment]
The issue has been fixed .
