### ISSUE TITLE
Restrict access to personnal document history and former version

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/v6_api#724]
Only moderators en documents'authors should have the right to access to history and former versions of personnal documents

**Comment by mgerbaux** [comment]
Authors are already displayed in the documents. Let's continue the discussion if needed on https://forum.camptocamp.org/t/restriction-de-lacces-a-lhistorique-des-documents-personnels/210913/5 ?

**Comment by cbeauchesne** [comment]
The discussion ended up with the conclusion of no-go. The solution for the root issue is to develop the ability for moderator to hide a given version in the history.
