### ISSUE TITLE
Add an association log service

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#729]
That would list the history of associations (creations and removals) for a given document.

- Data are already saved in table ``guidebook.association_log``. See model ``AssociationLog`` at
https://github.com/c2corg/v6_api/blob/3a5d5202da0ee49903b7ce495e141c41dce27892/c2corg_api/models/association.py#L78
- When an association is created or removed, a log entry is added in the table:
https://github.com/c2corg/v6_api/blob/3a5d5202da0ee49903b7ce495e141c41dce27892/c2corg_api/models/association.py#L157

**Comment by cbeauchesne** [comment]
Fixed a year ago :)
