### ISSUE TITLE
Sorting of search results

### ISSUE THREAD

**Issue by momomaniac** [c2corg/v6_api#757]
create API interface to pass sorting options over to elasticsearch

**Comment by momomaniac** [comment]
search command should use concatenation of different sort criteria separated by |
if one sort value is preceded by -, sort order is inversed
example:
`outings?q=belledonne&sort=-elevation_max|condition_rating`
shall sort the date by _descending elevation_ and _ascending conditions_

sort criteria must be defined for all _enum_ (like condition_rating) values, to avoid alphabetical sorting

**Comment by cbeauchesne** [comment]
Just **the** perfect spec, nothing to add nor remove :tada:

I would juste precise that order of criteria is important : `sort=<a>|<b>` is not the same as  `sort=<b>|<a>`.
And very fine polish : if nothing drives the choice of the separator, I would use comma instead of pipe, as it's the one used for other fields.

**Comment by momomaniac** [comment]
yep, agree with this, syntax shall use comma for consistency with other fields and sorting depends on order of variables.

Sorting of enum fields is handled correctly by postgres according to definition in common attribute file (https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py) ; enum order overrules alphabetic order &rarr; see PSQL example below
```
c2corg=# select frequentation, condition_rating, count(*)
            from guidebook.outings
            where frequentation is not null and condition_rating is not null
            group by 1, 2 order by 1, 2; 
 frequentation | condition_rating | count 
---------------+------------------+-------
 quiet         | excellent        | 19217
 quiet         | good             | 19824
 quiet         | average          |  7667
 quiet         | poor             |  1769
 quiet         | awful            |   243
 some          | excellent        | 15389
 some          | good             | 17344
 some          | average          |  5728
 some          | poor             |   940
 some          | awful            |    87
 crowded       | excellent        |  8349
 crowded       | good             |  9339
 crowded       | average          |  2541
 crowded       | poor             |   333
 crowded       | awful            |    34
 overcrowded   | excellent        |  3904
 overcrowded   | good             |  4061
 overcrowded   | average          |  1112
 overcrowded   | poor             |   174
 overcrowded   | awful            |    16
(20 rows)
```

**Comment by cbeauchesne** [comment]
Good news. That said, I'm not familiar with API model, but I think that request made on this route are sent to elastic, and I have no idea neither knowledge with elastic and sorting facilities.

@asaunier, do you remember how the API works on this point?

**Comment by cbeauchesne** [comment]
Hello @momomaniac,

Just saw your branch. You added sorting on `/search` route, which is not the good one :

* `/search` is used on the search bar on the top of the UI, it does not have any filtering, and does not need sorting 
* `/outings`, `/routes`, `/waypoints` ... are used on page like http://www.camptocamp.org/outings, http://www.camptocamp.org/routes, http://www.camptocamp.org/waypoints, and are the one where we need sorting

Really sorry for having forgot this one, and didn't precise it on the issue :(

**Comment by momomaniac** [comment]
the sort function is operational for both API entry points:

1. search view (less useful, but included for completeness, it would be hard to find an intelligent API integration)
1. document view (outings, routes, waypoints, etc.)

for both API entry points, there is an additional sort key, you can query
```
c2cAPI/search?q=blanc&t=w&sort=-elevation
```
or
```
c2cAPI/outings?act=skitouring&sort=-elevation_max,ski_rating
```
The UI allows for tests even without modifications, the sort term can be included manually in the URI, it is passed through to the API (this works for outings, etc. not for search). Sorted results are then displayed by the UI.

What I don't like about the current implementation is that the keys are literal and quite long ("conditions_rating", "elevation_max", etc.) as they are taken from common attributes. When several sort items are combined it may become messy. And furthermore I did not quite get the difference of how [attributes](https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py) and [sortable attributes](https://github.com/c2corg/v6_common/blob/master/c2corg_common/sortable_search_attributes.py) are used in the code.

Next step will be to include some tests and update documentation

**Comment by cbeauchesne** [comment]
> the sort function is operational for both API entry points:

Oh ! that's perfect. Sorry, I miss that, and I ran on my keyboard to avoid you a false direction :) 

> The UI allows for tests even without modifications

I confirm, I made this on purpose 😎 

> What I don't like about the current implementation is that the keys are literal and quite long 
 
Even if it'll be possible to have 10 sort keys (in this case, yes, it's pretty long...), users never use more than 3 sort fields. 90% of usages is one field and 99.9% is two fields or less. So IMO, not a big deal to have 40 chars in the URI for almost all the usages.

Furthermore, I'd want to avoid as possible to maintain one another ref. And as UI won't implement all fields, only the one in the 80-part of the 80/20 usage distribution. But we'll show to power-users (mainly moderators) how to hack the URI with keywords they still know => not a good idea to ask them to lean the new ref.

> And furthermore I did not quite get the difference of how attributes and sortable attributes are used in the code.

Neither do I. I'll take a look tomorrow

**Comment by momomaniac** [comment]
I prepared the PR #758 with first tests, but It's not quite finished.

- test is done for sorting function in view outings
- test for generic search entry point is still missing (but we said it's a minor feature, the code might just be removed.)

There are separate test files for each document type, but the sorting mechanism is the same.  So I stopped before writing a test for each data type. Sorted results of a test must be checked individually for each data type depending on the test dataset for each data type. So refactoring these tests is not trivial. The sorting mecanism is implemented in [search_filters](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/search/search_filters.py#L48), so this part must be covered by tests. I see two solutions:
1. leave it as is, the sort clause is covered by a single test in [test_outings](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/tests/views/test_outing.py) - this is a bit asymetric, but it works and achieves test coverage.
2. refactor to test it directly in class [BaseDocumentTestRest](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/tests/views/__init__.py#L124), but I have not found yet how to do this in a parent class

I have one finding which was a bit surprising and got me some headache, one can ask for sorting by `height_diff_down` or `elevation_min`, but it has no effect on the result. Maybe these parameters are not indexed in elasticSearch ??? We must clarify which parameters will work to avoid surprises, all do not seem to work due to an obscure filter somewhere (at least it's obscure to me)

**Comment by cbeauchesne** [comment]
> And furthermore I did not quite get the difference of how attributes and sortable attributes are used in the code.

On some filters, you can add two values : 
 
     /routes?quality=empty,medium

It does not means `empty OR medium` but all qualities between `empty` and `medium`, boundaries included.

I guess that sortable attributes are used here ton construct all possible values between two boundaries.

**Comment by cbeauchesne** [comment]
> test for generic search entry point is still missing (but we said it's a minor feature, the code might just be removed.)

We'll certainly not use it, I think you can remove the code.

> So refactoring these tests is not trivial

I plan to do it soon. As now, it's plenty of boilerplate, and overetesting. So do not brainwash yourself, do simple : 

* just test on routes, waypoints, and outings
* on only one doc type (as the logic is shared on all doc type, it's ok to only test one) : 
  * try one and two filters
  * one ASC and one DESC
  * and a combinaizon with numeric-like filter and rating filter, for instance, climbing rating and elevation.

> I have one finding which was a bit surprising and got me some headache, one can ask for sorting by height_diff_down or elevation_min, but it has no effect on the result. Maybe these parameters are not indexed in elasticSearch ??? We must clarify which parameters will work to avoid surprises, all do not seem to work due to an obscure filter somewhere (at least it's obscure to me)

No idea, maybe @asaunier  ?

**Comment by asaunier** [comment]
> No idea, maybe @asaunier ?

Sorry, I don't know either: it's old for me and the ES part (and most of the API) was designed by @tsauerwein

**Comment by tsauerwein** [comment]
> I have one finding which was a bit surprising and got me some headache, one can ask for sorting by height_diff_down or elevation_min, but it has no effect on the result. Maybe these parameters are not indexed in elasticSearch ?

Not sure anymore. I guess you already found the [mappings](https://github.com/c2corg/v6_api/tree/master/c2corg_api/search/mappings)? Though it's probably easier to take a look at the mapping in ES.

**Comment by momomaniac** [comment]
thanks @tsauerwein , I had quickly looked at the mappings, but now I realized the difference between models and mappings.
And actually, there is `height_diff_down` in [model outing](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/models/outing.py#L55), but not in [outing mapping](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/search/mappings/outing_mapping.py), so `height_diff_down` is neither searchable nor sortable.
I think for the moment, we can leave this inconsistency (maybe it's done on purpose), we know that some fields can not be sorted. And maybe harmonize later on ?

@cbeauchesne : test for one filter, two filters, asc and desc is done, I will add a test for a mix of numeric and qualitative fields, that's a good idea.

**Comment by momomaniac** [comment]
OK done, I have a test for enum + numeric criteria and an additional test for erroneous criteria

I continued to look at the column keys
the whole thing starts getting a bit clearer to me. There is a mapping between all fields available for documents defined in the [document model](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/models/outing.py#L55) and the queryable fields defined in [search mapping](https://github.com/c2corg/v6_api/blob/b6f16229718d837b16e89c1ee0337fe4c264c0e4/c2corg_api/search/mappings/outing_mapping.py)

Model fields are like `elevation_max`, `conditions_rating`
Queryable fields are like `oalt`, `ocond`

All model fields are declared to the elasticsearch index, however, data is only filled for queryable fields. Therefore when using a non queryable field (for search or for sorting), no error is raised by ES, but the information is ignored silently.

The best solution would be to harmonize the mapping between Model Fields and Queryable Fields ( there are also multiple mappings for a single Model Field, ex. `elevation_max` is `oalt` for outings but `rmaxa` for routes, but `ski_rating` is `trat` for both outings and routes). This might be difficult and break features, there is probably a historic reason for these mappings.

The basic solution can be a simple check, that the sort field is among the queryable fields, and raise an error otherwise. In this case, some fields cannot be used, for ex. `elevation_min`

for info, list of non-queryable fields by document type:
```
{
    "x": [
        "rescue",
        "disable_comments",
        "safety",
        "other_comments",
        "motivations",
        "previous_injuries",
        "gender",
        "activity_rate",
        "reduce_impact",
        "place",
        "modifications",
        "anonymous",
        "route_study",
        "conditions",
        "risk",
        "autonomy",
        "age",
        "time_management",
        "nb_outings",
        "training",
        "author_status",
        "increase_impact",
        "group_management"
    ],
    "i": [
        "height",
        "fnumber",
        "exposure_time",
        "camera_name",
        "file_size",
        "width",
        "focal_length",
        "iso_speed",
        "filename",
        "author"
    ],
    "b": [
        "url",
        "langs",
        "nb_pages",
        "editor",
        "isbn",
        "publication_date",
        "author"
    ],
    "w": [
        "heating_unstaffed",
        "phone",
        "slackline_length_min",
        "maps_info",
        "url",
        "gas_unstaffed",
        "parking_fee",
        "access",
        "access_period",
        "slope",
        "ground_types",
        "slackline_length_max",
        "phone_custodian",
        "elevation_min",
        "slackline_types",
        "matress_unstaffed",
        "blanket_unstaffed"
    ],
    "c": [
        "categories"
    ],
    "m": [
        "code",
        "scale",
        "editor"
    ],
    "u": [
        "categories",
        "activities"
    ],
    "a": [],
    "r": [
        "gear",
        "lift_access",
        "slackline_height",
        "slope",
        "route_history",
        "slackline_anchor1",
        "remarks",
        "main_waypoint_id",
        "external_resources",
        "slackline_anchor2"
    ],
    "o": [
        "conditions_levels",
        "disable_comments",
        "participants",
        "weather",
        "access_condition",
        "height_diff_down",
        "hut_comment",
        "timing",
        "hut_status",
        "partial_trip",
        "elevation_min",
        "avalanches",
        "route_description",
        "lift_status",
        "access_comment",
        "conditions",
        "participant_count"
    ]
}
```

obtained by a little script:
```from c2corg_api import models as m
from c2corg_api.search import search_documents
import json
myMap = {'a': m.area, 'c': m.article, 'i': m.image, 'm': m.topo_map, 'o' : m.outing, 'r': m.route, 'u': m.user_profile, 'w': m.waypoint, 'b': m.book, 'x': m.xreport}
myRes = {k: list(set(v.attributes).union(v.attributes_locales if hasattr(v, 'attributes_locales') else []) - set(search_documents[k].FIELDS).union(search_documents[k].ENUM_RANGE_FIELDS if hasattr(search_documents[k], 'ENUM_RANGE_FIELDS') else [])) for (k, v) in myMap.items()}
print(json.dumps(myRes, indent=4))
```

**Comment by brunobesson** [comment]
Historical reasons => probably the criteria from v5, to ensure reasonable
retrocompatibility

Le jeu. 21 nov. 2019 à 15:13, momomaniac <notifications@github.com> a
écrit :
