### ISSUE TITLE
Bad error message when header Content-Type is missing

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#8]
When POSTing a new waypoint, if the Content-Type header is missing, one gets a "missing waypoint_type" error even though the waypoint_type is correctly set.
This is confusing.

**Comment by tsauerwein** [comment]
I think this could be fixed by setting `content_type` for `@resource` or `@view`:
http://cornice.readthedocs.org/en/latest/api.html

**Comment by tsauerwein** [comment]
Maybe not, because by default all content types are accepted:
http://cornice.readthedocs.org/en/latest/exhaustive_list.html#content-types-ingress

I will have to take a closer look.

**Comment by gberaudo** [comment]
Restricting the allowed content types to `application/json` should fix the
issue, right?
Is it possible to do it globally?

**Comment by tsauerwein** [comment]
> Restricting the allowed content types to `application/json` should fix the issue, right?

Yes, that should work.

> Is it possible to do it globally?

I couldn't find an option in Cornice. But we could [extend](https://docs.python.org/2/library/functools.html#functools.wraps) [@ressource or @view](https://github.com/mozilla-services/cornice/blob/master/cornice/resource.py) with a default value for the content-type.
