### ISSUE TITLE
Add Chinese lang

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/v6_api#856]

**Comment by brunobesson** [comment]
@cbeauchesne does it relate to #1036 or is there more to do?

**Comment by cbeauchesne** [comment]
yes, you can't set chinese as prefered lang, as it doesn't exists from API POV :(

**Comment by brunobesson** [comment]
My question was, is there more to do than adding chinese to languages? E.g indexation and such?

**Comment by cbeauchesne** [comment]
I think there is some work on elastic search (even naive, it would be known if we were good on the search engine :) ), and a small modif on DB (can't remember which one though)
