### ISSUE TITLE
Abuse detection

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#9]
[NEEDS TO BE PRECISED]

We need to figure out what "abusive use" means.

READ:
- frequency of requests (max x req/s => how to check this?)
- ??

WRITE:
- frequency of requests (max x req/s => how to check this?)
- ??

**Comment by asaunier** [comment]
What kind of tools should we use for detecting abusing usages?
Not sure it is something to do directly in the API app, perhaps more in a monitoring tool?

See for instance the rationale of Cliquet:
http://cliquet.readthedocs.org/en/latest/rationale.html#toolkit

**Comment by tsauerwein** [comment]
Maybe the Apache module "mod_dosevasive" could be an option:
http://www.arunkarthick.com/2007/01/moddosevasive-in-apache.html

It's very simple, it checks that there are not too many requests in a specified timespan for the same IP.

See also:
http://www.fail2ban.org/wiki/index.php/Main_Page
http://stackoverflow.com/questions/131681/how-can-i-implement-rate-limiting-with-apache-requests-per-second

**Comment by gberaudo** [comment]
Unfortunately, one IP !== from one user.
What mechanism do we have in v5?

**Comment by asaunier** [comment]
> What mechanism do we have in v5?

None

**Comment by tsauerwein** [comment]
> Unfortunately, one IP !== from one user.

True. But what else could you check for?

**Comment by asaunier** [comment]
Nothing done about abuse detection yet.
By the way is it possible to block a suspect user account?

**Comment by tsauerwein** [comment]
> By the way is it possible to block a suspect user account?

Currently there is no web-service to disable an account.

**Comment by asaunier** [comment]
Not sure a web service is really needed because this is a very uncommon case, it could be done by hand in the database for instance. 
Is it possible to block an account by switching some flag for instance?

**Comment by asaunier** [comment]
Hints discussed within the association:
* limit the number of editions that a user can do in a given amount of time
* short term: use the UI as a proxy in front of the API and reject any write request that does not come from the UI servers (only "local" requests?) [suggested by @mfournier ]
* long term: implement an API key system with rate-limit &
blacklist (or install an existing system) [suggested by @mfournier ]
* rate-limit checks may be skipped for moderators

**Comment by asaunier** [comment]
> Can you explain ? How does it work with external partners that want to access the API (mobile app, university of Lyon (Petzl))?

Read access would still be possible through direct access to the API. Not write access.

**Comment by cbeauchesne** [comment]
Rate limiting is implemented, close issue.
