### ISSUE TITLE
Don't save secret config on github

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#99]
For instance:
https://github.com/c2corg/v6_api/blob/36c729ef1205dd3994dec31f24ff36f8c25baa1c/config/default#L68
https://github.com/c2corg/v6_api/blob/36c729ef1205dd3994dec31f24ff36f8c25baa1c/config/default#L12

**Comment by asaunier** [comment]
@mfournier @arnaud-morvan Do we have a solution for this?

Should we use Travis as for the Transifex password in the UI: https://github.com/c2corg/v6_ui/blob/master/.travis.yml#L21-L37
?

**Comment by mfournier** [comment]
So as @arnaud-morvan mentioned by email, here's the trick: https://github.com/c2corg/v6_api/blob/master/docker-entrypoint.d/10-env-replace.sh gets run at container startup, so each environment variable passed to the container will *override* the matching value in the `config/docker` file.

This means dummy usernames/passwords/api key/etc can be commited to the git repo, and the actual secrets will be defined as envvars in the docker composition file(s), which we won't put on github.

Closing this issue, as it seems to just be a misunderstanding.

**Comment by asaunier** [comment]
I prefer reopening the issue because there's probably some work to do to remove those secret keys from the config (even though no longer used?):
https://github.com/c2corg/v6_api/blob/master/config/default#L70-L75
